@php
    $settings = is_array($node['settings'] ?? null) ? $node['settings'] : [];
    $nodeId = trim((string) ($node['id'] ?? 'alert')) ?: 'alert';
    $safeLength = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?(?:px|pt|%|em|rem|vw|vh)?$/i', $raw) ? $raw : $fallback; };
    $safeColor = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return $raw !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $raw) ? $raw : $fallback; };
    $enum = fn (mixed $value, array $allowed, string $fallback): string => in_array(strtolower(trim((string) $value)), $allowed, true) ? strtolower(trim((string) $value)) : $fallback;
    $responsive = function (string $base, string $suffix = '', mixed $fallback = '') use ($settings): mixed { $keys = $suffix === 'Mobile' ? [$base.'Mobile', $base.'Tablet', $base] : ($suffix === 'Tablet' ? [$base.'Tablet', $base] : [$base]); foreach ($keys as $key) { if (($settings[$key] ?? '') !== '' && ($settings[$key] ?? null) !== null) return $settings[$key]; } return $fallback; };
    $fontStyle = function (string $prefix, string $suffix = '') use ($settings, $responsive, $safeLength, $safeColor): string { $size = $prefix === 'title' ? '18px' : '14px'; $line = $prefix === 'title' ? '1.3em' : '1.5em'; $weight = preg_match('/^(?:normal|bold|[1-9]00)$/', trim((string) ($settings[$prefix.'FontWeight'] ?? '400'))) ? trim((string) ($settings[$prefix.'FontWeight'] ?? '400')) : '400'; $shadow = trim((string) ($settings[$prefix.'TextShadow'] ?? 'none')); $shadow = $shadow !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $shadow) ? $shadow : 'none'; return implode(';', ['font-family:inherit','font-size:'.$safeLength($responsive($prefix.'FontSize', $suffix, $size), $size),'font-weight:'.$weight,'line-height:'.$safeLength($responsive($prefix.'LineHeight', $suffix, $line), $line),'letter-spacing:'.$safeLength($responsive($prefix.'LetterSpacing', $suffix, '0px'), '0px'),'word-spacing:'.$safeLength($responsive($prefix.'WordSpacing', $suffix, '0px'), '0px'),'text-transform:'.($settings[$prefix.'TextTransform'] ?? 'none'),'font-style:'.($settings[$prefix.'FontStyle'] ?? 'normal'),'text-decoration:'.($settings[$prefix.'TextDecoration'] ?? 'none'),'color:'.$safeColor($settings[$prefix.'Color'] ?? '', 'inherit'),'text-shadow:'.$shadow]); };
    $description = strip_tags((string) ($settings['description'] ?? ''), '<p><br><strong><em><b><i><a><ul><ol><li>');
    $type = $enum($settings['type'] ?? 'info', ['info','success','warning','danger'], 'info'); $vertical = $enum($settings['dismissVerticalPosition'] ?? 'top', ['top','middle','bottom'], 'top'); $horizontal = $enum($settings['dismissHorizontalPosition'] ?? 'right', ['left','right'], 'right');
    $svg = ''; if (($settings['dismissIconSource'] ?? '') === 'svg') { $rawSvg = trim((string) ($settings['dismissIconSvg'] ?? '')); $rawSvg = preg_replace('/<script\b[^>]*>.*?<\/script>/is', '', $rawSvg) ?? ''; $rawSvg = preg_replace('/\s(?:on[a-z]+|style|xlink:href|href)\s*=\s*(?:"[^"]*"|\'[^\']*\'|[^\s>]+)/i', '', $rawSvg) ?? ''; $svg = str_starts_with(strtolower($rawSvg), '<svg') ? strip_tags($rawSvg, '<svg><g><path><circle><ellipse><rect><line><polyline><polygon><title><desc>') : ''; }
    $dismissClass = preg_match('/^(?:fas|far|fab|fal|fad)\s+fa-[a-z0-9-]+$/i', trim((string) ($settings['dismissIconClass'] ?? ''))) ? trim((string) $settings['dismissIconClass']) : 'fas fa-times';
    $advanced = app(\App\Support\PageBuilderElementorV23\WidgetAdvancedStyleResolver::class)->resolve($settings, $nodeId, request()); $rootClasses = array_values(array_unique(array_merge(['el-widget-alert','pb-alert','pb-alert--'.$type,'pb-alert--dismiss-'.$vertical.'-'.$horizontal], $advanced['classes']))); $rootStyle = implode(';', ['--pb-alert-bg:'.$safeColor($settings['backgroundColor'] ?? '', '#eaf4ff'),'--pb-alert-border:'.$safeColor($settings['borderColor'] ?? '', '#b6d7fe'),'--pb-alert-border-width:'.$safeLength($settings['borderWidth'] ?? '4px', '4px'),'--pb-alert-dismiss-color:'.$safeColor($settings['dismissColor'] ?? '', '#344054'),'--pb-alert-dismiss-hover:'.$safeColor($settings['dismissColorHover'] ?? '', '#101828'),'--pb-alert-dismiss-duration:'.max(0, min(10, (float) ($settings['dismissTransitionDuration'] ?? .3))).'s']);
@endphp
<div id="{{ $advanced['id'] }}" class="{{ implode(' ', $rootClasses) }}" style="{{ $rootStyle }}" role="alert" data-entrance-delay="{{ $advanced['entranceDelay'] }}" data-entrance-duration="{{ $advanced['entranceDuration'] }}" @foreach($advanced['attributes'] as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>
    <div class="pb-alert__body">@if(trim((string) ($settings['title'] ?? '')) !== '')<div class="pb-alert__title" style="{{ $fontStyle('title') }}">{{ (string) $settings['title'] }}</div>@endif @if(trim((string) ($settings['description'] ?? '')) !== '')<div class="pb-alert__description" style="{{ $fontStyle('description') }}">{!! $description !!}</div>@endif</div>
    @if(!empty($settings['dismissIcon']))<button type="button" class="pb-alert__dismiss" data-pb-alert-dismiss aria-label="Dismiss alert" style="font-size:{{ $safeLength($settings['dismissSize'] ?? '16px', '16px') }}">@if($svg !== ''){!! $svg !!}@else<i class="{{ $dismissClass }}" aria-hidden="true"></i>@endif</button>@endif
</div>
<style>{!! $advanced['css'] !!}</style>
<script>
(function(){ const bind = () => document.querySelectorAll('[data-pb-alert-dismiss]').forEach((button) => { if (button.dataset.pbAlertReady === '1') return; button.dataset.pbAlertReady = '1'; button.addEventListener('click', () => { const root = button.closest('[role="alert"]'); if (root) root.hidden = true; }); }); if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', bind, { once:true }); else bind(); })();
</script>
