@php
    $settings = is_array($node['settings'] ?? null) ? $node['settings'] : [];
    $nodeId = trim((string) ($node['id'] ?? 'testimonial')) ?: 'testimonial';
    $safeLength = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?(?:px|pt|%|em|rem|vw|vh)?$/i', $raw) ? $raw : $fallback; };
    $safeColor = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return $raw !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $raw) ? $raw : $fallback; };
    $safeUrl = function (mixed $value): string { $url = trim((string) $value); return $url !== '' && !str_starts_with($url, '//') && preg_match('/^(?:https?:|mailto:|tel:|\/|#)/i', $url) ? $url : ''; };
    $enum = fn (mixed $value, array $allowed, string $fallback): string => in_array(strtolower(trim((string) $value)), $allowed, true) ? strtolower(trim((string) $value)) : $fallback;
    $responsive = function (string $base, string $suffix = '', mixed $fallback = '') use ($settings): mixed { $keys = $suffix === 'Mobile' ? [$base.'Mobile', $base.'Tablet', $base] : ($suffix === 'Tablet' ? [$base.'Tablet', $base] : [$base]); foreach ($keys as $key) { if (($settings[$key] ?? '') !== '' && ($settings[$key] ?? null) !== null) return $settings[$key]; } return $fallback; };
    $fontStyle = function (string $prefix, string $suffix = '') use ($settings, $responsive, $safeLength, $safeColor): string { $size = $prefix === 'content' ? '16px' : ($prefix === 'name' ? '18px' : '14px'); $line = $prefix === 'content' ? '1.5em' : ($prefix === 'name' ? '1.3em' : '1.4em'); $weight = preg_match('/^(?:normal|bold|[1-9]00)$/', trim((string) ($settings[$prefix.'FontWeight'] ?? '400'))) ? trim((string) ($settings[$prefix.'FontWeight'] ?? '400')) : '400'; $shadow = trim((string) ($settings[$prefix.'TextShadow'] ?? 'none')); $shadow = $shadow !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $shadow) ? $shadow : 'none'; return implode(';', ['font-family:inherit','font-size:'.$safeLength($responsive($prefix.'FontSize', $suffix, $size), $size),'font-weight:'.$weight,'line-height:'.$safeLength($responsive($prefix.'LineHeight', $suffix, $line), $line),'letter-spacing:'.$safeLength($responsive($prefix.'LetterSpacing', $suffix, '0px'), '0px'),'word-spacing:'.$safeLength($responsive($prefix.'WordSpacing', $suffix, '0px'), '0px'),'text-transform:'.($settings[$prefix.'TextTransform'] ?? 'none'),'font-style:'.($settings[$prefix.'FontStyle'] ?? 'normal'),'text-decoration:'.($settings[$prefix.'TextDecoration'] ?? 'none'),'color:'.$safeColor($settings[$prefix.'Color'] ?? '', 'inherit'),'text-shadow:'.$shadow]); };
    $content = strip_tags((string) ($settings['content'] ?? ''), '<p><br><strong><em><b><i><a><ul><ol><li>');
    $content = preg_replace_callback('/<a\b([^>]*)>/i', function (array $match) use ($safeUrl): string { preg_match('/\bhref\s*=\s*["\']([^"\']*)["\']/i', $match[1], $href); $url = $safeUrl($href[1] ?? ''); return $url !== '' ? '<a href="'.e($url).'">' : ''; }, $content) ?? '';
    $imageUrl = trim((string) ($settings['imageUrl'] ?? ''));
    $imageUrl = $imageUrl !== '' && !str_starts_with($imageUrl, '//') && preg_match('/^(?:https?:|data:image\/|\/)/i', $imageUrl) ? $imageUrl : '';
    if ($imageUrl !== '') { $resolution = $enum($settings['imageResolution'] ?? 'full', ['thumbnail','medium','medium_large','large','1536x1536','2048x2048','full','custom'], 'full'); $imageUrl = app(\App\Support\PageBuilderElementorV23\ImageRenditionResolver::class)->resolve($imageUrl, $resolution, $resolution === 'custom' ? max(1, min(4096, (int) ($settings['customImageWidth'] ?? 300))) : null, $resolution === 'custom' ? max(1, min(4096, (int) ($settings['customImageHeight'] ?? 300))) : null); }
    $imagePosition = $enum($settings['imagePosition'] ?? 'top', ['top','left','right'], 'top'); $alignment = $enum($settings['alignment'] ?? 'center', ['left','center','right','justify'], 'center'); $borderType = $enum($settings['imageBorderType'] ?? 'none', ['none','solid','double','dotted','dashed','groove'], 'none'); $imageSize = $safeLength($responsive('imageSize', '', '80px'), '80px'); $imageRadius = $safeLength($responsive('imageBorderRadius', '', '50%'), '50%');
    $linkUrl = $safeUrl($settings['linkUrl'] ?? ''); $target = ($settings['linkTarget'] ?? '') === '_blank' ? '_blank' : ''; $rel = $target === '_blank' ? ['noopener','noreferrer'] : []; if (!empty($settings['linkNofollow'])) $rel[] = 'nofollow'; $rel = implode(' ', array_unique($rel));
    $customAttributes = []; foreach (($settings['linkCustomAttributes'] ?? []) as $attribute) { if (!is_array($attribute)) continue; $name = strtolower(trim((string) ($attribute['key'] ?? $attribute['name'] ?? ''))); if (!preg_match('/^(?:aria-[a-z0-9_-]+|data-[a-z0-9_-]+|title|download|hreflang)$/', $name)) continue; $customAttributes[$name] = (string) ($attribute['value'] ?? ''); }
    $advanced = app(\App\Support\PageBuilderElementorV23\WidgetAdvancedStyleResolver::class)->resolve($settings, $nodeId, request()); $rootClasses = array_values(array_unique(array_merge(['el-widget-testimonial','pb-testimonial','pb-testimonial--position-'.$imagePosition], $advanced['classes'])));
    $rootStyle = implode(';', ['display:flex','flex-direction:'.($imagePosition === 'right' ? 'row-reverse' : ($imagePosition === 'left' ? 'row' : 'column')),'align-items:'.($imagePosition === 'top' ? ($alignment === 'left' ? 'flex-start' : ($alignment === 'right' ? 'flex-end' : ($alignment === 'justify' ? 'stretch' : 'center'))) : 'center'),'text-align:'.$alignment,'gap:'.($imagePosition === 'top' ? '16px' : '20px')]);
    $mediaRules = []; foreach (['Tablet'=>1024,'Mobile'=>767] as $suffix=>$breakpoint) { $currentPosition = $enum($responsive('imagePosition', $suffix, 'top'), ['top','left','right'], 'top'); $currentAlignment = $enum($responsive('alignment', $suffix, 'center'), ['left','center','right','justify'], 'center'); $currentDirection = $currentPosition === 'right' ? 'row-reverse' : ($currentPosition === 'left' ? 'row' : 'column'); $currentItems = $currentPosition === 'top' ? ($currentAlignment === 'left' ? 'flex-start' : ($currentAlignment === 'right' ? 'flex-end' : ($currentAlignment === 'justify' ? 'stretch' : 'center'))) : 'center'; $mediaRules[] = '@media (max-width: '.$breakpoint.'px){#'.$advanced['id'].'{flex-direction:'.$currentDirection.';align-items:'.$currentItems.';text-align:'.$currentAlignment.'}#'.$advanced['id'].' .pb-testimonial__image{width:'.$safeLength($responsive('imageSize', $suffix, '80px'), '80px').';height:'.$safeLength($responsive('imageSize', $suffix, '80px'), '80px').'}#'.$advanced['id'].' .pb-testimonial__content{'.$fontStyle('content', $suffix).'}#'.$advanced['id'].' .pb-testimonial__name{'.$fontStyle('name', $suffix).'}#'.$advanced['id'].' .pb-testimonial__title{'.$fontStyle('title', $suffix).'}}'; }
@endphp
<div id="{{ $advanced['id'] }}" class="{{ implode(' ', $rootClasses) }}" style="{{ $rootStyle }}" data-entrance-delay="{{ $advanced['entranceDelay'] }}" data-entrance-duration="{{ $advanced['entranceDuration'] }}" @foreach($advanced['attributes'] as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>
    <div class="pb-testimonial__media">@if($imageUrl !== '') @if($linkUrl !== '')<a class="pb-testimonial__image-link" href="{{ $linkUrl }}" @if($target !== '') target="{{ $target }}" @endif @if($rel !== '') rel="{{ $rel }}" @endif @foreach($customAttributes as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach><img class="pb-testimonial__image" src="{{ $imageUrl }}" alt="{{ e((string) ($settings['imageAlt'] ?? '')) }}" style="width:{{ $imageSize }};height:{{ $imageSize }};object-fit:cover;border-style:{{ $borderType }};border-width:{{ $borderType === 'none' ? '0' : $safeLength($settings['imageBorderWidth'] ?? '1px', '1px') }};border-color:{{ $safeColor($settings['imageBorderColor'] ?? '', '#d0d7e6') }};border-radius:{{ $imageRadius }}"></a>@else<img class="pb-testimonial__image" src="{{ $imageUrl }}" alt="{{ e((string) ($settings['imageAlt'] ?? '')) }}" style="width:{{ $imageSize }};height:{{ $imageSize }};object-fit:cover;border-style:{{ $borderType }};border-width:{{ $borderType === 'none' ? '0' : $safeLength($settings['imageBorderWidth'] ?? '1px', '1px') }};border-color:{{ $safeColor($settings['imageBorderColor'] ?? '', '#d0d7e6') }};border-radius:{{ $imageRadius }}">@endif @else<div class="pb-testimonial__empty-image" role="img" aria-label="Choose an image"><i class="far fa-user" aria-hidden="true"></i></div>@endif</div>
    <div class="pb-testimonial__body"><div class="pb-testimonial__content" style="{{ $fontStyle('content') }}">{!! $content !!}</div>@if(trim((string) ($settings['name'] ?? '')) !== '') @if($linkUrl !== '')<a class="pb-testimonial__name-link" href="{{ $linkUrl }}" @if($target !== '') target="{{ $target }}" @endif @if($rel !== '') rel="{{ $rel }}" @endif><span class="pb-testimonial__name" style="{{ $fontStyle('name') }}">{{ (string) $settings['name'] }}</span></a>@else<span class="pb-testimonial__name" style="{{ $fontStyle('name') }}">{{ (string) $settings['name'] }}</span>@endif @endif @if(trim((string) ($settings['title'] ?? '')) !== '')<span class="pb-testimonial__title" style="{{ $fontStyle('title') }}">{{ (string) $settings['title'] }}</span>@endif</div>
</div>
<style>{!! $advanced['css'] . implode('', $mediaRules) !!}</style>
