<template>
	<div class="pb-widget-settings pb-widget-settings--general-new pb-widget-settings--social-icons">
		<div class="pb-tab-nav"><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button></div>
		<div v-if="editor.settingsTab==='content'" class="pb-tab-content"><details class="pb-collapsible" open><summary>Social Icons</summary><div class="pb-collapsible-body">
			<div class="pb-form-group"><div class="pb-label-row"><label class="pb-form-label mb-0">Items</label><span class="pb-form-hint">{{node.settings.items.length}} icons</span></div><div class="pb-social-repeater">
				<div v-for="(entry,index) in node.settings.items" :key="entry.id" class="pb-social-repeater__item" :class="{'is-open':expandedId===entry.id}">
					<div class="pb-social-repeater__header" role="button" tabindex="0" :aria-expanded="expandedId===entry.id?'true':'false'" @click="toggle(entry.id)" @keydown.enter.prevent="toggle(entry.id)" @keydown.space.prevent="toggle(entry.id)"><i class="fas pb-social-repeater__disclosure" :class="expandedId===entry.id?'fa-chevron-up':'fa-chevron-down'" aria-hidden="true"></i><span class="pb-social-repeater__title"><i :class="entry.iconClass || 'fas fa-star'"></i><span>{{entry.iconName || ('Icon '+(index+1))}}</span></span><span class="pb-social-repeater__actions"><button type="button" title="Duplicate Item" aria-label="Duplicate item" @click.stop="duplicate(entry)"><i class="far fa-copy"></i></button><button type="button" title="Remove Item" aria-label="Remove item" :disabled="node.settings.items.length<=1" @click.stop="remove(entry.id)"><i class="fas fa-times"></i></button></span></div>
					<div v-if="expandedId===entry.id" class="pb-social-repeater__body"><div class="pb-form-group"><label class="pb-form-label">Icon</label><div class="pb-general-icon-picker"><button type="button" class="pb-icon-picker-field" @click="editor.openSocialIconLibrary(entry.id,node)"><div class="pb-icon-picker-preview"><i :class="entry.iconClass || 'fas fa-icons'"></i></div><div class="pb-icon-picker-copy"><div class="pb-icon-picker-name">{{iconLabel(entry)}}</div><div class="pb-icon-picker-style">{{entry.iconSource==='svg'?'Custom SVG':editor.fontAwesomeStyleLabel(entry.iconStyle||'brands')}}</div></div><i class="fas fa-chevron-right"></i></button><div class="pb-general-icon-picker__actions"><button type="button" title="Upload SVG" aria-label="Upload SVG" @click="editor.chooseSocialIconSvg(entry.id,node)"><i class="fas fa-upload"></i></button><button type="button" title="Reset Icon" aria-label="Reset icon" @click="clearIcon(entry)"><i class="fas fa-undo"></i></button></div></div></div><div class="pb-form-group"><label class="pb-form-label">Link</label><component :is="editor.linkControl" :url="entry.linkUrl" :target="entry.linkTarget" :nofollow="entry.linkNofollow" :custom-attributes="entry.linkCustomAttributes" @update:url="entry.linkUrl=$event" @update:target="entry.linkTarget=$event" @update:nofollow="entry.linkNofollow=$event" @update:customAttributes="entry.linkCustomAttributes=$event" /></div><div class="pb-form-group"><label class="pb-form-label">Color</label><select class="pb-select" v-model="entry.colorMode"><option value="official">Official</option><option value="custom">Custom</option></select></div><div v-if="entry.colorMode==='custom'" class="pb-form-row pb-form-row--two"><color-control label="Primary" setting-key="primaryColor" :entry="entry" /><color-control label="Secondary" setting-key="secondaryColor" :entry="entry" /></div></div>
				</div><button type="button" class="pb-social-add" @click="add"><i class="fas fa-plus"></i><span>Add Item</span></button>
			</div></div>
			<div class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Shape</label><select class="pb-select" v-model="node.settings.shape"><option value="rounded">Rounded</option><option value="square">Square</option><option value="circle">Circle</option></select></div><div class="pb-form-group"><label class="pb-form-label">Columns</label><select class="pb-select" v-model="node.settings.columns"><option value="auto">Auto</option><option v-for="column in 6" :key="column" :value="String(column)">{{column}}</option></select></div></div>
			<responsive-choice label="Alignment" base="alignment" control-id="social-icons-alignment" :node="node" :editor="editor" :options="alignmentOptions" />
		</div></details></div>
		<div v-if="editor.settingsTab==='style'" class="pb-tab-content"><details class="pb-collapsible" open><summary>Social Icons</summary><div class="pb-collapsible-body">
			<div class="pb-state-tabs pb-state-tabs--two"><button type="button" :class="{active:colorState==='normal'}" @click="colorState='normal'">Normal</button><button type="button" :class="{active:colorState==='hover'}" @click="colorState='hover'">Hover</button></div>
			<div class="pb-form-group"><label class="pb-form-label">Color</label><select class="pb-select" v-model="node.settings[colorState==='normal'?'colorMode':'colorModeHover']"><option value="official">Official</option><option value="custom">Custom</option></select></div>
			<div v-if="node.settings[colorState==='normal'?'colorMode':'colorModeHover']==='custom'" class="pb-form-row pb-form-row--two"><color-control :label="colorState==='normal'?'Primary':'Hover Primary'" :setting-key="colorState==='normal'?'primaryColor':'primaryColorHover'" :node="node" /><color-control :label="colorState==='normal'?'Secondary':'Hover Secondary'" :setting-key="colorState==='normal'?'secondaryColor':'secondaryColorHover'" :node="node" /></div>
			<size-control label="Size" base="size" control-id="social-icons-size" fallback="18px" :node="node" :editor="editor" :min="8" :max="80" /><size-control label="Padding" base="padding" control-id="social-icons-padding" fallback="10px" :node="node" :editor="editor" :min="0" :max="60" /><size-control label="Spacing" base="spacing" control-id="social-icons-spacing" fallback="8px" :node="node" :editor="editor" :min="0" :max="80" /><size-control label="Rows Gap" base="rowsGap" control-id="social-icons-rows-gap" fallback="8px" :node="node" :editor="editor" :min="0" :max="80" />
			<div class="pb-form-group"><label class="pb-form-label">Border Type</label><select class="pb-select" v-model="node.settings.borderType"><option value="none">None</option><option value="solid">Solid</option><option value="double">Double</option><option value="dotted">Dotted</option><option value="dashed">Dashed</option></select></div><template v-if="node.settings.borderType!=='none'"><size-control label="Border Width" base="borderWidth" control-id="social-icons-border-width" fallback="1px" :node="node" :editor="editor" :min="0" :max="20" /><color-control label="Border Color" setting-key="borderColor" :node="node" /></template><size-control label="Border Radius" base="borderRadius" control-id="social-icons-border-radius" fallback="4px" :node="node" :editor="editor" :min="0" :max="100" /><div v-if="colorState==='hover'" class="pb-form-group"><label class="pb-form-label">Hover Animation</label><select class="pb-select" v-model="node.settings.hoverAnimation"><option value="none">None</option><option value="grow">Grow</option><option value="shrink">Shrink</option><option value="pulse">Pulse</option><option value="rotate">Rotate</option></select></div>
		</div></details></div>
		<div v-if="editor.settingsTab==='advanced'" class="pb-tab-content"><component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" :show-display-conditions="false" :show-cache-settings="false" :elementor-choices="true" @responsive-device="editor.setResponsiveDevice" @choose-media="editor.chooseMedia(node.settings,$event)" @clear-media="editor.clearMedia(node.settings,$event)" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" /></div>
	</div>
</template>

<script>
const ResponsiveMenu={props:['editor','id'],template:`<div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu(id)" :title="'Responsive: '+editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen(id)" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="id+'-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice(id,device.value)"><i :class="device.icon"></i><span>{{editor.deviceOptionLabel(device)}}</span></button></div></div>`};
const ResponsiveChoice={components:{ResponsiveMenu},props:['label','base','controlId','node','editor','options'],template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-btn-group pb-compact-choice"><button v-for="option in options" :key="base+'-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey(base)]===option.value}" :title="option.label" :aria-label="option.label" @click="editor.setResponsiveSetting(node.settings,base,option.value)"><i :class="option.icon"></i></button></div></div>`};
const SizeControl={components:{ResponsiveMenu},props:{label:String,base:String,controlId:String,fallback:String,node:Object,editor:Object,min:{type:Number,default:0},max:{type:Number,default:null}},template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback):max" :step="editor.sizeControlStep(node,base,fallback)" :value="editor.sizeControlDisplayValue(node,base,fallback)" @input="editor.onSizeControlInput(node,base,$event,{fallback,min,max})"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback):max" :value="editor.sizeControlDisplayValue(node,base,fallback)" @input="editor.onSizeControlInput(node,base,$event,{fallback,min,max})"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node,base,fallback)" @change="editor.setSizeControlUnit(node,base,$event.target.value,{fallback})"><option v-for="unit in editor.sizeControlUnits" :key="unit" :value="unit">{{unit}}</option></select></div></div></div>`};
const ColorControl={props:['label','settingKey','node','entry'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><input class="pb-input coloris pb-coloris-input" :value="(entry||node.settings)[settingKey]" @input="(entry||node.settings)[settingKey]=$event.target.value"></div>`};
export default {name:'GeneralSocialIconsSettings',props:{node:{type:Object,required:true},editor:{type:Object,required:true}},components:{ResponsiveMenu,ResponsiveChoice,SizeControl,ColorControl},data(){return{expandedId:'',colorState:'normal'}},computed:{alignmentOptions(){return[{value:'left',label:'Left',icon:'fas fa-align-left'},{value:'center',label:'Center',icon:'fas fa-align-center'},{value:'right',label:'Right',icon:'fas fa-align-right'}]}},methods:{iconLabel(entry){return entry.iconSource==='svg'?'Uploaded SVG':String(entry.iconName||'Selected icon').replace(/(^|[-_\s])(\w)/g,(_,space,letter)=>space+letter.toUpperCase())},toggle(id){this.expandedId=this.expandedId===id?'':id},add(){const id='social-'+Date.now();this.node.settings.items.push({id,iconSource:'library',iconStyle:'solid',iconName:'star',iconClass:'fas fa-star',iconSvg:'',linkUrl:'#',linkTarget:'',linkNofollow:false,linkCustomAttributes:[],colorMode:'official',primaryColor:'#405de6',secondaryColor:'#fff'});this.expandedId=id},duplicate(entry){const copy=JSON.parse(JSON.stringify(entry));copy.id='social-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);this.node.settings.items.push(copy);this.expandedId=copy.id},remove(id){if(this.node.settings.items.length<=1)return;const index=this.node.settings.items.findIndex((entry)=>entry.id===id);if(index>=0)this.node.settings.items.splice(index,1);if(this.expandedId===id)this.expandedId=''},clearIcon(entry){entry.iconSource='library';entry.iconClass='fas fa-star';entry.iconName='star';entry.iconStyle='solid';entry.iconSvg=''}}};
</script>

<style scoped>
.pb-widget-settings--general-new .pb-form-row{display:grid;gap:12px}.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:repeat(2,minmax(0,1fr))}.pb-widget-settings--general-new .pb-compact-choice{display:grid;grid-template-columns:repeat(auto-fit,minmax(34px,1fr));gap:7px}.pb-widget-settings--general-new .pb-compact-choice .pb-seg-btn{min-width:0;height:32px;padding:0 8px}.pb-widget-settings--general-new .pb-form-group{margin-bottom:14px}.pb-widget-settings--general-new .pb-form-row .pb-form-group{margin-bottom:0}.pb-social-repeater{overflow:hidden;border:1px solid #dce3ef;border-radius:6px;background:#fff}.pb-social-repeater__item{border-bottom:1px solid #e7ebf2}.pb-social-repeater__item:last-of-type{border-bottom:0}.pb-social-repeater__header{display:flex;align-items:center;gap:5px;min-width:0;min-height:40px;padding:6px 8px;cursor:pointer}.pb-social-repeater__header:focus-visible{outline:2px solid #8ea7ff;outline-offset:-2px}.pb-social-repeater__title{display:flex;align-items:center;gap:7px;min-width:0;overflow:hidden;flex:1;font-size:12px;font-weight:600}.pb-social-repeater__title span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pb-social-repeater__actions{display:flex;margin-left:auto}.pb-social-repeater__actions button{width:30px;height:30px;padding:0;border:0;background:transparent;color:#667085}.pb-social-repeater__actions button:last-child{color:#b42318}.pb-social-repeater__actions button:disabled{opacity:.35}.pb-social-repeater__disclosure{width:12px;flex:0 0 12px;font-size:10px;color:#667085;transition:transform .16s ease}.pb-social-repeater__disclosure.is-open{transform:rotate(180deg)}.pb-social-repeater__body{padding:10px;border-top:1px solid #e7ebf2;background:#f9fafb}.pb-social-add{display:flex;align-items:center;justify-content:center;gap:6px;width:100%;min-height:36px;padding:8px;border:0;background:#fff;color:#4f46e5;cursor:pointer}.pb-general-icon-picker{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:center}.pb-general-icon-picker__actions{display:grid;gap:5px}.pb-general-icon-picker__actions button{width:28px;height:28px;padding:0;border:1px solid #cdd8ea;border-radius:6px;background:#fff;color:#667085}.pb-general-icon-picker__actions button:hover{border-color:#aebdf7;background:#eef1ff;color:#5367ff}.pb-widget-settings--general-new .pb-collapsible-body{padding-top:13px}.pb-widget-settings--general-new .pb-input,.pb-widget-settings--general-new .pb-select{min-height:36px}@media(max-width:420px){.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:1fr}}
</style>

<style scoped>
.pb-social-repeater__header{gap:4px;min-height:34px;padding:4px 6px}
.pb-social-repeater__title{gap:6px;font-size:11px}
.pb-social-repeater__disclosure{flex:0 0 16px;width:16px;font-size:9px;transition:none}
.pb-social-repeater__actions{gap:2px}
.pb-social-repeater__actions button{display:grid;width:26px;height:26px;place-items:center;padding:0;border:1px solid #d7dfed;border-radius:5px;background:#fff}
.pb-social-add{min-height:34px;padding:7px;font-size:11px}
</style>
