<template>
	<ul class="pb-icon-list" :class="rootClasses()" :style="rootStyle()">
		<li v-for="item in items" :key="item.id" class="pb-icon-list__item" :style="itemStyle()">
			<a v-if="linkFor(item)" class="pb-icon-list__content" :href="linkFor(item)" :target="item.linkTarget || null" :rel="relFor(item) || null" v-bind="attributesFor(item)" @click.prevent>
				<span class="pb-icon-list__icon" :style="iconStyle()"><i :class="item.iconClass || 'fas fa-check'" aria-hidden="true"></i></span><span class="pb-icon-list__text" :style="textStyle()">{{ item.text }}</span>
			</a>
			<span v-else class="pb-icon-list__content"><span class="pb-icon-list__icon" :style="iconStyle()"><i :class="item.iconClass || 'fas fa-check'" aria-hidden="true"></i></span><span class="pb-icon-list__text" :style="textStyle()">{{ item.text }}</span></span>
		</li>
	</ul>
</template>
<script>
export default{
	name:'GeneralIconList',props:{item:{type:Object,required:true},responsiveDevice:{type:String,default:'desktop'}},
	computed:{settings(){return this.item.settings||{};},items(){return Array.isArray(this.settings.items)?this.settings.items:[];}},
	methods:{
		responsiveValue(base,fallback=''){const device=['tablet','mobile'].includes(this.responsiveDevice)?this.responsiveDevice:'desktop';const keys=device==='mobile'?[base+'Mobile',base+'Tablet',base]:device==='tablet'?[base+'Tablet',base]:[base];for(const key of keys){const value=this.settings[key];if(value!==''&&value!==null&&value!==undefined)return value;}return fallback;},
		cssSize(value,fallback='0px'){const raw=String(value??'').trim();return /^-?\d+(?:\.\d+)?(?:px|%|em|rem|vw|vh)?$/i.test(raw)?raw:fallback;},
		safeColor(value,fallback='inherit'){const raw=String(value||'').trim();return raw&&/^[#a-z0-9(),.%\s-]+$/i.test(raw)?raw:fallback;},
		safeUrl(value){const url=String(value||'').trim();return /^(https?:\/\/|\/|#|mailto:|tel:)/i.test(url)&&!url.startsWith('//')?url:'';},
		rootClasses(){return{'is-inline':this.settings.layout==='inline','has-divider':!!this.settings.divider,'pb-icon-list--apply-inline':this.settings.applyLinkOn==='inline'};},
		rootStyle(){const inline=this.settings.layout==='inline';const align={start:'flex-start',center:'center',end:'flex-end'}[this.responsiveValue('alignment','start')]||'flex-start';return{'--pb-icon-list-space-between':this.cssSize(this.responsiveValue('spaceBetween','15px'),'15px'),'--pb-icon-list-align':align,'--pb-icon-list-divider-style':['solid','double','dotted','dashed'].includes(this.settings.dividerStyle)?this.settings.dividerStyle:'solid','--pb-icon-list-divider-weight':this.cssSize(this.settings.dividerWeight,'1px'),'--pb-icon-list-divider-size':this.cssSize(inline?this.settings.dividerHeight:this.settings.dividerWidth,'100%'),'--pb-icon-list-divider-color':this.safeColor(this.settings.dividerColor,'#dddddd'),'--pb-icon-list-icon-size':this.cssSize(this.responsiveValue('iconSize','14px'),'14px'),'--pb-icon-list-icon-gap':this.cssSize(this.responsiveValue('iconGap','20px'),'20px'),'--pb-icon-list-icon-offset':this.cssSize(this.responsiveValue('iconVerticalOffset','0px'),'0px'),'--pb-icon-list-icon-color':this.safeColor(this.settings.iconColor,'inherit'),'--pb-icon-list-icon-hover':this.safeColor(this.settings.iconColorHover,this.safeColor(this.settings.iconColor,'inherit')),'--pb-icon-list-icon-transition':`${Math.max(0,Number(this.settings.iconTransitionDuration)||0)}s`,'--pb-icon-list-text-color':this.safeColor(this.settings.textColor,'inherit'),'--pb-icon-list-text-hover':this.safeColor(this.settings.textColorHover,this.safeColor(this.settings.textColor,'inherit')),'--pb-icon-list-text-transition':`${Math.max(0,Number(this.settings.textTransitionDuration)||0)}s`};},
		itemStyle(){const alignment={start:'flex-start',center:'center',end:'flex-end'}[this.responsiveValue('alignment','start')]||'flex-start';const vertical=this.responsiveValue('iconVerticalAlignment','');return{alignItems:vertical||'center',justifyContent:alignment};},
		iconStyle(){const horizontal={left:'flex-start',center:'center',right:'flex-end'}[this.responsiveValue('iconHorizontalAlignment','left')]||'flex-start';return{justifyContent:horizontal,alignSelf:this.responsiveValue('iconVerticalAlignment','')||'center',transform:`translateY(${this.cssSize(this.responsiveValue('iconVerticalOffset','0px'),'0px')})`};},
		textStyle(){return{fontFamily:String(this.settings.textFontFamily||'inherit'),fontSize:this.cssSize(this.responsiveValue('textFontSize','16px'),'16px'),fontWeight:String(this.settings.textFontWeight||'400'),lineHeight:this.cssSize(this.responsiveValue('textLineHeight','1.5em'),'1.5em'),letterSpacing:this.cssSize(this.responsiveValue('textLetterSpacing','0px'),'0px'),wordSpacing:this.cssSize(this.responsiveValue('textWordSpacing','0px'),'0px'),textTransform:this.settings.textTextTransform||'none',fontStyle:this.settings.textFontStyle||'normal',textDecoration:this.settings.textTextDecoration||'none',textShadow:String(this.settings.textTextShadow||'none')};},
		linkFor(item){return this.safeUrl(item?.linkUrl);},relFor(item){const rel=[];if(item?.linkNofollow)rel.push('nofollow');if(item?.linkTarget==='_blank')rel.push('noopener','noreferrer');return [...new Set(rel)].join(' ');},attributesFor(item){const out={};(Array.isArray(item?.linkCustomAttributes)?item.linkCustomAttributes:[]).forEach(attribute=>{const name=String(attribute?.name||attribute?.key||'').trim();if(/^(data-|aria-)[A-Za-z0-9_.:-]+$/.test(name))out[name]=String(attribute?.value||'');});return out;},
	},
};
</script>
<style scoped>
.pb-icon-list{display:flex;flex-direction:column;align-items:var(--pb-icon-list-align);gap:var(--pb-icon-list-space-between);width:100%;margin:0;padding:0;list-style:none}.pb-icon-list.is-inline{flex-flow:row wrap;justify-content:var(--pb-icon-list-align);align-items:center}.pb-icon-list__item{position:relative;display:flex;min-width:0;max-width:100%}.pb-icon-list:not(.is-inline) .pb-icon-list__item{width:100%}.pb-icon-list__content{display:flex;align-items:inherit;justify-content:var(--pb-icon-list-align);min-width:0;color:inherit;text-decoration:none}.pb-icon-list:not(.pb-icon-list--apply-inline) .pb-icon-list__content{width:100%}.pb-icon-list.pb-icon-list--apply-inline .pb-icon-list__content{width:auto}.pb-icon-list__icon{display:inline-flex;flex:0 0 var(--pb-icon-list-icon-size);width:var(--pb-icon-list-icon-size);padding-inline-end:var(--pb-icon-list-icon-gap);font-size:var(--pb-icon-list-icon-size);line-height:1;color:var(--pb-icon-list-icon-color);transition:color var(--pb-icon-list-icon-transition) ease}.pb-icon-list__text{min-width:0;color:var(--pb-icon-list-text-color);transition:color var(--pb-icon-list-text-transition) ease}.pb-icon-list__item:hover .pb-icon-list__icon{color:var(--pb-icon-list-icon-hover)}.pb-icon-list__item:hover .pb-icon-list__text{color:var(--pb-icon-list-text-hover)}.pb-icon-list.has-divider:not(.is-inline) .pb-icon-list__item:not(:last-child)::after{content:"";position:absolute;inset-inline-start:0;bottom:calc(var(--pb-icon-list-space-between) / -2);width:var(--pb-icon-list-divider-size);border-block-start:var(--pb-icon-list-divider-weight) var(--pb-icon-list-divider-style) var(--pb-icon-list-divider-color)}.pb-icon-list.has-divider.is-inline .pb-icon-list__item:not(:last-child)::after{content:"";position:absolute;top:50%;inset-inline-end:calc(var(--pb-icon-list-space-between) / -2);height:var(--pb-icon-list-divider-size);transform:translateY(-50%);border-inline-start:var(--pb-icon-list-divider-weight) var(--pb-icon-list-divider-style) var(--pb-icon-list-divider-color)}
</style>
