@php
    $settings = is_array($node['settings'] ?? null) ? $node['settings'] : [];
    $nodeId = trim((string) ($node['id'] ?? 'counter')) ?: 'counter';
    $safeLength = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?(?:px|pt|%|em|rem|vw|vh)?$/i', $raw) ? $raw : $fallback; };
    $safeColor = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return $raw !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $raw) ? $raw : $fallback; };
    $safeShadow = fn (mixed $value): string => $safeColor($value, 'none');
    $enum = fn (mixed $value, array $allowed, string $fallback): string => in_array(strtolower(trim((string) $value)), $allowed, true) ? strtolower(trim((string) $value)) : $fallback;
    $responsive = function (string $base, string $suffix = '', mixed $fallback = '') use ($settings): mixed { $keys = $suffix === 'Mobile' ? [$base.'Mobile', $base.'Tablet', $base] : ($suffix === 'Tablet' ? [$base.'Tablet', $base] : [$base]); foreach ($keys as $key) { if (($settings[$key] ?? '') !== '' && ($settings[$key] ?? null) !== null) return $settings[$key]; } return $fallback; };
    $fontStyle = function (string $prefix, string $suffix = '') use ($settings, $responsive, $safeLength, $safeColor, $safeShadow, $enum): string { $size = $prefix === 'number' ? '48px' : '16px'; $line = $prefix === 'number' ? '1.2em' : '1.4em'; $weight = preg_match('/^(?:normal|bold|[1-9]00)$/', trim((string) ($settings[$prefix.'FontWeight'] ?? '400'))) ? trim((string) ($settings[$prefix.'FontWeight'] ?? '400')) : '400'; return implode(';', ['font-family:'.(preg_match('/^[A-Za-z0-9 _,\'"-]+$/', trim((string) ($settings[$prefix.'FontFamily'] ?? 'inherit'))) ? trim((string) ($settings[$prefix.'FontFamily'] ?? 'inherit')) : 'inherit'), 'font-size:'.$safeLength($responsive($prefix.'FontSize', $suffix, $size), $size), 'font-weight:'.$weight, 'line-height:'.$safeLength($responsive($prefix.'LineHeight', $suffix, $line), $line), 'letter-spacing:'.$safeLength($responsive($prefix.'LetterSpacing', $suffix, '0px'), '0px'), 'word-spacing:'.$safeLength($responsive($prefix.'WordSpacing', $suffix, '0px'), '0px'), 'text-transform:'.$enum($settings[$prefix.'TextTransform'] ?? 'none', ['none','uppercase','lowercase','capitalize'], 'none'), 'font-style:'.$enum($settings[$prefix.'FontStyle'] ?? 'normal', ['normal','italic','oblique'], 'normal'), 'text-decoration:'.$enum($settings[$prefix.'TextDecoration'] ?? 'none', ['none','underline','overline','line-through'], 'none'), 'color:'.$safeColor($settings[$prefix.'Color'] ?? '', 'inherit'), 'text-shadow:'.$safeShadow($settings[$prefix.'TextShadow'] ?? 'none'), '-webkit-text-stroke-width:'.$safeLength($responsive($prefix.'TextStrokeWidth', $suffix, '0px'), '0px'), '-webkit-text-stroke-color:'.$safeColor($settings[$prefix.'TextStrokeColor'] ?? 'currentColor', 'currentColor')]); };
    $title = trim((string) ($settings['title'] ?? 'Counter'));
    $titleTag = $enum($settings['titleTag'] ?? 'div', ['h1','h2','h3','h4','h5','h6','div','span','p'], 'div');
    $position = $enum($settings['titlePosition'] ?? 'below', ['above','below','left','right'], 'below');
    $numberPosition = $enum($settings['numberPosition'] ?? 'center', ['left','center','right','stretch'], 'center');
    $titleAlign = $enum($settings['titleAlign'] ?? 'center', ['left','center','right'], 'center');
    $alignItems = $numberPosition === 'left' ? 'flex-start' : ($numberPosition === 'right' ? 'flex-end' : ($numberPosition === 'stretch' ? 'stretch' : 'center'));
    $direction = $position === 'right' ? 'row-reverse' : ($position === 'left' ? 'row' : 'column');
    $advanced = app(\App\Support\PageBuilderElementor\WidgetAdvancedStyleResolver::class)->resolve($settings, $nodeId, request());
    $number = is_numeric($settings['endingNumber'] ?? null) ? (float) $settings['endingNumber'] : 100;
    $start = is_numeric($settings['startingNumber'] ?? null) ? (float) $settings['startingNumber'] : 0;
    $separator = $settings['separator'] ?? 'default';
    $formatted = number_format($number, fmod($number, 1) === 0.0 ? 0 : 2, '.', ($separator === 'dot' ? '.' : ($separator === 'space' ? ' ' : ',')));
    if (!($settings['thousandSeparator'] ?? true)) $formatted = (string) (fmod($number, 1) === 0.0 ? (int) $number : $number);
    $rootStyle = implode(';', ['display:flex', 'flex-direction:'.$direction, 'align-items:'.$alignItems, 'text-align:'.$titleAlign, 'gap:'.$safeLength($responsive('titleGap', '', '8px'), '8px'), $numberPosition === 'stretch' ? 'width:100%' : '']);
    $rootClasses = array_values(array_unique(array_merge(['el-widget-counter','pb-counter','pb-counter--position-'.$position], $advanced['classes'])));
    $mediaRules = [];
    foreach (['Tablet'=>1024,'Mobile'=>767] as $suffix => $breakpoint) { $currentPosition = $enum($responsive('titlePosition', $suffix, 'below'), ['above','below','left','right'], 'below'); $currentNumberPosition = $enum($responsive('numberPosition', $suffix, 'center'), ['left','center','right','stretch'], 'center'); $currentAlign = $enum($responsive('titleAlign', $suffix, 'center'), ['left','center','right'], 'center'); $currentItems = $currentNumberPosition === 'left' ? 'flex-start' : ($currentNumberPosition === 'right' ? 'flex-end' : ($currentNumberPosition === 'stretch' ? 'stretch' : 'center')); $currentDirection = $currentPosition === 'right' ? 'row-reverse' : ($currentPosition === 'left' ? 'row' : 'column'); $mediaRules[] = '@media (max-width: '.$breakpoint.'px){#'.$advanced['id'].'{flex-direction:'.$currentDirection.';align-items:'.$currentItems.';text-align:'.$currentAlign.';gap:'.$safeLength($responsive('titleGap', $suffix, '8px'), '8px').'}#'.$advanced['id'].' .pb-counter__number{'. $fontStyle('number', $suffix) .'}#'.$advanced['id'].' .pb-counter__title{'. $fontStyle('title', $suffix) .'}}'; }
@endphp
<div id="{{ $advanced['id'] }}" class="{{ implode(' ', $rootClasses) }}" style="{{ $rootStyle }}" data-pb-counter data-pb-counter-start="{{ $start }}" data-pb-counter-end="{{ $number }}" data-pb-counter-duration="{{ max(0, min(10000, (int) ($settings['animationDuration'] ?? 2000))) }}" data-pb-counter-separator="{{ e($separator) }}" data-pb-counter-grouping="{{ !empty($settings['thousandSeparator']) ? '1' : '0' }}" data-entrance-delay="{{ $advanced['entranceDelay'] }}" data-entrance-duration="{{ $advanced['entranceDuration'] }}" @foreach($advanced['attributes'] as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>
    <div class="pb-counter__number" style="{{ $fontStyle('number') }}"><span class="pb-counter__prefix">{{ (string) ($settings['numberPrefix'] ?? '') }}</span><span class="pb-counter__value">{{ $formatted }}</span><span class="pb-counter__suffix">{{ (string) ($settings['numberSuffix'] ?? '') }}</span></div>
    @if($title !== '')<{{ $titleTag }} class="pb-counter__title" style="{{ $fontStyle('title') }}">{{ $title }}</{{ $titleTag }}>@endif
</div>
<style>{!! $advanced['css'] . implode('', $mediaRules) !!}</style>
<script>
(function(){
    const run = (root) => { if (!root || root.dataset.pbCounterReady === '1') return; root.dataset.pbCounterReady = '1'; const value = root.querySelector('.pb-counter__value'); if (!value) return; const start = Number(root.dataset.pbCounterStart || 0); const end = Number(root.dataset.pbCounterEnd || 0); const duration = Math.max(0, Number(root.dataset.pbCounterDuration || 0)); const grouping = root.dataset.pbCounterGrouping === '1'; const separator = root.dataset.pbCounterSeparator || 'default'; const format = (number) => { if (!grouping) return String(Math.round(number * 100) / 100); let output = number.toLocaleString('en-US', { maximumFractionDigits: 2 }); if (separator === 'dot') output = output.replace(/,/g, '.'); if (separator === 'space') output = output.replace(/,/g, ' '); return output; }; if (!duration || typeof requestAnimationFrame !== 'function') { value.textContent = format(end); return; } const started = performance.now(); const tick = (now) => { const progress = Math.min(1, (now - started) / duration); const eased = 1 - Math.pow(1 - progress, 3); value.textContent = format(start + ((end - start) * eased)); if (progress < 1) requestAnimationFrame(tick); }; requestAnimationFrame(tick); };
    const boot = () => document.querySelectorAll('[data-pb-counter]').forEach(run); if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once:true }); else boot();
})();
</script>
