@php
    $settings = is_array($node['settings'] ?? null) ? $node['settings'] : [];
    $nodeId = trim((string) ($node['id'] ?? 'text-path')) ?: 'text-path';
    $safeLength = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?(?:px|pt|%|em|rem|vw|vh)?$/i', $raw) ? $raw : $fallback; };
    $safeAngle = function (mixed $value): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?deg$/i', $raw) ? $raw : '0deg'; };
    $safeColor = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return ($raw === 'transparent' || ($raw !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $raw))) ? $raw : $fallback; };
    $safeUrl = function (mixed $value): string { $url = trim((string) $value); return $url !== '' && !str_starts_with($url, '//') && preg_match('/^(?:https?:|mailto:|tel:|\/|#)/i', $url) ? $url : ''; };
    $responsive = function (string $base, string $suffix = '', mixed $fallback = '') use ($settings): mixed { $keys = $suffix === 'Mobile' ? [$base.'Mobile', $base.'Tablet', $base] : ($suffix === 'Tablet' ? [$base.'Tablet', $base] : [$base]); foreach ($keys as $key) { if (($settings[$key] ?? '') !== '' && ($settings[$key] ?? null) !== null) return $settings[$key]; } return $fallback; };
    $paths = [
        'wave'=>['viewBox'=>'0 0 250 42.4994','d'=>'M0,42.2494C62.5,42.2494,62.5.25,125,.25s62.5,41.9994,125,41.9994'],
        'arc'=>['viewBox'=>'0 0 250.5 125.25','d'=>'M.25,125.25a125,125,0,0,1,250,0'],
        'circle'=>['viewBox'=>'0 0 250.5 250.5','d'=>'M.25,125.25a125,125,0,1,1,125,125,125,125,0,0,1-125-125'],
        'line'=>['viewBox'=>'0 0 250 22','d'=>'M 0 27 l 250 -22'],
        'oval'=>['viewBox'=>'0 0 250.5 125.75','d'=>'M.25,62.875C.25,28.2882,56.2144.25,125.25.25s125,28.0382,125,62.625-55.9644,62.625-125,62.625S.25,97.4619.25,62.875'],
        'spiral'=>['viewBox'=>'0 0 250.4348 239.4454','d'=>'M.1848,49.0219a149.3489,149.3489,0,0,1,210.9824-9.8266,119.479,119.479,0,0,1,7.8613,168.786A95.5831,95.5831,0,0,1,84,214.27a76.4666,76.4666,0,0,1-5.0312-108.023'],
    ];
    $pathType = in_array($settings['pathType'] ?? 'wave', ['wave','arc','circle','line','oval','spiral','custom'], true) ? $settings['pathType'] : 'wave';
    $pathDefinition = $paths[$pathType] ?? $paths['wave'];
    $pathData = $pathDefinition['d'];
    $viewBox = $pathDefinition['viewBox'];
    $customSvgUrl = $pathType === 'custom' ? $safeUrl($settings['customSvgUrl'] ?? '') : '';
    $alignment = in_array($responsive('alignment', '', 'left'), ['left','center','right'], true) ? $responsive('alignment', '', 'left') : 'left';
    $justify = fn (string $value): string => $value === 'center' ? 'center' : ($value === 'right' ? 'flex-end' : 'flex-start');
    $direction = in_array($settings['textDirection'] ?? 'default', ['rtl','ltr'], true) ? $settings['textDirection'] : 'inherit';
    $startingPoint = max(0, min(100, (float) ($settings['startingPoint'] ?? 0)));
    $requestedHoverAnimation = (string) ($settings['hoverAnimation'] ?? 'none');
    $hoverAnimation = in_array($requestedHoverAnimation, ['none','grow','shrink','pulse','pulse-grow','pulse-shrink','push','pop','bounce-in','bounce-out','rotate','grow-rotate','float','sink','bob','hang','skew','skew-forward','skew-backward','wobble-vertical','wobble-horizontal','wobble-to-bottom-right','wobble-to-top-right','wobble-top','wobble-bottom','wobble-skew','buzz','buzz-out'], true) ? $requestedHoverAnimation : 'none';
    $text = (string) ($settings['text'] ?? 'Add Your Curvy Text Here');
    $href = $safeUrl($settings['linkUrl'] ?? '');
    $target = ($settings['linkTarget'] ?? '') === '_blank' ? '_blank' : '';
    $rel = array_values(array_unique(array_merge($target === '_blank' ? ['noopener','noreferrer'] : [], !empty($settings['linkNofollow']) ? ['nofollow'] : [])));
    $linkAttributes = []; foreach (($settings['linkCustomAttributes'] ?? []) as $attribute) { if (!is_array($attribute)) continue; $name = strtolower(trim((string) ($attribute['key'] ?? $attribute['name'] ?? ''))); if (preg_match('/^(?:aria-[a-z0-9_-]+|data-[a-z0-9_-]+|title|download|hreflang)$/', $name)) $linkAttributes[$name] = (string) ($attribute['value'] ?? ''); }
    $advanced = app(\App\Support\PageBuilderElementor\WidgetAdvancedStyleResolver::class)->resolve($settings, $nodeId, request());
    $rootClasses = array_values(array_unique(array_merge(['el-widget-text-path','pb-text-path'], $hoverAnimation !== 'none' ? ['pb-text-path--hover-'.$hoverAnimation] : [], $advanced['classes'])));
    $pathId = 'pb-text-path-path-'.preg_replace('/[^a-zA-Z0-9_-]/', '', $nodeId);
    $textFontWeight = (string) ($settings['textFontWeight'] ?? '400');
    $textFontStyle = in_array($settings['textFontStyle'] ?? 'normal', ['normal','italic','oblique'], true) ? $settings['textFontStyle'] : 'normal';
    $textTransform = in_array($settings['textTextTransform'] ?? 'none', ['none','uppercase','lowercase','capitalize'], true) ? $settings['textTextTransform'] : 'none';
    $textDecoration = in_array($settings['textTextDecoration'] ?? 'none', ['none','underline','overline','line-through'], true) ? $settings['textTextDecoration'] : 'none';
    $rootStyle = implode(';', ['justify-content:'.$justify($alignment),'direction:'.$direction,'--pb-text-path-size:'.$safeLength($responsive('size', '', '500px'), '500px'),'--pb-text-path-rotate:'.$safeAngle($responsive('rotate', '', '0deg')),'--pb-text-path-color:'.$safeColor($settings['textColor'] ?? '', '#101828'),'--pb-text-path-color-hover:'.$safeColor($settings['textColorHover'] ?? '', '#101828'),'--pb-text-path-word-spacing:'.$safeLength($responsive('wordSpacing', '', '0px'), '0px'),'--pb-text-path-stroke-width:'.$safeLength($responsive('textStrokeWidth', '', '0px'), '0px'),'--pb-text-path-stroke-color:'.$safeColor($settings['textStrokeColor'] ?? '', 'currentColor'),'--pb-text-path-duration:'.max(0, min(10, (float) ($settings['transitionDuration'] ?? .3))).'s','--pb-text-font-family:'.e((string) ($settings['textFontFamily'] ?? 'inherit')),'--pb-text-font-size:'.$safeLength($responsive('textFontSize', '', '20px'), '20px'),'--pb-text-font-weight:'.(preg_match('/^(?:normal|bold|[1-9]00)$/', $textFontWeight) ? $textFontWeight : '400'),'--pb-text-font-style:'.$textFontStyle,'--pb-text-transform:'.$textTransform,'--pb-text-decoration:'.$textDecoration,'--pb-text-line-height:'.$safeLength($responsive('textLineHeight', '', '1.2em'), '1.2em'),'--pb-text-letter-spacing:'.$safeLength($responsive('textLetterSpacing', '', '0px'), '0px')]);
    $visiblePathStyle = implode(';', ['fill:'.$safeColor($settings['pathColor'] ?? '', 'transparent'),'stroke:'.$safeColor($settings['pathStrokeColor'] ?? '', '#f04438'),'stroke-width:'.$safeLength($responsive('pathStrokeWidth', '', '1px'), '1px'),'--pb-path-fill-hover:'.$safeColor($settings['pathColorHover'] ?? '', 'transparent'),'--pb-path-stroke-hover:'.$safeColor($settings['pathStrokeColorHover'] ?? '', '#f04438'),'--pb-path-width-hover:'.$safeLength($responsive('pathStrokeWidthHover', '', '1px'), '1px'),'--pb-path-duration:'.max(0, min(10, (float) ($settings['pathTransitionDuration'] ?? .3))).'s']);
    $mediaRules = [];
    foreach (['Tablet'=>1024,'Mobile'=>767] as $suffix=>$breakpoint) { $align = in_array($responsive('alignment', $suffix, 'left'), ['left','center','right'], true) ? $responsive('alignment', $suffix, 'left') : 'left'; $mediaRules[] = '@media(max-width:'.$breakpoint.'px){#'.$advanced['id'].'{justify-content:'.$justify($align).';--pb-text-path-size:'.$safeLength($responsive('size', $suffix, '500px'), '500px').';--pb-text-path-rotate:'.$safeAngle($responsive('rotate', $suffix, '0deg')).';--pb-text-path-word-spacing:'.$safeLength($responsive('wordSpacing', $suffix, '0px'), '0px').';--pb-text-path-stroke-width:'.$safeLength($responsive('textStrokeWidth', $suffix, '0px'), '0px').';--pb-text-font-size:'.$safeLength($responsive('textFontSize', $suffix, '20px'), '20px').';--pb-text-line-height:'.$safeLength($responsive('textLineHeight', $suffix, '1.2em'), '1.2em').';--pb-text-letter-spacing:'.$safeLength($responsive('textLetterSpacing', $suffix, '0px'), '0px').'}}'; }
@endphp
<div id="{{ $advanced['id'] }}" class="{{ implode(' ', $rootClasses) }}" style="{{ $rootStyle }}" @if($customSvgUrl !== '') data-custom-svg-url="{{ e($customSvgUrl) }}" @endif data-entrance-delay="{{ $advanced['entranceDelay'] }}" data-entrance-duration="{{ $advanced['entranceDuration'] }}" @foreach($advanced['attributes'] as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>
    @if($href !== '')<a data-text-path-link href="{{ e($href) }}" @if($target !== '') target="{{ $target }}" @endif @if($rel) rel="{{ implode(' ', $rel) }}" @endif @foreach($linkAttributes as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>@endif
    <svg data-text-path-svg viewBox="{{ $viewBox }}" role="img" aria-label="{{ e($text) }}"><defs><path id="{{ $pathId }}" data-text-path-definition d="{{ $pathData }}"></path></defs>@if(!empty($settings['showPath']))<use data-text-path-visible href="#{{ $pathId }}" style="{{ $visiblePathStyle }}"></use>@endif<text data-text-path-text><textPath href="#{{ $pathId }}" startOffset="{{ $startingPoint }}%">{{ $text }}</textPath></text></svg>
    @if($href !== '')</a>@endif
</div>
<style>
#{{ $advanced['id'] }}{display:flex;width:100%;min-width:0}#{{ $advanced['id'] }} [data-text-path-link]{display:block;width:min(100%,var(--pb-text-path-size));max-width:100%;color:inherit;text-decoration:none;transform:rotate(var(--pb-text-path-rotate));transform-origin:center;transition:transform var(--pb-text-path-duration) ease}#{{ $advanced['id'] }}>[data-text-path-svg]{display:block;width:min(100%,var(--pb-text-path-size));max-width:100%;height:auto;overflow:visible;transform:rotate(var(--pb-text-path-rotate));transform-origin:center;transition:transform var(--pb-text-path-duration) ease}#{{ $advanced['id'] }} [data-text-path-link]>[data-text-path-svg]{width:100%;transform:none}#{{ $advanced['id'] }} [data-text-path-text]{fill:var(--pb-text-path-color);font-family:var(--pb-text-font-family);font-size:var(--pb-text-font-size);font-weight:var(--pb-text-font-weight);font-style:var(--pb-text-font-style);text-transform:var(--pb-text-transform);text-decoration:var(--pb-text-decoration);line-height:var(--pb-text-line-height);letter-spacing:var(--pb-text-letter-spacing);word-spacing:var(--pb-text-path-word-spacing);stroke:var(--pb-text-path-stroke-color);stroke-width:var(--pb-text-path-stroke-width);paint-order:stroke fill;transition:fill var(--pb-text-path-duration) ease}#{{ $advanced['id'] }}:hover [data-text-path-text]{fill:var(--pb-text-path-color-hover)}#{{ $advanced['id'] }} [data-text-path-visible]{transition:fill var(--pb-path-duration) ease,stroke var(--pb-path-duration) ease,stroke-width var(--pb-path-duration) ease}#{{ $advanced['id'] }}:hover [data-text-path-visible]{fill:var(--pb-path-fill-hover)!important;stroke:var(--pb-path-stroke-hover)!important;stroke-width:var(--pb-path-width-hover)!important}.pb-text-path--hover-grow:hover [data-text-path-link],.pb-text-path--hover-grow:hover>[data-text-path-svg],.pb-text-path--hover-pulse-grow:hover [data-text-path-link],.pb-text-path--hover-pulse-grow:hover>[data-text-path-svg]{transform:rotate(var(--pb-text-path-rotate)) scale(1.08)}.pb-text-path--hover-shrink:hover [data-text-path-link],.pb-text-path--hover-shrink:hover>[data-text-path-svg]{transform:rotate(var(--pb-text-path-rotate)) scale(.94)}.pb-text-path--hover-float:hover [data-text-path-link],.pb-text-path--hover-float:hover>[data-text-path-svg]{transform:rotate(var(--pb-text-path-rotate)) translateY(-6px)}.pb-text-path--hover-sink:hover [data-text-path-link],.pb-text-path--hover-sink:hover>[data-text-path-svg]{transform:rotate(var(--pb-text-path-rotate)) translateY(6px)}{!! implode('', $mediaRules) !!}@media(prefers-reduced-motion:reduce){#{{ $advanced['id'] }} [data-text-path-link],#{{ $advanced['id'] }}>[data-text-path-svg]{transition:none!important;animation:none!important}}{!! $advanced['css'] !!}
</style>
@if($customSvgUrl !== '')
<script>
(function(){const root=document.getElementById(@json($advanced['id']));if(!root)return;const url=root.dataset.customSvgUrl||'';if(!url)return;fetch(url,{credentials:'same-origin'}).then(response=>{if(!response.ok)throw new Error(String(response.status));return response.text()}).then(source=>{const doc=new DOMParser().parseFromString(source,'image/svg+xml');const sourceSvg=doc.querySelector('svg');const path=sourceSvg?.querySelector('path[d]');const data=String(path?.getAttribute('d')||'').trim();const box=String(sourceSvg?.getAttribute('viewBox')||'').trim();if(/^[Mm][0-9eE+.,\-\sA-Za-z]+$/.test(data)){const target=root.querySelector('[data-text-path-definition]');const targetSvg=root.querySelector('[data-text-path-svg]');if(target)target.setAttribute('d',data);if(targetSvg&&/^-?\d+(?:\.\d+)?(?:\s+-?\d+(?:\.\d+)?){3}$/.test(box))targetSvg.setAttribute('viewBox',box)}}).catch(()=>{});})();
</script>
@endif
