<template>
	<div class="pb-widget-settings pb-widget-settings--general-new pb-widget-settings--counter">
		<div class="pb-tab-nav"><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button></div>
		<div v-show="editor.settingsTab==='content'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Counter</summary><div class="pb-collapsible-body">
				<div class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Starting Number</label><input class="pb-input" type="number" v-model.number="node.settings.startingNumber"></div><div class="pb-form-group"><label class="pb-form-label">Ending Number</label><input class="pb-input" type="number" v-model.number="node.settings.endingNumber"></div></div>
				<div class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Number Prefix</label><input class="pb-input" v-model="node.settings.numberPrefix" placeholder="$"></div><div class="pb-form-group"><label class="pb-form-label">Number Suffix</label><input class="pb-input" v-model="node.settings.numberSuffix" placeholder="+"></div></div>
				<div class="pb-form-group"><label class="pb-form-label">Animation Duration (ms)</label><input class="pb-input" type="number" min="0" max="10000" step="100" v-model.number="node.settings.animationDuration"></div>
				<div class="pb-form-group pb-toggle-label-row"><label class="pb-form-label mb-0">Thousand Separator</label><div class="pb-toggle-switch-wrap"><div class="pb-toggle-wrap"><input :id="'counter-separator-' + node.id" type="checkbox" class="pb-toggle" v-model="node.settings.thousandSeparator"><label :for="'counter-separator-' + node.id"></label></div><span class="pb-toggle-state">{{node.settings.thousandSeparator?'On':'Off'}}</span></div></div>
				<div v-if="node.settings.thousandSeparator" class="pb-form-group"><label class="pb-form-label">Separator</label><select class="pb-select" v-model="node.settings.separator"><option value="default">Default</option><option value="dot">Dot</option><option value="space">Space</option></select></div>
				<div class="pb-form-group"><label class="pb-form-label">Title</label><input class="pb-input" v-model="node.settings.title" placeholder="Counter"></div>
				<div class="pb-form-group"><label class="pb-form-label">Title HTML Tag</label><select class="pb-select" v-model="node.settings.titleTag"><option v-for="tag in titleTags" :key="tag" :value="tag">{{tag.toUpperCase()}}</option></select></div>
			</div></details>
		</div>
		<div v-show="editor.settingsTab==='style'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Layout</summary><div class="pb-collapsible-body">
				<responsive-choice label="Title Position" base="titlePosition" control-id="counter-title-position" :node="node" :editor="editor" :options="titlePositionOptions" />
				<responsive-choice label="Title Alignment" base="titleAlign" control-id="counter-title-align" :node="node" :editor="editor" :options="alignmentOptions" />
				<size-control label="Title Gap" base="titleGap" control-id="counter-title-gap" fallback="8px" :node="node" :editor="editor" :min="0" :max="80" />
				<responsive-choice label="Number Position" base="numberPosition" control-id="counter-number-position" :node="node" :editor="editor" :options="numberPositionOptions" />
			</div></details>
			<details class="pb-collapsible" open><summary>Number</summary><div class="pb-collapsible-body">
				<color-control label="Text Color" setting-key="numberColor" :node="node" />
				<component :is="editor.typographyControl" prefix="number" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'48px',FontWeight:'700',LineHeight:'1.2em'}" @responsive-device="editor.setResponsiveDevice" />
				<component :is="editor.textStrokeControl" :settings="node.settings" :responsive-device="editor.responsiveDevice" width-key="numberTextStrokeWidth" color-key="numberTextStrokeColor" control-id="counter-number-stroke" :open="activeEffect==='counter-number-stroke'" @request-open="activeEffect=$event" @responsive-device="editor.setResponsiveDevice" />
				<component :is="editor.textShadowControl" aria-label="Text Shadow" :model-value="node.settings.numberTextShadow" control-id="counter-number-shadow" :open="activeEffect==='counter-number-shadow'" @request-open="activeEffect=$event" @update:modelValue="node.settings.numberTextShadow=$event" />
			</div></details>
			<details class="pb-collapsible"><summary>Title</summary><div class="pb-collapsible-body">
				<color-control label="Text Color" setting-key="titleColor" :node="node" />
				<component :is="editor.typographyControl" prefix="title" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'16px',FontWeight:'500',LineHeight:'1.4em'}" @responsive-device="editor.setResponsiveDevice" />
				<component :is="editor.textStrokeControl" :settings="node.settings" :responsive-device="editor.responsiveDevice" width-key="titleTextStrokeWidth" color-key="titleTextStrokeColor" control-id="counter-title-stroke" :open="activeEffect==='counter-title-stroke'" @request-open="activeEffect=$event" @responsive-device="editor.setResponsiveDevice" />
				<component :is="editor.textShadowControl" aria-label="Text Shadow" :model-value="node.settings.titleTextShadow" control-id="counter-title-shadow" :open="activeEffect==='counter-title-shadow'" @request-open="activeEffect=$event" @update:modelValue="node.settings.titleTextShadow=$event" />
			</div></details>
		</div>
		<div v-show="editor.settingsTab==='advanced'" class="pb-tab-content"><component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" :show-display-conditions="false" :show-cache-settings="false" :elementor-choices="true" @responsive-device="editor.setResponsiveDevice" @choose-media="editor.chooseMedia(node.settings,$event)" @clear-media="editor.clearMedia(node.settings,$event)" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" /></div>
	</div>
</template>

<script>
const ResponsiveMenu={props:['editor','id'],template:`<div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu(id)" :title="'Responsive: '+editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen(id)" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="id+'-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice(id,device.value)"><i :class="device.icon"></i><span>{{editor.deviceOptionLabel(device)}}</span></button></div></div>`};
const ResponsiveChoice={components:{ResponsiveMenu},props:['label','base','controlId','node','editor','options'],template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-btn-group pb-compact-choice"><button v-for="option in options" :key="base+'-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey(base)]===option.value}" :title="option.label" :aria-label="option.label" @click="editor.setResponsiveSetting(node.settings,base,option.value)"><i :class="option.icon"></i></button></div></div>`};
const SizeControl={components:{ResponsiveMenu},props:{label:String,base:String,controlId:String,fallback:String,node:Object,editor:Object,min:{type:Number,default:0},max:{type:Number,default:80}},template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max" :step="editor.sizeControlStep(node,base,fallback)" :value="editor.sizeControlDisplayValue(node,base,fallback)" @input="editor.onSizeControlInput(node,base,$event,{fallback,min,max})"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max" :value="editor.sizeControlDisplayValue(node,base,fallback)" @input="editor.onSizeControlInput(node,base,$event,{fallback,min,max})"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node,base,fallback)" @change="editor.setSizeControlUnit(node,base,$event.target.value,{fallback})"><option v-for="unit in editor.sizeControlUnits" :key="unit" :value="unit">{{unit}}</option></select></div></div></div>`};
const ColorControl={props:['label','settingKey','node'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><input class="pb-input coloris pb-coloris-input" v-model="node.settings[settingKey]"></div>`};
export default { name:'GeneralCounterSettings', props:{node:{type:Object,required:true},editor:{type:Object,required:true}}, components:{ResponsiveMenu,ResponsiveChoice,SizeControl,ColorControl}, data(){return{activeEffect:'',titleTags:['h1','h2','h3','h4','h5','h6','div','span','p']}}, computed:{titlePositionOptions(){return[{value:'above',label:'Above',icon:'fas fa-arrow-up'},{value:'below',label:'Below',icon:'fas fa-arrow-down'},{value:'left',label:'Left',icon:'fas fa-arrow-left'},{value:'right',label:'Right',icon:'fas fa-arrow-right'}]},alignmentOptions(){return[{value:'left',label:'Left',icon:'fas fa-align-left'},{value:'center',label:'Center',icon:'fas fa-align-center'},{value:'right',label:'Right',icon:'fas fa-align-right'}]},numberPositionOptions(){return[{value:'left',label:'Left',icon:'fas fa-align-left'},{value:'center',label:'Center',icon:'fas fa-align-center'},{value:'right',label:'Right',icon:'fas fa-align-right'},{value:'stretch',label:'Stretch',icon:'fas fa-arrows-alt-h'}]}}};
</script>

<style scoped>
.pb-widget-settings--general-new .pb-form-row{display:grid;gap:12px}.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:repeat(2,minmax(0,1fr))}.pb-widget-settings--general-new .pb-compact-choice{display:grid;grid-template-columns:repeat(auto-fit,minmax(34px,1fr));gap:7px}.pb-widget-settings--general-new .pb-compact-choice .pb-seg-btn{min-width:0;height:32px;padding:0 8px}.pb-widget-settings--general-new .pb-form-group{margin-bottom:14px}.pb-widget-settings--general-new .pb-form-row .pb-form-group{margin-bottom:0}.pb-widget-settings--general-new .pb-collapsible-body{padding-top:13px}.pb-widget-settings--general-new .pb-form-label{line-height:1.25}.pb-widget-settings--general-new .pb-input,.pb-widget-settings--general-new .pb-select{min-height:36px}@media(max-width:420px){.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:1fr}}
</style>
