<template>
	<div class="pb-widget-settings pb-widget-settings--general-new pb-widget-settings--testimonial">
		<div class="pb-tab-nav"><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button></div>
		<div v-if="editor.settingsTab==='content'" class="pb-tab-content"><details class="pb-collapsible" open><summary>Testimonial</summary><div class="pb-collapsible-body">
			<div class="pb-form-group"><label class="pb-form-label">Content</label><textarea class="pb-textarea" rows="4" v-model="node.settings.content" placeholder="Write a testimonial"></textarea></div>
			<div class="pb-form-group"><label class="pb-form-label">Image</label><div class="pb-bg-media-field pb-widget-settings__media-field" :class="{'has-image':!!node.settings.imageUrl}"><div class="pb-bg-media-preview" :style="node.settings.imageUrl?{backgroundImage:'url('+node.settings.imageUrl+')'}:{}"><button type="button" class="pb-bg-media-center-btn" :title="node.settings.imageUrl?'Change Image':'Choose Image'" @click="editor.chooseMedia(node.settings,'imageUrl')"><i :class="node.settings.imageUrl?'fas fa-pen':'fas fa-plus'"></i></button></div><div class="pb-bg-media-actions"><button type="button" class="pb-bg-media-choose" @click="editor.chooseMedia(node.settings,'imageUrl')">{{node.settings.imageUrl?'Change':'Choose'}} Image</button><button type="button" class="pb-bg-media-remove" :disabled="!node.settings.imageUrl" title="Remove Image" aria-label="Remove Image" @click="editor.clearMedia(node.settings,'imageUrl')"><i class="fas fa-trash-alt"></i></button></div></div></div>
			<div class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Image Resolution</label><select class="pb-select" v-model="node.settings.imageResolution"><option v-for="resolution in resolutions" :key="resolution.value" :value="resolution.value">{{resolution.label}}</option></select></div><div class="pb-form-group"><label class="pb-form-label">Image Alt</label><input class="pb-input" v-model="node.settings.imageAlt" placeholder="Portrait"></div></div>
			<div v-if="node.settings.imageResolution==='custom'" class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Custom Width</label><input class="pb-input" type="number" min="1" max="4096" v-model.number="node.settings.customImageWidth"></div><div class="pb-form-group"><label class="pb-form-label">Custom Height</label><input class="pb-input" type="number" min="1" max="4096" v-model.number="node.settings.customImageHeight"></div></div>
			<div class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Name</label><input class="pb-input" v-model="node.settings.name" placeholder="John Doe"></div><div class="pb-form-group"><label class="pb-form-label">Title</label><input class="pb-input" v-model="node.settings.title" placeholder="Designer"></div></div>
			<div class="pb-form-group"><label class="pb-form-label">Link</label><component :is="editor.linkControl" :url="node.settings.linkUrl" :target="node.settings.linkTarget" :nofollow="node.settings.linkNofollow" :custom-attributes="node.settings.linkCustomAttributes" @update:url="node.settings.linkUrl=$event" @update:target="node.settings.linkTarget=$event" @update:nofollow="node.settings.linkNofollow=$event" @update:customAttributes="node.settings.linkCustomAttributes=$event" /></div>
			<responsive-choice label="Image Position" base="imagePosition" control-id="testimonial-image-position" :node="node" :editor="editor" :options="positionOptions" /><responsive-choice label="Alignment" base="alignment" control-id="testimonial-alignment" :node="node" :editor="editor" :options="alignmentOptions" />
		</div></details></div>
		<div v-if="editor.settingsTab==='style'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Content</summary><div class="pb-collapsible-body"><color-control label="Text Color" setting-key="contentColor" :node="node" /><component :is="editor.typographyControl" prefix="content" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'16px',FontWeight:'400',LineHeight:'1.5em'}" @responsive-device="editor.setResponsiveDevice" /><component :is="editor.textShadowControl" aria-label="Text Shadow" :model-value="node.settings.contentTextShadow" control-id="testimonial-content-shadow" :open="activeEffect==='testimonial-content-shadow'" @request-open="activeEffect=$event" @update:modelValue="node.settings.contentTextShadow=$event" /></div></details>
			<details class="pb-collapsible"><summary>Image</summary><div class="pb-collapsible-body"><size-control label="Size" base="imageSize" control-id="testimonial-image-size" fallback="80px" :node="node" :editor="editor" :min="20" :max="400" /><div class="pb-form-group"><label class="pb-form-label">Border Type</label><select class="pb-select" v-model="node.settings.imageBorderType"><option value="none">None</option><option value="solid">Solid</option><option value="double">Double</option><option value="dotted">Dotted</option><option value="dashed">Dashed</option><option value="groove">Groove</option></select></div><template v-if="node.settings.imageBorderType!=='none'"><size-control label="Border Width" base="imageBorderWidth" control-id="testimonial-image-border-width" fallback="1px" :node="node" :editor="editor" :min="0" :max="20" /><color-control label="Border Color" setting-key="imageBorderColor" :node="node" /></template><size-control label="Border Radius" base="imageBorderRadius" control-id="testimonial-image-border-radius" fallback="50%" :node="node" :editor="editor" :min="0" :max="100" /></div></details>
			<details class="pb-collapsible"><summary>Name</summary><div class="pb-collapsible-body"><color-control label="Text Color" setting-key="nameColor" :node="node" /><component :is="editor.typographyControl" prefix="name" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'18px',FontWeight:'600',LineHeight:'1.3em'}" @responsive-device="editor.setResponsiveDevice" /><component :is="editor.textShadowControl" aria-label="Text Shadow" :model-value="node.settings.nameTextShadow" control-id="testimonial-name-shadow" :open="activeEffect==='testimonial-name-shadow'" @request-open="activeEffect=$event" @update:modelValue="node.settings.nameTextShadow=$event" /></div></details>
			<details class="pb-collapsible"><summary>Title</summary><div class="pb-collapsible-body"><color-control label="Text Color" setting-key="titleColor" :node="node" /><component :is="editor.typographyControl" prefix="title" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'14px',FontWeight:'400',LineHeight:'1.4em'}" @responsive-device="editor.setResponsiveDevice" /><component :is="editor.textShadowControl" aria-label="Text Shadow" :model-value="node.settings.titleTextShadow" control-id="testimonial-title-shadow" :open="activeEffect==='testimonial-title-shadow'" @request-open="activeEffect=$event" @update:modelValue="node.settings.titleTextShadow=$event" /></div></details>
		</div>
		<div v-if="editor.settingsTab==='advanced'" class="pb-tab-content"><component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" :show-display-conditions="false" :show-cache-settings="false" :elementor-choices="true" @responsive-device="editor.setResponsiveDevice" @choose-media="editor.chooseMedia(node.settings,$event)" @clear-media="editor.clearMedia(node.settings,$event)" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" /></div>
	</div>
</template>

<script>
const ResponsiveMenu={props:['editor','id'],template:`<div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu(id)" :title="'Responsive: '+editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen(id)" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="id+'-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice(id,device.value)"><i :class="device.icon"></i><span>{{editor.deviceOptionLabel(device)}}</span></button></div></div>`};
const ResponsiveChoice={components:{ResponsiveMenu},props:['label','base','controlId','node','editor','options'],template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-btn-group pb-compact-choice"><button v-for="option in options" :key="base+'-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey(base)]===option.value}" :title="option.label" :aria-label="option.label" @click="editor.setResponsiveSetting(node.settings,base,option.value)"><i :class="option.icon"></i></button></div></div>`};
const SizeControl={components:{ResponsiveMenu},props:{label:String,base:String,controlId:String,fallback:String,node:Object,editor:Object,min:{type:Number,default:0},max:{type:Number,default:null}},template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback):max" :step="editor.sizeControlStep(node,base,fallback)" :value="editor.sizeControlDisplayValue(node,base,fallback)" @input="editor.onSizeControlInput(node,base,$event,{fallback,min,max})"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback):max" :value="editor.sizeControlDisplayValue(node,base,fallback)" @input="editor.onSizeControlInput(node,base,$event,{fallback,min,max})"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node,base,fallback)" @change="editor.setSizeControlUnit(node,base,$event.target.value,{fallback})"><option v-for="unit in editor.sizeControlUnits" :key="unit" :value="unit">{{unit}}</option></select></div></div></div>`};
const ColorControl={props:['label','settingKey','node'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><input class="pb-input coloris pb-coloris-input" v-model="node.settings[settingKey]"></div>`};
export default {name:'GeneralTestimonialSettings',props:{node:{type:Object,required:true},editor:{type:Object,required:true}},components:{ResponsiveMenu,ResponsiveChoice,SizeControl,ColorControl},data(){return{activeEffect:'',resolutions:[{value:'thumbnail',label:'Thumbnail'},{value:'medium',label:'Medium'},{value:'medium_large',label:'Medium Large'},{value:'large',label:'Large'},{value:'full',label:'Full'},{value:'custom',label:'Custom'}]}},computed:{positionOptions(){return[{value:'top',label:'Above',icon:'fas fa-arrow-up'},{value:'left',label:'Left',icon:'fas fa-arrow-left'},{value:'right',label:'Right',icon:'fas fa-arrow-right'}]},alignmentOptions(){return[{value:'left',label:'Left',icon:'fas fa-align-left'},{value:'center',label:'Center',icon:'fas fa-align-center'},{value:'right',label:'Right',icon:'fas fa-align-right'},{value:'justify',label:'Justify',icon:'fas fa-align-justify'}]}}};
</script>

<style scoped>
.pb-widget-settings--general-new .pb-form-row{display:grid;gap:12px}.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:repeat(2,minmax(0,1fr))}.pb-widget-settings--general-new .pb-compact-choice{display:grid;grid-template-columns:repeat(auto-fit,minmax(34px,1fr));gap:7px}.pb-widget-settings--general-new .pb-compact-choice .pb-seg-btn{min-width:0;height:32px;padding:0 8px}.pb-widget-settings--general-new .pb-form-group{margin-bottom:14px}.pb-widget-settings--general-new .pb-form-row .pb-form-group{margin-bottom:0}.pb-widget-settings--general-new .pb-collapsible-body{padding-top:13px}.pb-widget-settings--general-new .pb-input,.pb-widget-settings--general-new .pb-select,.pb-widget-settings--general-new .pb-textarea{min-height:36px}@media(max-width:420px){.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:1fr}}
</style>
