<template>
						<div class="pb-image-box-settings pb-widget-settings pb-widget-settings--image-box">
							<div class="pb-tab-nav">
								<button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button>
								<button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button>
								<button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button>
							</div>

							<div v-show="editor.settingsTab==='content'" class="pb-tab-content">
								<details class="pb-collapsible" open>
									<summary>Image Box</summary>
									<div class="pb-collapsible-body">
										<div class="pb-form-group">
											<label class="pb-form-label">Choose Image</label>
											<div class="pb-bg-media-field pb-widget-settings__media-field" :class="{ 'has-image': !!node.settings.imageUrl }">
												<div class="pb-bg-media-preview" :style="node.settings.imageUrl ? { backgroundImage: 'url(' + node.settings.imageUrl + ')' } : {}">
													<button type="button" class="pb-bg-media-center-btn" :title="node.settings.imageUrl ? 'Change Image' : 'Choose Image'" @click="editor.chooseMedia(node.settings, 'imageUrl')"><i :class="node.settings.imageUrl ? 'fas fa-pen' : 'fas fa-plus'"></i></button>
												</div>
												<div class="pb-bg-media-actions">
													<button type="button" class="pb-bg-media-choose" @click="editor.chooseMedia(node.settings, 'imageUrl')">Choose Image</button>
													<button type="button" class="pb-bg-media-remove" :disabled="!node.settings.imageUrl" title="Remove Image" @click="editor.clearMedia(node.settings, 'imageUrl')"><i class="fas fa-trash-alt"></i></button>
												</div>
											</div>
										</div>
										<div class="pb-form-group"><label class="pb-form-label">Image Resolution</label><select class="pb-select" v-model="node.settings.imageResolution"><option value="thumbnail">Thumbnail - 150px</option><option value="medium">Medium - 300px</option><option value="medium_large">Medium Large - 768px</option><option value="large">Large - 1024px</option><option value="1536x1536">1536 x 1536</option><option value="2048x2048">2048 x 2048</option><option value="full">Full</option></select></div>
										<div class="pb-form-group"><label class="pb-form-label">Title</label><div class="pb-image-box-dynamic-field"><input class="pb-input" v-model="node.settings.title"><component :is="editor.dynamicTagControl" :model-value="node.settings.dynamicBindings.title || ''" @update:modelValue="node.settings.dynamicBindings.title=$event" /></div></div>
										<div class="pb-form-group"><label class="pb-form-label">Description</label><div class="pb-image-box-dynamic-field pb-image-box-dynamic-field--textarea"><textarea class="pb-input" rows="5" v-model="node.settings.description"></textarea><component :is="editor.dynamicTagControl" :model-value="node.settings.dynamicBindings.description || ''" @update:modelValue="node.settings.dynamicBindings.description=$event" /></div></div>
										<div class="pb-form-group"><label class="pb-form-label">Link</label><component :is="editor.linkControl" :url="node.settings.linkUrl" :target="node.settings.linkTarget" :nofollow="node.settings.linkNofollow" :custom-attributes="node.settings.linkCustomAttributes" @update:url="node.settings.linkUrl=$event" @update:target="node.settings.linkTarget=$event" @update:nofollow="node.settings.linkNofollow=$event" @update:customAttributes="node.settings.linkCustomAttributes=$event" /></div>
										<div class="pb-form-group"><label class="pb-form-label">Title HTML Tag</label><select class="pb-select" v-model="node.settings.titleTag"><option v-for="tag in ['h1','h2','h3','h4','h5','h6','div','span','p']" :key="'image-box-tag-'+tag" :value="tag">{{ tag.toUpperCase() }}</option></select></div>
									</div>
								</details>
							</div>

							<div v-show="editor.settingsTab==='style'" class="pb-tab-content pb-image-box-style-settings">
								<details class="pb-collapsible" open>
									<summary>Box</summary>
									<div class="pb-collapsible-body">
										<div class="pb-form-group pb-image-box-choice-row"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">Image Position</label><div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu('image-box-position')" :title="'Responsive: ' + editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen('image-box-position')" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="'image-box-position-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice('image-box-position', device.value)"><i :class="device.icon"></i><span>{{ editor.deviceOptionLabel(device) }}</span></button></div></div></div><div class="pb-btn-group pb-image-box-segmented pb-image-box-segmented--three"><button v-for="option in [{value:'left',icon:'fas fa-arrow-left'},{value:'top',icon:'fas fa-arrow-up'},{value:'right',icon:'fas fa-arrow-right'}]" :key="'image-box-position-option-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey('imagePosition')]===option.value}" :aria-pressed="node.settings[editor.activeResponsiveKey('imagePosition')]===option.value" :title="option.value" @click.prevent="node.settings[editor.activeResponsiveKey('imagePosition')]=option.value"><i :class="option.icon"></i></button></div></div>
										<div class="pb-form-group pb-image-box-choice-row"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">Alignment</label><div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu('image-box-alignment')" :title="'Responsive: ' + editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen('image-box-alignment')" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="'image-box-alignment-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice('image-box-alignment', device.value)"><i :class="device.icon"></i><span>{{ editor.deviceOptionLabel(device) }}</span></button></div></div></div><div class="pb-btn-group pb-image-box-segmented pb-image-box-segmented--four"><button v-for="option in [{value:'left',icon:'fas fa-align-left'},{value:'center',icon:'fas fa-align-center'},{value:'right',icon:'fas fa-align-right'},{value:'justify',icon:'fas fa-align-justify'}]" :key="'image-box-alignment-option-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey('alignment')]===option.value}" :aria-pressed="node.settings[editor.activeResponsiveKey('alignment')]===option.value" :title="option.value" @click.prevent="node.settings[editor.activeResponsiveKey('alignment')]=option.value"><i :class="option.icon"></i></button></div></div>
										<div v-for="control in [{key:'imageSpacing',label:'Image Spacing',fallback:'15px',id:'image-box-image-spacing'},{key:'contentSpacing',label:'Content Spacing',fallback:'0px',id:'image-box-content-spacing'}]" :key="control.key" class="pb-form-group pb-image-box-dimension-control"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{ control.label }}</label><div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu(control.id)" :title="'Responsive: ' + editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen(control.id)" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="control.id+'-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice(control.id, device.value)"><i :class="device.icon"></i><span>{{ editor.deviceOptionLabel(device) }}</span></button></div></div></div><div class="pb-range-value-row"><input class="pb-range" type="range" min="0" :max="editor.sizeControlMax(node, control.key, control.fallback)" :step="editor.sizeControlStep(node, control.key, control.fallback)" :value="editor.sizeControlDisplayValue(node, control.key, control.fallback)" @input="editor.onSizeControlInput(node, control.key, $event, {fallback:control.fallback})"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" min="0" :value="editor.sizeControlDisplayValue(node, control.key, control.fallback)" @input="editor.onSizeControlInput(node, control.key, $event, {fallback:control.fallback})"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node, control.key, control.fallback)" @change="editor.setSizeControlUnit(node, control.key, $event.target.value, {fallback:control.fallback})"><option v-for="unit in editor.sizeControlUnits" :key="control.key+'-'+unit" :value="unit">{{ unit }}</option></select></div></div></div>
									</div>
								</details>

								<details class="pb-collapsible" open>
									<summary>Image</summary>
									<div class="pb-collapsible-body">
										<div class="pb-form-group pb-image-box-dimension-control"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">Width</label><div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu('image-box-width')" :title="'Responsive: ' + editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen('image-box-width')" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="'image-box-width-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice('image-box-width', device.value)"><i :class="device.icon"></i><span>{{ editor.deviceOptionLabel(device) }}</span></button></div></div></div><div class="pb-range-value-row"><input class="pb-range" type="range" min="0" :max="editor.sizeControlMax(node, 'imageWidth', '30%')" :step="editor.sizeControlStep(node, 'imageWidth', '30%')" :value="editor.sizeControlDisplayValue(node, 'imageWidth', '30%')" @input="editor.onSizeControlInput(node, 'imageWidth', $event, {fallback:'30%'})"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" min="0" :value="editor.sizeControlDisplayValue(node, 'imageWidth', '30%')" @input="editor.onSizeControlInput(node, 'imageWidth', $event, {fallback:'30%'})"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node, 'imageWidth', '30%')" @change="editor.setSizeControlUnit(node, 'imageWidth', $event.target.value, {fallback:'30%'})"><option v-for="unit in editor.sizeControlUnits" :key="'image-box-width-unit-'+unit" :value="unit">{{ unit }}</option></select></div></div></div>
										<div class="pb-form-group"><label class="pb-form-label">Border Type</label><select class="pb-select" v-model="node.settings.imageBorderType"><option value="none">Default</option><option value="solid">Solid</option><option value="double">Double</option><option value="dotted">Dotted</option><option value="dashed">Dashed</option><option value="groove">Groove</option></select></div>
										<template v-if="node.settings.imageBorderType!=='none'"><div class="pb-form-group"><label class="pb-form-label">Border Width</label><input class="pb-input" v-model="node.settings.imageBorderWidth" placeholder="1px"></div><div class="pb-form-group"><label class="pb-form-label">Border Color</label><input class="pb-input pb-coloris-input" v-model="node.settings.imageBorderColor"></div></template>
										<div class="pb-form-group pb-image-box-dimension-control"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">Border Radius</label><div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu('image-box-radius')" :title="'Responsive: ' + editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen('image-box-radius')" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="'image-box-radius-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice('image-box-radius', device.value)"><i :class="device.icon"></i><span>{{ editor.deviceOptionLabel(device) }}</span></button></div></div></div><div class="pb-range-value-row"><input class="pb-range" type="range" min="0" :max="editor.sizeControlMax(node, 'imageBorderRadius', '0px')" :step="editor.sizeControlStep(node, 'imageBorderRadius', '0px')" :value="editor.sizeControlDisplayValue(node, 'imageBorderRadius', '0px')" @input="editor.onSizeControlInput(node, 'imageBorderRadius', $event, {fallback:'0px'})"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" min="0" :value="editor.sizeControlDisplayValue(node, 'imageBorderRadius', '0px')" @input="editor.onSizeControlInput(node, 'imageBorderRadius', $event, {fallback:'0px'})"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node, 'imageBorderRadius', '0px')" @change="editor.setSizeControlUnit(node, 'imageBorderRadius', $event.target.value, {fallback:'0px'})"><option v-for="unit in editor.sizeControlUnits" :key="'image-box-radius-unit-'+unit" :value="unit">{{ unit }}</option></select></div></div></div>
										<div class="pb-state-tabs pb-state-tabs--two"><button type="button" :class="{active:editor.imageBoxImageState==='normal'}" @click="editor.imageBoxImageState='normal'">Normal</button><button type="button" :class="{active:editor.imageBoxImageState==='hover'}" @click="editor.imageBoxImageState='hover'">Hover</button></div>
										<component :is="editor.cssFilterControl" v-if="editor.imageBoxImageState==='normal'" v-model="node.settings.imageNormalFilter" />
										<component :is="editor.cssFilterControl" v-else v-model="node.settings.imageHoverFilter" />
										<div class="pb-form-group"><label class="pb-form-label">Opacity</label><div v-if="editor.imageBoxImageState==='normal'" class="pb-range-value-row"><input class="pb-range" type="range" min="0" max="1" step="0.01" v-model.number="node.settings.imageNormalOpacity"><input class="pb-input pb-input-compact" type="number" min="0" max="1" step="0.01" v-model.number="node.settings.imageNormalOpacity"></div><div v-else class="pb-range-value-row"><input class="pb-range" type="range" min="0" max="1" step="0.01" v-model.number="node.settings.imageHoverOpacity"><input class="pb-input pb-input-compact" type="number" min="0" max="1" step="0.01" v-model.number="node.settings.imageHoverOpacity"></div></div>
										<div v-if="editor.imageBoxImageState==='hover'" class="pb-form-group"><label class="pb-form-label">Transition Duration</label><div class="pb-range-value-row"><input class="pb-range" type="range" min="0" max="5" step="0.1" v-model.number="node.settings.imageHoverTransition"><input class="pb-input pb-input-compact" type="number" min="0" max="10" step="0.1" v-model.number="node.settings.imageHoverTransition"></div></div>
									</div>
								</details>

								<details class="pb-collapsible" open>
									<summary>Content</summary>
									<div class="pb-collapsible-body">
										<div class="pb-subsection-title">Title</div>
										<div class="pb-form-group"><label class="pb-form-label">Color</label><input class="pb-input pb-coloris-input" v-model="node.settings.titleColor"></div>
										<component :is="editor.typographyControl" prefix="title" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'29px',FontWeight:'400',LineHeight:'1.2em'}" @responsive-device="editor.setResponsiveDevice" />
										<div class="pb-form-group"><label class="pb-form-label">Text Stroke</label><div class="pb-image-box-inline-fields"><input class="pb-input" v-model="node.settings.titleTextStrokeWidth" placeholder="0px"><input class="pb-input pb-coloris-input" v-model="node.settings.titleTextStrokeColor"></div></div>
										<div class="pb-form-group"><label class="pb-form-label">Text Shadow</label><input class="pb-input" v-model="node.settings.titleTextShadow" placeholder="0 1px 2px rgba(0,0,0,.15)"></div>
										<div class="pb-subsection-title pb-subsection-title--spaced">Description</div>
										<div class="pb-form-group"><label class="pb-form-label">Color</label><input class="pb-input pb-coloris-input" v-model="node.settings.descriptionColor"></div>
										<component :is="editor.typographyControl" prefix="description" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'16px',FontWeight:'400',LineHeight:'1.5em'}" @responsive-device="editor.setResponsiveDevice" />
										<div class="pb-form-group"><label class="pb-form-label">Text Shadow</label><input class="pb-input" v-model="node.settings.descriptionTextShadow" placeholder="0 1px 2px rgba(0,0,0,.15)"></div>
									</div>
								</details>
							</div>

							<div v-show="editor.settingsTab==='advanced'" class="pb-tab-content pb-image-box-advanced-settings">
								<component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" @responsive-device="editor.setResponsiveDevice" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" />
							</div>
						</div>
</template>

<script>
export default { name: 'ImageBoxWidgetSettings', props: { node: { type: Object, required: true }, editor: { type: Object, required: true } } };
</script>
