<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('accounts')->insert([
        [
            'id' => 1,
            'uuid' => 'd7787d9e-e11f-4fcd-8e76-8bab72eb3073',
            'email' => 'admin@aruna-dev.com',
            'username' => 'administrator',
            'fullname' => 'Administrator',
            'password' => '$2y$12$DOZYv27cil8FPhMZUIdqduaeFMzVrNC2rBadwAH5TM1o6tvKyyw5q',
            'remember_token' => '',
            'status' => 1,
            'recovery_code' => 'laraphoexRecovery_66ebe9edb48e0',
            'recovery_code_duration' => null,
            'token' => 'LaraPhoenixPAT_66ebe9edb494d',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-22 17:18:08',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 2,
            'uuid' => 'd1c7bc73-00b2-4d5e-9d32-f97fd00e8cde',
            'email' => 'andhika@aruna-dev.com',
            'username' => 'andhika',
            'fullname' => 'Andhika Adhitia N',
            'password' => '$2y$12$UgDY./heHCqF/m6PsL.9Ru8I8zwEeBfmxSzHNdBd3V1cSY/2OV91S',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => 'laraphoexRecovery_668d074ed832e',
            'recovery_code_duration' => null,
            'token' => 'LaraPhoenixPAT_668d074ed837f',
            'suspended_until' => '2025-05-27 08:14:41',
            'suspended_at' => null,
            'updated_at' => '2025-07-25 04:35:02',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 3,
            'uuid' => '',
            'email' => 'pitaloka@aruna-dev.com',
            'username' => 'pitaloka',
            'fullname' => 'Pitaloka',
            'password' => '$2y$10$D4.yjlvcKRErC5SynYsUqe71dL8rp5VcAr3dY6jPV7Ygd4gU.2vZq',
            'remember_token' => '',
            'status' => 1,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-09-04 01:54:13',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 4,
            'uuid' => '',
            'email' => 'malika@aruna-dev.id',
            'username' => 'malika',
            'fullname' => 'Malika',
            'password' => '$2y$10$x2NIm41WOYXfbG/V/KMW2uMMwb/qkogPqrS8n5U1nigtUCEIJZrRG',
            'remember_token' => '',
            'status' => 1,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-01-20 02:28:19',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 5,
            'uuid' => '',
            'email' => 'rajolangit@aruna-dev.id',
            'username' => 'rajolangit',
            'fullname' => 'Rajo Langit',
            'password' => '$2y$10$PesVGBgTRMuxoRbA3plyVO0FbsOJTEHnoMxAOxJbYVmH.qJyJWuaK',
            'remember_token' => '',
            'status' => 1,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-01-20 02:29:02',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 6,
            'uuid' => '',
            'email' => 'limbubu@aruna-dev.id',
            'username' => 'limbubu',
            'fullname' => 'Lim Bubu',
            'password' => '$2y$12$XC5S.tJh2.Bh1H/qoYTqRO7nbtKCHqe/UoyxXKbzN4bQrBxpuK4ya',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => 'laraphoexRecovery_66a340a83f0af',
            'recovery_code_duration' => null,
            'token' => 'LaraPhoenixPAT_66a340a83f226',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-25 23:22:32',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 7,
            'uuid' => '',
            'email' => 'aruna.dev96@gmail.com',
            'username' => 'arunika',
            'fullname' => 'Arunika',
            'password' => '$2y$12$YIS/nzRdNEzAmtVSxiSX2OQzYTJyi4oGjMABfhatD9M9XuRv2q6rC',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '9jQXDAs8L1SHk5O42phmZK',
            'recovery_code_duration' => 1748472272,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:43:32',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 8,
            'uuid' => '',
            'email' => 'azazahra@gmail.com',
            'username' => 'azazahra',
            'fullname' => 'Az Zahra',
            'password' => '$2y$10$w3q.fRXsg0lJ3J2EyR03Ju3ztb36p/PreMR7VRrGSXEMZAofQJta.',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:24:14',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 9,
            'uuid' => '',
            'email' => 'kirana@gmail.com',
            'username' => 'kirana',
            'fullname' => 'Kirana',
            'password' => '$2y$10$jcDoRAel/3.hBdDktKqsSOJ5lSYZUsXyO0nuHnViaNaGvQRdP/iAC',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:24:14',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 10,
            'uuid' => '889017d8-a466-4791-bae9-c7cb2ac410fc',
            'email' => 'gumara@aruna-dev.id',
            'username' => 'gumara',
            'fullname' => 'Gumara Peto Alam Edited',
            'password' => '$2y$10$XjReXV4PvTE1ZYpCIQgrL.65m5BehtOhFkmjnSKmI5cBzTJOs7ZPC',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2026-01-09 07:08:11',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 11,
            'uuid' => '',
            'email' => 'cyber.phoenix@aruna-dev.id',
            'username' => 'cyber_phoenix',
            'fullname' => 'Cyber Phoenix',
            'password' => '$2y$10$YdWG1tsalZCI/wBqbcUoluiSRGG8Rt9OT06ilBDadNOlEUYREOzh6',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:25:00',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 12,
            'uuid' => '',
            'email' => 'hazy@gmail.com',
            'username' => 'hazy',
            'fullname' => 'Hazy',
            'password' => '$2y$10$FGNs7EJioCPWjzRsOyOiseKaCQOP8OpDXwj4lFF2JFNSuTGXPVXGK',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:25:00',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 13,
            'uuid' => '',
            'email' => 'seven.lions@aruna-dev.id',
            'username' => 'seven_lions',
            'fullname' => 'Seven Lions',
            'password' => '$2y$10$cFtgjygnQ.uqVtRe3KtNe./38PYj72zY.qPtAgEE/HP.zOIR8mv22',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:25:00',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 14,
            'uuid' => '',
            'email' => 'illenium.ashes@aruna-dev.id',
            'username' => 'illenium',
            'fullname' => 'Illenium Ashes',
            'password' => '$2y$10$08fHik6WBl3H4aI5aJwlD.qDHA1Y2.VdLGs1KsPKFiqfD/r7Qdcj6',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:25:00',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 15,
            'uuid' => '',
            'email' => 'karina@aruna-dev.id',
            'username' => 'karina',
            'fullname' => 'Karina',
            'password' => '$2y$10$oF8bK8jB3oHmSojXVwDFn.QA2szbCl0X/TP6jh.epnjlng9.SQWL.',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:25:00',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 16,
            'uuid' => '',
            'email' => 'andhika.adhitia96@gmail.com',
            'username' => 'adhitia',
            'fullname' => 'Adhitia',
            'password' => '$2y$10$0ETFtB0IOu4xL1zwo0O3HewgOivmjZ9peZM.NKdlNWLXizavx.Jly',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '0Vjrf5Q2EZMgv1SxYuaKbF',
            'recovery_code_duration' => 1748595974,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-30 09:01:14',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 17,
            'uuid' => '',
            'email' => 'rfasyurapvp@gmail.com',
            'username' => 'asyura',
            'fullname' => 'RF Asyura',
            'password' => '$2y$10$tL16JDjpj3w5K3xxbtfz2.4iPTJin3r7wcL8RpjClzBWDdOIL3nse',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2024-07-09 02:25:00',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 18,
            'uuid' => 'c8de9f7d-07ba-4108-8812-1b413854017c',
            'email' => 'gumara.peto@aruna-dev.id',
            'username' => 'gumara_peto_alam',
            'fullname' => 'Gumara Peto Alam Edited 2',
            'password' => '$2y$10$1zuUYhahQ.1IaCp8owh1tOeTW99ZsjI/Dr1mKnxF3jmPdxC3kdWoe',
            'remember_token' => '',
            'status' => 2,
            'recovery_code' => '',
            'recovery_code_duration' => null,
            'token' => '',
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2026-01-09 07:08:28',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 19,
            'uuid' => null,
            'email' => 'testing_account1@aruna-dev.com',
            'username' => 'testing_account1',
            'fullname' => 'Testing Account 1',
            'password' => '$2y$12$XiILVlL9SR1Gz1rJKcnOruuD33k0lOGpNbRZCARUaeCRwz6OYDlXC',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:48:08',
            'created_at' => '2025-05-17 05:31:47'
        ],
        [
            'id' => 20,
            'uuid' => null,
            'email' => 'testing_account2@aruna-dev.com',
            'username' => 'u8534609',
            'fullname' => 'Testing Account 2',
            'password' => '$2y$12$1nf01.LCgUzeDMEewaKL2Oeo075rpXwcJj08WIN78i6ZggwUkOHAa',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:48:48',
            'created_at' => '2025-05-17 06:15:27'
        ],
        [
            'id' => 21,
            'uuid' => null,
            'email' => 'testing_account3@aruna-dev.com',
            'username' => 'u6203581',
            'fullname' => 'Testing Account 3',
            'password' => '$2y$12$K9BXIIvVD8BmykHExnpMYO8mXsDP6odtjEJJboojSdQlmoQO8qnV6',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:49:50',
            'created_at' => '2025-05-17 06:17:00'
        ],
        [
            'id' => 22,
            'uuid' => null,
            'email' => 'testing_account4@aruna-dev.com',
            'username' => 'u9017563',
            'fullname' => 'Testing Account 4',
            'password' => '$2y$12$DdOCsleN4Wbkqo.sLU43PeVUbhos/JIQ.sGzj8p.U9Z8G88c3ul9S',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:51:03',
            'created_at' => '2025-05-17 06:18:37'
        ],
        [
            'id' => 23,
            'uuid' => null,
            'email' => 'testing_account5@aruna-dev.com',
            'username' => 'u6309178',
            'fullname' => 'Testing Account 5',
            'password' => '$2y$12$6kxbVJ85D0qyJeE/60xaf.7.K9LIIUV4KOnZPQDjqa5ZGuzRVU9He',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:51:06',
            'created_at' => '2025-05-17 06:20:00'
        ],
        [
            'id' => 24,
            'uuid' => null,
            'email' => 'testing_account6@aruna-dev.com',
            'username' => 'u3806251',
            'fullname' => 'Testing Account 6',
            'password' => '$2y$12$dzrwN.Gt4mIam2ldlOPfZODucb6hVMg3Xr6Wk/VfRha39oVyqxB1i',
            'remember_token' => null,
            'status' => 2,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:51:07',
            'created_at' => '2025-05-17 06:26:51'
        ],
        [
            'id' => 25,
            'uuid' => null,
            'email' => 'testing_account7@aruna-dev.com',
            'username' => 'u1960873',
            'fullname' => 'Testing Account 7',
            'password' => '$2y$12$NCWwIvGkK.AaGvraPQIA0eFPkvGeZ8/bEw3HM6BrnZ2DUq7.qOG.K',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:51:12',
            'created_at' => '2025-05-17 06:29:05'
        ],
        [
            'id' => 26,
            'uuid' => null,
            'email' => 'testing_account8@aruna-dev.com',
            'username' => 'u9250843',
            'fullname' => 'Testing Account 8',
            'password' => '$2y$12$ER2rxZlqW5bmt.9u0UIMMeELnBO8iVUHhZkleMCJmw4U/vqltxO/.',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:51:35',
            'created_at' => '2025-05-17 06:32:21'
        ],
        [
            'id' => 27,
            'uuid' => null,
            'email' => 'testing_account9@aruna-dev.com',
            'username' => 'u9046721',
            'fullname' => 'Testing Account 9',
            'password' => '$2y$12$GF2HAKaAtNzJaHV2jR9.kuXZSdB5mkZIGCUdXes2C6/.ypprp09Hm',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:51:58',
            'created_at' => '2025-05-17 06:33:54'
        ],
        [
            'id' => 28,
            'uuid' => null,
            'email' => 'testing_account10@aruna-dev.com',
            'username' => 'u1839245',
            'fullname' => 'Testing Account 10',
            'password' => '$2y$12$radpvBOkQky/zrz6ndddLOvDh3SnN6mMbU.gG7rzPzGVuW9Ql8Tte',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:53:33',
            'created_at' => '2025-05-17 06:35:13'
        ],
        [
            'id' => 29,
            'uuid' => null,
            'email' => 'testing_account11@aruna-dev.com',
            'username' => 'testing_account11',
            'fullname' => 'Testing Account 11',
            'password' => '$2y$12$V9QJvENrK6AKkOBFWsXpn.0yNIFLrwtEhRs.EsrbbyasBD2TfqDha',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:54:43',
            'created_at' => '2025-05-17 06:35:42'
        ],
        [
            'id' => 30,
            'uuid' => null,
            'email' => 'testing_account12@aruna-dev.com',
            'username' => 'u1923784',
            'fullname' => 'Testing Account 12',
            'password' => '$2y$12$zHwxBKncFaMcQG24lI099usB5MyaaWveJeLnSPBbci7UYaCJDTNYm',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:55:39',
            'created_at' => '2025-05-17 06:36:04'
        ],
        [
            'id' => 31,
            'uuid' => null,
            'email' => 'testing_account13@aruna-dev.com',
            'username' => 'testing_account13',
            'fullname' => 'Testing Account 13',
            'password' => '$2y$12$LzdK73yrUB/pqC.9/sdiL.mktY6tSlyeEF9IxAFifpQVP.zLqtx2i',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 21:56:20',
            'created_at' => '2025-05-17 06:36:46'
        ],
        [
            'id' => 32,
            'uuid' => null,
            'email' => 'testing_account14@aruna-dev.com',
            'username' => 'testing_account14',
            'fullname' => 'Testing Account 14',
            'password' => '$2y$12$z2MeG7Vjb4yPh9LdYtsvbevsmmxsRvZ3Ty9LuEiwgRDulOR7JQpk2',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:03:04',
            'created_at' => '2025-05-17 06:37:44'
        ],
        [
            'id' => 33,
            'uuid' => null,
            'email' => 'testing_account15@aruna-dev.com',
            'username' => 'testing_account15',
            'fullname' => 'Testing Account 15',
            'password' => '$2y$12$QjhdOfMIYDXJJXsxncdqWeFkPZBq6my8LbZEHu6m9P8T2jlu6Xwqa',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:04:06',
            'created_at' => '2025-05-17 06:38:16'
        ],
        [
            'id' => 34,
            'uuid' => null,
            'email' => 'testing_account16@aruna-dev.com',
            'username' => 'u2179306',
            'fullname' => 'Testing Account 16',
            'password' => '$2y$12$NDeok4SZ.IByeRpQqc5FgumNsXDuboVy1V2U1qEsQIYFGmEe.b6KG',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:04:08',
            'created_at' => '2025-05-17 06:38:56'
        ],
        [
            'id' => 35,
            'uuid' => null,
            'email' => 'testing_account17@aruna-dev.com',
            'username' => 'testing_account17',
            'fullname' => 'Testing Account 17',
            'password' => '$2y$12$ZzT4gUdE9xbb9eBH1KeKdOViVXJUx7nZDgCRv7X.bFvP7HvVeLOhC',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:04:19',
            'created_at' => '2025-05-17 06:42:09'
        ],
        [
            'id' => 36,
            'uuid' => null,
            'email' => 'testing_account18@aruna-dev.com',
            'username' => 'u9481230',
            'fullname' => 'Testing Account 18',
            'password' => '$2y$12$2gGsZm.E7d0J7XnD9XRUiujtNjYSjebDzv0uRmAwg1Hl7vEmvhlkC',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:04:49',
            'created_at' => '2025-05-17 06:43:04'
        ],
        [
            'id' => 37,
            'uuid' => null,
            'email' => 'testing_account19@aruna-dev.com',
            'username' => 'u8079542',
            'fullname' => 'Testing Account 19',
            'password' => '$2y$12$O7yF5O1SLgqJxSW2ECkPO.cWSGryRIjVoTrJYgy/k215bS9Y0zeSe',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:05:40',
            'created_at' => '2025-05-17 06:45:21'
        ],
        [
            'id' => 38,
            'uuid' => null,
            'email' => 'testing_account20@aruna-dev.com',
            'username' => 'testing_account20',
            'fullname' => 'Testing Account 20',
            'password' => '$2y$12$Sj0fltZc.CsaLGsHhcOIhuhgvKQASBLrksA/isaGonC72TkRkStjW',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:05:43',
            'created_at' => '2025-05-17 08:33:33'
        ],
        [
            'id' => 39,
            'uuid' => null,
            'email' => 'testing_account21@aruna-dev.com',
            'username' => 'testing_account21',
            'fullname' => 'Testing Account 21 Edited',
            'password' => '$2y$12$MYsOqiDkKm3wxbC1nUsShutCfxiFqb28FYPWWcVVitcCYe855/uR6',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:05:55',
            'created_at' => '2025-05-17 08:35:28'
        ],
        [
            'id' => 40,
            'uuid' => null,
            'email' => 'testing_account22@aruna-dev.com',
            'username' => 'testing_account22',
            'fullname' => 'Testing Account 22',
            'password' => '$2y$12$Bp6oN.io6Mrv/B77UGYrHucFbFzRuV0/9/MBdLLlxD72itTAXZkX.',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => 'KONTOL',
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-28 22:05:57',
            'created_at' => '2025-05-17 08:36:54'
        ],
        [
            'id' => 41,
            'uuid' => null,
            'email' => 'testing_account23@aruna-dev.com',
            'username' => 'testing_account23',
            'fullname' => 'Testing Account 23 Edited',
            'password' => '$2y$12$9JCgU4YONyc.N/CvV8oVoukkHSvhnwZYTYU3.TlcJFecb7x2/HNZi',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-17 08:41:04',
            'created_at' => '2025-05-17 08:37:40'
        ],
        [
            'id' => 45,
            'uuid' => null,
            'email' => 'andhika96@aruna-dev.com',
            'username' => 'andhika96',
            'fullname' => 'Andhika 96',
            'password' => '$2y$12$xGoAcx6Syh74bq6lS48rpONsHsipW0QQaF.6IJHTbujZGW.U03Zzq',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-06-14 14:57:02',
            'created_at' => '2025-05-26 01:22:08'
        ],
        [
            'id' => 46,
            'uuid' => null,
            'email' => 'andhika06@aruna-dev.com',
            'username' => 'andhika06',
            'fullname' => 'Andhika 06',
            'password' => '$2y$12$OdFT1EpcGUXXtKmt0Okf0.BLi8s3P1jY/A8.LeJztGo7CgEuVkCni',
            'remember_token' => null,
            'status' => 3,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-26 01:23:09',
            'created_at' => '2025-05-26 01:23:09'
        ],
        [
            'id' => 47,
            'uuid' => null,
            'email' => 'andhika19@aruna-dev.com',
            'username' => 'andhika19',
            'fullname' => 'Andhika 19',
            'password' => '$2y$12$4Z0DsIv1lQotGmhGGOai3en8D0.Zgc6HOI8wd5sE9vqwdXnOOr/va',
            'remember_token' => null,
            'status' => 3,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-26 01:25:42',
            'created_at' => '2025-05-26 01:25:42'
        ],
        [
            'id' => 48,
            'uuid' => null,
            'email' => 'andhika1906@aruna-dev.com',
            'username' => 'andhika1906',
            'fullname' => 'Andhika 1906',
            'password' => '$2y$12$4rbaEpeMeSf3yUViFzNaZeTSJ9OLkDnVqZ/9ItU37p3GPoNNrxwfC',
            'remember_token' => null,
            'status' => 3,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => '2025-05-26 01:30:23',
            'updated_at' => '2025-05-26 01:30:23',
            'created_at' => '2025-05-26 01:30:23'
        ],
        [
            'id' => 49,
            'uuid' => null,
            'email' => 'andhika1996@aruna-dev.com',
            'username' => 'andhika1996',
            'fullname' => 'Andhika 1996',
            'password' => '$2y$12$no/HZ8Mc1OuZ.S0RUeYa8.tIUTv25bHfcTSmbqWhZqoTB45b5vlMS',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-26 01:31:37',
            'created_at' => '2025-05-26 01:31:37'
        ],
        [
            'id' => 50,
            'uuid' => null,
            'email' => 'andhika.testing12@gmail.com',
            'username' => 'andhika.testing12',
            'fullname' => 'Andhika Testing 12',
            'password' => '$2y$12$dLhUpWwNVQHoZJPSlqEImOx3BiRu2xFOwqUbdzxfV1zqRuBxkPxQ.',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-05-26 01:32:53',
            'created_at' => '2025-05-26 01:32:53'
        ],
        [
            'id' => 58,
            'uuid' => null,
            'email' => 'testing_account100@aruna-dev.com',
            'username' => 'testing_account100',
            'fullname' => 'testing_account100',
            'password' => '$2y$12$/FB55JdKjeEPek0qlN5gSu2QPtiLto6Kn3hjTjb1Fs3Dzv9rLEN42',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-07-25 02:43:23',
            'created_at' => '2025-07-21 09:07:02'
        ],
        [
            'id' => 59,
            'uuid' => '8702522e-1c44-4ce8-80b5-118e4ea5ec59',
            'email' => 'testing_account101@aruna-dev.com',
            'username' => 'testing_account101',
            'fullname' => 'testing_account101',
            'password' => '$2y$12$CbqW/V0O/xWBgwI6qGBHfembAB6NSA0L8/v2MnMgEs7zBg6iv.LX6',
            'remember_token' => null,
            'status' => 3,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-07-21 09:08:52',
            'created_at' => '2025-07-21 09:08:52'
        ],
        [
            'id' => 60,
            'uuid' => 'd1c7bc73-00b2-4d5e-9d32-f97fd00e8cde',
            'email' => 'testing_account200@aruna-dev.com',
            'username' => 'testing_account200',
            'fullname' => 'Testing Account 200',
            'password' => 'LaraPhoenixDev',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-04 08:17:32',
            'created_at' => '2025-08-04 08:17:32'
        ],
        [
            'id' => 61,
            'uuid' => '16acd371-8cee-4c92-a1ea-8f6992e542c7',
            'email' => 'testing_account201@aruna-dev.com',
            'username' => 'testing_account201',
            'fullname' => 'Testing Account 201',
            'password' => '$2y$12$joOz3zFv4sARaU9nq2FzuO0zxpBCnhQ5e.Ex4/Q54jPJcL/ndn2JK',
            'remember_token' => null,
            'status' => 3,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-04 08:33:07',
            'created_at' => '2025-08-04 08:33:07'
        ],
        [
            'id' => 62,
            'uuid' => 'ed2ba545-4a4c-4a0e-8242-0898be01821b',
            'email' => 'testing_account202@aruna-dev.com',
            'username' => 'testing_account202',
            'fullname' => 'Testing Account 201',
            'password' => '$2y$12$AhBXnDH5AUwbecCE75IYDOu0aivtufyJdx5n8RmWKPP9vA4nOuNCq',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-04 09:04:05',
            'created_at' => '2025-08-04 09:04:05'
        ],
        [
            'id' => 63,
            'uuid' => 'e292e1a7-3196-4833-b28b-86866f2dbd8e',
            'email' => 'testing_account203@aruna-dev.com',
            'username' => 'testing_account203',
            'fullname' => 'Testing Account 203',
            'password' => 'LaraPhoenixDev',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-04 09:31:25',
            'created_at' => '2025-08-04 09:31:25'
        ],
        [
            'id' => 64,
            'uuid' => '78e5d738-6b45-47ea-88b1-756df2de6ea8',
            'email' => 'testing_account204@aruna-dev.com',
            'username' => 'testing_account204',
            'fullname' => 'Testing Account 204',
            'password' => '$2y$12$XIZ9iPiWmhupguXEVwpe8.ZKSFNzcWvGr.CT1A5VhsxeAYSnfE9O6',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-04 09:36:22',
            'created_at' => '2025-08-04 09:35:26'
        ],
        [
            'id' => 65,
            'uuid' => '184b9f6b-d7d3-4a31-8a52-d0c0dcc18788',
            'email' => 'asdasdasd',
            'username' => 'asdasd',
            'fullname' => 'asd',
            'password' => 'LaraPhoenixDev',
            'remember_token' => null,
            'status' => 1,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-18 08:55:15',
            'created_at' => '2025-08-18 08:55:15'
        ],
        [
            'id' => 66,
            'uuid' => 'cdab9b3a-edf9-43e5-8b2d-8e68fa2b0b4e',
            'email' => 'asdasd2',
            'username' => 'asdasd2',
            'fullname' => 'asdasd2',
            'password' => 'LaraPhoenixDev',
            'remember_token' => null,
            'status' => 2,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2025-08-18 08:56:11',
            'created_at' => '2025-08-18 08:56:11'
        ],
        [
            'id' => 67,
            'uuid' => 'dac7a758-06f0-465f-bc8a-53d0ce32fe72',
            'email' => 'andhikakw1@aruna-dev.com',
            'username' => 'andhikakw1',
            'fullname' => 'Andhika KW 1',
            'password' => '$2y$12$JHQhiOQngO6wR/eWT4lUCevzwclYhjeDu4UOuERMmKMozZEKy8aSW',
            'remember_token' => null,
            'status' => 3,
            'recovery_code' => null,
            'recovery_code_duration' => null,
            'token' => null,
            'suspended_until' => null,
            'suspended_at' => null,
            'updated_at' => '2026-01-02 17:06:10',
            'created_at' => '2026-01-02 17:06:10'
        ]
        ]);
    }
}
