<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticlesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('articles')->insert([
        [
            'id' => 4,
            'uri' => 'testing',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-25 08:53:52',
            'created_at' => '2025-08-09 17:00:00'
        ],
        [
            'id' => 5,
            'uri' => 'testing-2',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 2',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-25 08:53:52',
            'created_at' => '2025-08-30 17:00:00'
        ],
        [
            'id' => 6,
            'uri' => 'testing-2',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 2',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'pending',
            'scheduled' => 'false',
            'updated_at' => '2025-08-19 07:49:27',
            'created_at' => '2025-08-19 07:49:27'
        ],
        [
            'id' => 7,
            'uri' => 'testing-3',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 3',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'password_protected',
            'password_protected' => 'QWERTY',
            'status' => 'pending',
            'scheduled' => 'false',
            'updated_at' => '2025-08-25 08:54:39',
            'created_at' => '2025-08-19 07:59:14'
        ],
        [
            'id' => 8,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-21 18:49:24',
            'created_at' => '2025-08-31 03:05:00'
        ],
        [
            'id' => 9,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 18:49:44',
            'created_at' => '2025-08-21 18:49:44'
        ],
        [
            'id' => 10,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-21 18:50:12',
            'created_at' => '2025-08-28 13:00:00'
        ],
        [
            'id' => 11,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'password_protected',
            'password_protected' => 'TESTING',
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-21 18:51:01',
            'created_at' => '2025-08-24 13:00:00'
        ],
        [
            'id' => 12,
            'uri' => 'testing-testing',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:05:59',
            'created_at' => '2025-08-21 19:05:59'
        ],
        [
            'id' => 13,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:06:25',
            'created_at' => '2025-08-21 19:06:25'
        ],
        [
            'id' => 14,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:18:55',
            'created_at' => '2025-08-21 19:18:55'
        ],
        [
            'id' => 15,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:22:42',
            'created_at' => '2025-08-21 19:22:42'
        ],
        [
            'id' => 16,
            'uri' => 'awdawd',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDAWD',
            'content' => '<p>AWDAWDAWDWD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:22:57',
            'created_at' => '2025-08-21 19:22:57'
        ],
        [
            'id' => 17,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:24:06',
            'created_at' => '2025-08-21 19:24:06'
        ],
        [
            'id' => 18,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:28:49',
            'created_at' => '2025-08-21 19:28:49'
        ],
        [
            'id' => 19,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:29:05',
            'created_at' => '2025-08-21 19:29:05'
        ],
        [
            'id' => 28,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:44:42',
            'created_at' => '2025-08-21 19:44:42'
        ],
        [
            'id' => 29,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:44:59',
            'created_at' => '2025-08-21 19:44:59'
        ],
        [
            'id' => 35,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:58:37',
            'created_at' => '2025-08-21 19:58:36'
        ],
        [
            'id' => 36,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:59:10',
            'created_at' => '2025-08-21 19:59:09'
        ],
        [
            'id' => 37,
            'uri' => 'kwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'KWKWKWKWKW',
            'content' => '<p>KWKWKWKWKW</p>',
            'tags' => null,
            'thumb_s' => 'articles/082025/date_23/2ea4ad6d86de114d98fbe0205dc299e8_small.png',
            'thumb_l' => 'articles/082025/date_23/06e6b5ab768c902c9551efe627f62ce9.png',
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-22 20:59:59',
            'created_at' => '2025-08-22 20:59:58'
        ],
        [
            'id' => 38,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:06:25',
            'created_at' => '2025-08-21 19:06:25'
        ],
        [
            'id' => 39,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:18:55',
            'created_at' => '2025-08-21 19:18:55'
        ],
        [
            'id' => 40,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:22:42',
            'created_at' => '2025-08-21 19:22:42'
        ],
        [
            'id' => 41,
            'uri' => 'awdawd',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDAWD',
            'content' => '<p>AWDAWDAWDWD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:22:57',
            'created_at' => '2025-08-21 19:22:57'
        ],
        [
            'id' => 42,
            'uri' => 'awdasdawdw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDASDAWDW',
            'content' => '<p>ASDAWDAW</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:24:06',
            'created_at' => '2025-08-21 19:24:06'
        ],
        [
            'id' => 43,
            'uri' => 'testing-2',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 2',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'pending',
            'scheduled' => 'true',
            'updated_at' => '2025-08-19 07:49:17',
            'created_at' => '2025-08-30 17:00:00'
        ],
        [
            'id' => 44,
            'uri' => 'testing-2',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 2',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'pending',
            'scheduled' => 'false',
            'updated_at' => '2025-08-19 07:49:27',
            'created_at' => '2025-08-19 07:49:27'
        ],
        [
            'id' => 45,
            'uri' => 'testing-3',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 3',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'password_protected',
            'password_protected' => 'QWERTY',
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-19 07:59:14',
            'created_at' => '2025-08-19 07:59:14'
        ],
        [
            'id' => 46,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-21 18:49:24',
            'created_at' => '2025-08-31 03:05:00'
        ],
        [
            'id' => 47,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'password_protected',
            'password_protected' => 'TESTING',
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2025-08-21 18:51:01',
            'created_at' => '2025-08-24 13:00:00'
        ],
        [
            'id' => 48,
            'uri' => 'testing-testing',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2025-08-21 19:05:59',
            'created_at' => '2025-08-21 19:05:59'
        ],
        [
            'id' => 50,
            'uri' => 'awdawd',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'AWDAWD',
            'content' => '<p>AWDAWDAWDWD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2026-01-07 09:29:15',
            'created_at' => '2025-08-21 19:22:57'
        ],
        [
            'id' => 52,
            'uri' => 'testing-2',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 2',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'pending',
            'scheduled' => 'true',
            'updated_at' => '2026-01-07 09:29:15',
            'created_at' => '2025-08-30 17:00:00'
        ],
        [
            'id' => 53,
            'uri' => 'testing-2',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 2',
            'content' => '<p>Hello World!</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'private',
            'password_protected' => null,
            'status' => 'pending',
            'scheduled' => 'false',
            'updated_at' => '2026-01-07 09:29:15',
            'created_at' => '2025-08-19 07:49:27'
        ],
        [
            'id' => 54,
            'uri' => 'testing-3',
            'user_id' => 59,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 3',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'password_protected',
            'password_protected' => 'QWERTY',
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2026-01-07 09:29:15',
            'created_at' => '2025-08-19 07:59:14'
        ],
        [
            'id' => 55,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2026-01-07 09:29:15',
            'created_at' => '2025-08-31 03:05:00'
        ],
        [
            'id' => 56,
            'uri' => 'testing-4',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing 4',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'password_protected',
            'password_protected' => 'TESTING',
            'status' => 'publish',
            'scheduled' => 'true',
            'updated_at' => '2026-01-07 09:24:38',
            'created_at' => '2025-08-24 13:00:00'
        ],
        [
            'id' => 57,
            'uri' => 'testing-testing',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD ASDASDASD ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2026-03-18 05:47:55',
            'created_at' => '2026-03-18 05:47:55'
        ],
        [
            'id' => 58,
            'uri' => 'testing-testing-kwkwkwkwkwkw',
            'user_id' => 1,
            'category_id' => 1,
            'subcategory_id' => 0,
            'title' => 'Testing Testing',
            'content' => '<p>ASDASDASD</p>',
            'tags' => null,
            'thumb_s' => null,
            'thumb_l' => null,
            'visibility' => 'public',
            'password_protected' => null,
            'status' => 'publish',
            'scheduled' => 'false',
            'updated_at' => '2026-01-07 09:24:38',
            'created_at' => '2025-08-21 19:06:25'
        ]
        ]);
    }
}
