<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menu')->insert([
        [
            'id' => 1,
            'module' => 'manage_aboutus',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 1,
            'menu_parent_code' => 'manage_aboutus',
            'menu_parent_name' => 'Manage About Us',
            'menu_name' => 'About Us 1',
            'url' => 'manage_aboutus',
            'icon' => '<i class=\\"fad fa-address-card fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 2,
            'module' => 'manage_aboutus',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 1,
            'menu_parent_code' => 'manage_aboutus',
            'menu_parent_name' => 'Manage About Us',
            'menu_name' => 'About Us 2',
            'url' => 'manage_aboutus',
            'icon' => '<i class=\\"fad fa-address-card fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 3,
            'module' => 'manage_contactus',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 2,
            'menu_parent_code' => 'uncategorized_manage_contactus',
            'menu_parent_name' => '',
            'menu_name' => 'Manage Contact Us',
            'url' => 'manage_contactus',
            'icon' => '<i class=\\"fad fa-phone fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 4,
            'module' => 'manage_event',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 3,
            'menu_parent_code' => 'manage_event',
            'menu_parent_name' => 'Manage Event',
            'menu_name' => 'List of Event',
            'url' => 'manage_event',
            'icon' => '<i class=\\"fad fa-list fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 5,
            'module' => 'manage_event',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 3,
            'menu_parent_code' => 'manage_event',
            'menu_parent_name' => 'Manage Event',
            'menu_name' => 'Add New',
            'url' => 'manage_event/addpost',
            'icon' => '<i class=\\"fad fa-plus fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 6,
            'module' => 'manage_event',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 3,
            'menu_parent_code' => 'manage_event',
            'menu_parent_name' => 'Manage Event',
            'menu_name' => 'Event Categories',
            'url' => 'manage_event/category',
            'icon' => '<i class=\\"fad fa-folder fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 7,
            'module' => 'manage_event',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 3,
            'menu_parent_code' => 'manage_event',
            'menu_parent_name' => 'Manage Event',
            'menu_name' => 'Layout',
            'url' => 'manage_event/layout',
            'icon' => '<i class=\\"fad fa-swatchbook fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 8,
            'module' => 'manage_gallery',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 4,
            'menu_parent_code' => 'uncategorized_manage_gallery',
            'menu_parent_name' => '',
            'menu_name' => 'Manage Gallery',
            'url' => 'manage_gallery',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 9,
            'module' => 'manage_news',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 5,
            'menu_parent_code' => 'manage_news',
            'menu_parent_name' => 'Manage News',
            'menu_name' => 'List of News',
            'url' => 'manage_news',
            'icon' => '<i class=\\"fad fa-list fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 10,
            'module' => 'manage_news',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 5,
            'menu_parent_code' => 'manage_news',
            'menu_parent_name' => 'Manage News',
            'menu_name' => 'Add New',
            'url' => 'manage_news/addpost',
            'icon' => '<i class=\\"fad fa-plus fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 11,
            'module' => 'manage_news',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 5,
            'menu_parent_code' => 'manage_news',
            'menu_parent_name' => 'Manage News',
            'menu_name' => 'News Categories',
            'url' => 'manage_news/category',
            'icon' => '<i class=\\"fad fa-folder fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 12,
            'module' => 'manage_news',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 5,
            'menu_parent_code' => 'manage_news',
            'menu_parent_name' => 'Manage News',
            'menu_name' => 'Layout',
            'url' => 'manage_news/layout',
            'icon' => '<i class=\\"fad fa-swatchbook fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 13,
            'module' => 'manage_portofolio',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 6,
            'menu_parent_code' => 'manage_portofolio',
            'menu_parent_name' => 'Manage Portofolio',
            'menu_name' => 'List of Portofolio',
            'url' => 'manage_portofolio',
            'icon' => '<i class=\\"fad fa-list fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 14,
            'module' => 'manage_portofolio',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 6,
            'menu_parent_code' => 'manage_portofolio',
            'menu_parent_name' => 'Manage Portofolio',
            'menu_name' => 'Add New',
            'url' => 'manage_portofolio/addpost',
            'icon' => '<i class=\\"fad fa-plus fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 15,
            'module' => 'manage_portofolio',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 6,
            'menu_parent_code' => 'manage_portofolio',
            'menu_parent_name' => 'Manage Portofolio',
            'menu_name' => 'Portofolio Categories',
            'url' => 'manage_portofolio/category',
            'icon' => '<i class=\\"fad fa-folder fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 16,
            'module' => 'manage_portofolio',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 6,
            'menu_parent_code' => 'manage_portofolio',
            'menu_parent_name' => 'Manage Portofolio',
            'menu_name' => 'Layout',
            'url' => 'manage_portofolio/layout',
            'icon' => '<i class=\\"fad fa-swatchbook fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 17,
            'module' => 'manage_promotion',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 7,
            'menu_parent_code' => 'manage_promotion',
            'menu_parent_name' => 'Manage Promotion',
            'menu_name' => 'List of Promotion',
            'url' => 'manage_promotion',
            'icon' => '<i class=\\"fad fa-list fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 18,
            'module' => 'manage_promotion',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 7,
            'menu_parent_code' => 'manage_promotion',
            'menu_parent_name' => 'Manage Promotion',
            'menu_name' => 'Add New',
            'url' => 'manage_promotion/addpost',
            'icon' => '<i class=\\"fad fa-plus fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 19,
            'module' => 'manage_promotion',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 7,
            'menu_parent_code' => 'manage_promotion',
            'menu_parent_name' => 'Manage Promotion',
            'menu_name' => 'Promotion Categories',
            'url' => 'manage_promotion/category',
            'icon' => '<i class=\\"fad fa-folder fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 20,
            'module' => 'manage_promotion',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 7,
            'menu_parent_code' => 'manage_promotion',
            'menu_parent_name' => 'Manage Promotion',
            'menu_name' => 'Layout',
            'url' => 'manage_promotion/layout',
            'icon' => '<i class=\\"fad fa-swatchbook fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 21,
            'module' => 'manage_appearance',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 8,
            'menu_parent_code' => 'manage_appearance',
            'menu_parent_name' => 'Manage Appearance',
            'menu_name' => 'Logo',
            'url' => 'manage_appearance/logo',
            'icon' => '<i class=\\"fad fa-swatchbook fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 22,
            'module' => 'manage_appearance',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 8,
            'menu_parent_code' => 'manage_appearance',
            'menu_parent_name' => 'Manage Appearance',
            'menu_name' => 'Slideshow',
            'url' => 'manage_appearance/slideshow',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 23,
            'module' => 'manage_appearance',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 8,
            'menu_parent_code' => 'manage_appearance',
            'menu_parent_name' => 'Manage Appearance',
            'menu_name' => 'Cover Image',
            'url' => 'manage_appearance/coverimage',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 24,
            'module' => 'manage_appearance',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 8,
            'menu_parent_code' => 'manage_appearance',
            'menu_parent_name' => 'Manage Appearance',
            'menu_name' => 'Page Style',
            'url' => 'manage_appearance/pagestyle',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 25,
            'module' => 'manage_appearance',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 8,
            'menu_parent_code' => 'manage_appearance',
            'menu_parent_name' => 'Manage Appearance',
            'menu_name' => 'Layout',
            'url' => 'manage_appearance/layout',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 26,
            'module' => 'manage_section_content',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 9,
            'menu_parent_code' => 'manage_section_content',
            'menu_parent_name' => 'Manage Section Content',
            'menu_name' => 'Content In Pages',
            'url' => 'manage_section_content/pages',
            'icon' => '<i class=\\"fad fa-swatchbook fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 27,
            'module' => 'manage_section_content',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 9,
            'menu_parent_code' => 'manage_section_content',
            'menu_parent_name' => 'Manage Section Content',
            'menu_name' => 'Header',
            'url' => 'manage_section_content/header',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 28,
            'module' => 'manage_section_content',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 9,
            'menu_parent_code' => 'manage_section_content',
            'menu_parent_name' => 'Manage Section Content',
            'menu_name' => 'Footer',
            'url' => 'manage_section_content/footer',
            'icon' => '<i class=\\"fad fa-images fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 29,
            'module' => 'manage_dropdown',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 10,
            'menu_parent_code' => 'manage_dropdown',
            'menu_parent_name' => 'Manage Dropdown Menu',
            'menu_name' => 'List of Dropdown Menu',
            'url' => 'manage_dropdown',
            'icon' => '<i class=\\"fad fa-list fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 30,
            'module' => 'manage_dropdown',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 10,
            'menu_parent_code' => 'manage_dropdown',
            'menu_parent_name' => 'Manage Dropdown Menu',
            'menu_name' => 'Add New',
            'url' => 'manage_dropdown/addpost',
            'icon' => '<i class=\\"fad fa-plus fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ],
        [
            'id' => 31,
            'module' => 'manage_header',
            'menu_with_parent' => 'false',
            'menu_parent_id' => 11,
            'menu_parent_code' => 'manage_header',
            'menu_parent_name' => 'Manage Header Menu',
            'menu_name' => 'List of Header Menu',
            'url' => 'manage_header',
            'icon' => '<i class=\\"fad fa-list fa-fw me-2\\"></i>',
            'roles' => '99',
            'status' => 0
        ]
        ]);
    }
}
