<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuParentmenuJsonSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menu_parentmenu_json')->insert([
        [
            'id' => 1,
            'menu_page' => 'awesome_admin',
            'menu_vars' => '[{\\"parent_code\\": \\"hBMt85z8I4p3dgfZCt1sf4\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"manage_article\\", \\"parent_name\\": \\"Manage Articles\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [\\"Administrator\\", \\"Super Admin\\"], \\"category_code\\": \\"uIxTa0lV3L4EaV9A6BvJ7x\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"custom_input\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"<i class=\\\\\\"fal fa-newspaper fa-fw\\\\\\"></i>\\", \\"parent_permissions\\": \\"\\"}, {\\"parent_code\\": \\"ktGbOw0EloeZX73WIs50VO\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"manage_coverimage\\", \\"parent_name\\": \\"Manage Cover Image\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [], \\"category_code\\": \\"uIxTa0lV3L4EaV9A6BvJ7x\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"custom_input\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"<i class=\\\\\\"fal fa-puzzle-piece fa-fw\\\\\\"></i>\\", \\"parent_permissions\\": \\"\\"}, {\\"parent_code\\": \\"dqV84cjEjCrmp0BWF0fxpn\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"filemanager\\", \\"parent_name\\": \\"File Manager\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [\\"Super Admin\\", \\"Administrator\\", \\"General Member\\"], \\"category_code\\": \\"uIxTa0lV3L4EaV9A6BvJ7x\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"custom_input\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"<i class=\\\\\\"fal fa-file-alt fa-fw\\\\\\"></i>\\", \\"parent_permissions\\": \\"\\"}]',
            'menu_vars_backup' => '[{\\"parent_code\\": \\"hBMt85z8I4p3dgfZCt1sf4\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"manage_article\\", \\"parent_name\\": \\"Manage Articles\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [\\"Administrator\\", \\"Super Admin\\"], \\"category_code\\": \\"uIxTa0lV3L4EaV9A6BvJ7x\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"custom_input\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"<i class=\\\\\\"fal fa-newspaper fa-fw\\\\\\"></i>\\", \\"parent_permissions\\": \\"\\"}, {\\"parent_code\\": \\"ktGbOw0EloeZX73WIs50VO\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"manage_coverimage\\", \\"parent_name\\": \\"Manage Cover Image\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [], \\"category_code\\": \\"uIxTa0lV3L4EaV9A6BvJ7x\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"custom_input\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"<i class=\\\\\\"fal fa-puzzle-piece fa-fw\\\\\\"></i>\\", \\"parent_permissions\\": \\"\\"}, {\\"parent_code\\": \\"dqV84cjEjCrmp0BWF0fxpn\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"filemanager\\", \\"parent_name\\": \\"File Manager\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [\\"Super Admin\\", \\"Administrator\\", \\"General Member\\"], \\"category_code\\": \\"uIxTa0lV3L4EaV9A6BvJ7x\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"custom_input\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"<i class=\\\\\\"fal fa-file-alt fa-fw\\\\\\"></i>\\", \\"parent_permissions\\": \\"\\"}, {\\"parent_code\\": \\"nT21heY6KH8npGso0DM6yl\\", \\"parent_icon\\": \\"\\", \\"parent_link\\": \\"account\\", \\"parent_name\\": \\"Accounts\\", \\"parent_type\\": \\"custom\\", \\"parent_roles\\": [\\"Super Admin\\"], \\"category_code\\": \\"\\", \\"parent_icon_url\\": \\"\\", \\"parent_icon_path\\": \\"\\", \\"parent_icon_type\\": \\"\\", \\"is_for_parent_menu\\": \\"single\\", \\"parent_icon_custom\\": \\"\\", \\"parent_permissions\\": \\"\\"}]'
        ]
        ]);
    }
}
