<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('notifications')->insert([
        [
            'id' => 1,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 2,
            'to_fullname' => 'Andhika Adhitia N',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new rule',
            'message' => 'Andhika has assign to new rule',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:31:29',
            'created_at' => '2025-07-15 04:31:29'
        ],
        [
            'id' => 2,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 2,
            'to_fullname' => 'Andhika Adhitia N',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new rule',
            'message' => 'Andhika has assign to new rule',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:33:32',
            'created_at' => '2025-07-15 04:33:32'
        ],
        [
            'id' => 3,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 2,
            'to_fullname' => 'Andhika Adhitia N',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new rule',
            'message' => 'Andhika has assign to new rule',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:33:54',
            'created_at' => '2025-07-15 04:33:54'
        ],
        [
            'id' => 4,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'follower',
            'message' => 'You have been followed by Aruna',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:34:22',
            'created_at' => '2025-07-15 04:34:22'
        ],
        [
            'id' => 5,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'follower',
            'message' => 'You have been followed by Rajo Langit',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:34:33',
            'created_at' => '2025-07-15 04:34:33'
        ],
        [
            'id' => 6,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new follower',
            'message' => 'You have been followed by Gumara Peto Alam',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:34:52',
            'created_at' => '2025-07-15 04:34:52'
        ],
        [
            'id' => 7,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'user',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new follower',
            'message' => 'You have been followed by Gumara Peto Alam',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:35:03',
            'created_at' => '2025-07-15 04:35:03'
        ],
        [
            'id' => 8,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new follower',
            'message' => 'You have been followed by Gumara Peto Alam',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:35:38',
            'created_at' => '2025-07-15 04:35:38'
        ],
        [
            'id' => 9,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'system',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:46:12',
            'created_at' => '2025-07-15 04:46:12'
        ],
        [
            'id' => 10,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:47:03',
            'created_at' => '2025-07-15 04:47:03'
        ],
        [
            'id' => 11,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-15 04:48:19',
            'created_at' => '2025-07-15 04:48:19'
        ],
        [
            'id' => 12,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-15 06:54:13',
            'created_at' => '2025-07-15 06:54:13'
        ],
        [
            'id' => 13,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-15 07:00:48',
            'created_at' => '2025-07-15 07:00:48'
        ],
        [
            'id' => 14,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:07:32',
            'created_at' => '2025-07-22 03:07:32'
        ],
        [
            'id' => 15,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:07:47',
            'created_at' => '2025-07-22 03:07:47'
        ],
        [
            'id' => 16,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:07:47',
            'created_at' => '2025-07-22 03:07:47'
        ],
        [
            'id' => 17,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:11:16',
            'created_at' => '2025-07-22 03:11:16'
        ],
        [
            'id' => 18,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:11:17',
            'created_at' => '2025-07-22 03:11:17'
        ],
        [
            'id' => 19,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:11:29',
            'created_at' => '2025-07-22 03:11:29'
        ],
        [
            'id' => 20,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:11:41',
            'created_at' => '2025-07-22 03:11:41'
        ],
        [
            'id' => 21,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 03:11:44',
            'created_at' => '2025-07-22 03:11:44'
        ],
        [
            'id' => 22,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-22 10:16:13',
            'created_at' => '2025-07-22 10:16:13'
        ],
        [
            'id' => 23,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-23 02:34:49',
            'created_at' => '2025-07-23 02:34:49'
        ],
        [
            'id' => 24,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-23 08:56:16',
            'created_at' => '2025-07-23 08:56:16'
        ],
        [
            'id' => 25,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-23 09:18:12',
            'created_at' => '2025-07-23 09:18:12'
        ],
        [
            'id' => 26,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-24 03:23:53',
            'created_at' => '2025-07-24 03:23:53'
        ],
        [
            'id' => 27,
            'user_id' => 1,
            'from_id' => 1,
            'from_fullname' => 'Administrator',
            'to_id' => 1,
            'to_fullname' => 'Administrator',
            'type' => 'general',
            'icon' => '<i class=\\"fad fa-bullhorn fa-fw fa-lg\\"></i>',
            'title' => 'new status',
            'message' => 'You role has been changed to Premium Member',
            'hasread' => 0,
            'updated_at' => '2025-07-24 06:51:52',
            'created_at' => '2025-07-24 06:51:52'
        ]
        ]);
    }
}
