<?php

return [
    'container' => [
        'type' => 'container',
        'label' => 'Container',
        'category' => 'layout',
        'icon' => 'fas fa-cube',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/layout/container/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/layout/container/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/layout/container/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.layout.container',
        'toolbox' => true,
    ],
    'container_fluid' => [
        'type' => 'container_fluid',
        'label' => 'Container Fluid',
        'category' => 'layout',
        'icon' => 'fas fa-cube',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/layout/container-fluid/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/layout/container-fluid/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/layout/container-fluid/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.layout.container-fluid',
        'toolbox' => false,
    ],
    'grid' => [
        'type' => 'grid',
        'label' => 'Grid',
        'category' => 'layout',
        'icon' => 'fas fa-th-large',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/layout/grid/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/layout/grid/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/layout/grid/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.layout.grid',
        'toolbox' => true,
    ],
    'row_grid' => [
        'type' => 'row_grid',
        'label' => 'Row Grid',
        'category' => 'layout',
        'icon' => 'fas fa-th-large',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/layout/row-grid/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/layout/row-grid/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/layout/row-grid/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.layout.row-grid',
        'toolbox' => false,
    ],
    'heading' => [
        'type' => 'heading',
        'label' => 'Heading',
        'category' => 'basic',
        'icon' => 'fas fa-heading',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/heading/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/heading/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/heading/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.heading',
        'toolbox' => true,
    ],
    'video' => [
        'type' => 'video',
        'label' => 'Video',
        'category' => 'basic',
        'icon' => 'fas fa-video',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/video/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/video/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/video/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.video',
        'toolbox' => true,
    ],
    'google_maps' => [
        'type' => 'google_maps',
        'label' => 'Google Maps',
        'category' => 'basic',
        'icon' => 'fas fa-map-marker-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/google-maps/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/google-maps/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/google-maps/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.google-maps',
        'toolbox' => true,
    ],
    'image_box' => [
        'type' => 'image_box',
        'label' => 'Image Box',
        'category' => 'general',
        'icon' => 'far fa-image',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/image-box/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/image-box/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/image-box/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_image_box',
        'toolbox' => true,
    ],
    'icon_box' => [
        'type' => 'icon_box',
        'label' => 'Icon Box',
        'category' => 'general',
        'icon' => 'far fa-star',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/icon-box/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/icon-box/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/icon-box/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_icon_box',
        'toolbox' => true,
    ],
    'image_carousel' => [
        'type' => 'image_carousel',
        'label' => 'Image Carousel',
        'category' => 'general',
        'icon' => 'fas fa-images',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/image-carousel/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/image-carousel/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/image-carousel/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_image_carousel',
        'toolbox' => true,
    ],
    'basic_gallery' => [
        'type' => 'basic_gallery',
        'label' => 'Basic Gallery',
        'category' => 'general',
        'icon' => 'fas fa-th',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/basic-gallery/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/basic-gallery/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/basic-gallery/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_basic_gallery',
        'toolbox' => true,
    ],
    'feature_showcase' => [
        'type' => 'feature_showcase',
        'label' => 'Feature Showcase',
        'category' => 'general',
        'icon' => 'fas fa-layer-group',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/feature-showcase/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/feature-showcase/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/feature-showcase/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_feature_showcase',
        'toolbox' => true,
    ],
    'icon_list' => [
        'type' => 'icon_list',
        'label' => 'Icon List',
        'category' => 'general',
        'icon' => 'fas fa-list-ul',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/icon-list/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/icon-list/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/icon-list/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_icon_list',
        'toolbox' => true,
    ],
    'tabs' => [
        'type' => 'tabs',
        'label' => 'Tabs',
        'category' => 'general',
        'icon' => 'far fa-folder',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/tabs/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/tabs/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/tabs/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.general.tabs',
        'toolbox' => true,
    ],
    'accordion' => [
        'type' => 'accordion',
        'label' => 'Accordion',
        'category' => 'general',
        'icon' => 'fas fa-bars',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/advanced/accordion/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/advanced/accordion/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/advanced/accordion/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_accordion',
        'toolbox' => true,
    ],
    'counter' => [
        'type' => 'counter',
        'label' => 'Counter',
        'category' => 'general',
        'icon' => 'fas fa-sort-numeric-up',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/counter/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/counter/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/counter/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_counter',
        'toolbox' => true,
    ],
    'progress_bar' => [
        'type' => 'progress_bar',
        'label' => 'Progress Bar',
        'category' => 'general',
        'icon' => 'fas fa-tasks',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/progress-bar/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/progress-bar/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/progress-bar/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_progress_bar',
        'toolbox' => true,
    ],
    'testimonial' => [
        'type' => 'testimonial',
        'label' => 'Testimonial',
        'category' => 'general',
        'icon' => 'fas fa-quote-left',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/testimonial/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/testimonial/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/testimonial/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_testimonial',
        'toolbox' => true,
    ],
    'social_icons' => [
        'type' => 'social_icons',
        'label' => 'Social Icons',
        'category' => 'general',
        'icon' => 'fas fa-share-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/social-icons/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/social-icons/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/social-icons/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_social_icons',
        'toolbox' => true,
    ],
    'alert' => [
        'type' => 'alert',
        'label' => 'Alert',
        'category' => 'general',
        'icon' => 'fas fa-exclamation-triangle',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/alert/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/alert/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/alert/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_alert',
        'toolbox' => true,
    ],
    'rating' => [
        'type' => 'rating',
        'label' => 'Rating',
        'category' => 'general',
        'icon' => 'fas fa-star-half-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/rating/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/rating/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/rating/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_rating',
        'toolbox' => true,
    ],
    'text_path' => [
        'type' => 'text_path',
        'label' => 'Text Path',
        'category' => 'general',
        'icon' => 'fas fa-bezier-curve',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/general/text-path/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/general/text-path/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/general/text-path/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_text_path',
        'toolbox' => true,
    ],
    'form' => [
        'type' => 'form', 'label' => 'Form', 'category' => 'pro', 'icon' => 'fab fa-wpforms',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/form/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'slides' => [
        'type' => 'slides', 'label' => 'Slides', 'category' => 'pro', 'icon' => 'fas fa-sliders-h',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/slides/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'animated_headline' => [
        'type' => 'animated_headline', 'label' => 'Animated Headline', 'category' => 'pro', 'icon' => 'fas fa-heading',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/animated-headline/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'hotspot' => [
        'type' => 'hotspot', 'label' => 'Hotspot', 'category' => 'pro', 'icon' => 'fas fa-map-marker-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/hotspot/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'price_list' => [
        'type' => 'price_list', 'label' => 'Price List', 'category' => 'pro', 'icon' => 'fas fa-list-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/price-list/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'price_table' => [
        'type' => 'price_table', 'label' => 'Price Table', 'category' => 'pro', 'icon' => 'fas fa-tags',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/price-table/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'call_to_action' => [
        'type' => 'call_to_action', 'label' => 'Call to Action', 'category' => 'pro', 'icon' => 'fas fa-bullhorn',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/call-to-action/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'countdown' => [
        'type' => 'countdown', 'label' => 'Countdown', 'category' => 'pro', 'icon' => 'fas fa-hourglass-half',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/countdown/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'carousel' => [
        'type' => 'carousel', 'label' => 'Carousel', 'category' => 'pro', 'icon' => 'fas fa-clone',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/carousel/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'reviews' => [
        'type' => 'reviews', 'label' => 'Reviews', 'category' => 'pro', 'icon' => 'fas fa-comments',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/reviews/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'testimonial_carousel' => [
        'type' => 'testimonial_carousel', 'label' => 'Testimonial Carousel', 'category' => 'pro', 'icon' => 'fas fa-quote-right',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/testimonial-carousel/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'media_carousel' => [
        'type' => 'media_carousel', 'label' => 'Media Carousel', 'category' => 'pro', 'icon' => 'fas fa-photo-video',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/media-carousel/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'hero_banner' => [
        'type' => 'hero_banner', 'label' => 'Hero Banner', 'category' => 'pro', 'icon' => 'fas fa-image',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/hero-banner/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/hero-banner/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/hero-banner/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.pro.hero-banner', 'toolbox' => true,
    ],
    'hero_slider' => [
        'type' => 'hero_slider', 'label' => 'Hero Slider', 'category' => 'pro', 'icon' => 'fas fa-photo-video',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/hero-slider/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/hero-slider/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/hero-slider/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.pro.hero-slider', 'toolbox' => true,
    ],
    'flip_box' => [
        'type' => 'flip_box', 'label' => 'Flip Box', 'category' => 'pro', 'icon' => 'fas fa-sync-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/flip-box/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'code_highlight' => [
        'type' => 'code_highlight', 'label' => 'Code Highlight', 'category' => 'pro', 'icon' => 'fas fa-code',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/code-highlight/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'blockquote' => [
        'type' => 'blockquote', 'label' => 'Blockquote', 'category' => 'pro', 'icon' => 'fas fa-quote-left',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/blockquote/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'share_buttons' => [
        'type' => 'share_buttons', 'label' => 'Share Buttons', 'category' => 'pro', 'icon' => 'fas fa-share-alt',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/share-buttons/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'progress_tracker' => [
        'type' => 'progress_tracker', 'label' => 'Progress Tracker', 'category' => 'pro', 'icon' => 'fas fa-tasks',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/progress-tracker/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'video_playlist' => [
        'type' => 'video_playlist', 'label' => 'Video Playlist', 'category' => 'pro', 'icon' => 'fas fa-list',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/video-playlist/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/shared/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.partials.render_pro_widget', 'toolbox' => true,
    ],
    'product_color_selector' => [
        'type' => 'product_color_selector', 'label' => 'Product Color Selector', 'category' => 'pro', 'icon' => 'fas fa-palette',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/pro/product-color-selector/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/pro/product-color-selector/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/pro/product-color-selector/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.pro.product-color-selector', 'toolbox' => true,
    ],
    'text_editor' => [
        'type' => 'text_editor',
        'label' => 'Text Editor',
        'category' => 'basic',
        'icon' => 'fas fa-edit',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/text-editor/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/text-editor/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/text-editor/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.text-editor',
        'toolbox' => true,
    ],
    'image' => [
        'type' => 'image',
        'label' => 'Image',
        'category' => 'basic',
        'icon' => 'far fa-image',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/image/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/image/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/image/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.image',
        'toolbox' => true,
    ],
    'button' => [
        'type' => 'button',
        'label' => 'Button',
        'category' => 'basic',
        'icon' => 'fas fa-link',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/button/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/button/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/button/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.button',
        'toolbox' => true,
    ],
    'divider' => [
        'type' => 'divider',
        'label' => 'Divider',
        'category' => 'basic',
        'icon' => 'fas fa-minus',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/divider/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/divider/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/divider/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.divider',
        'toolbox' => true,
    ],
    'spacer' => [
        'type' => 'spacer',
        'label' => 'Spacer',
        'category' => 'basic',
        'icon' => 'fas fa-arrows-alt-v',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/spacer/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/spacer/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/spacer/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.spacer',
        'toolbox' => true,
    ],
    'icon' => [
        'type' => 'icon',
        'label' => 'Icon',
        'category' => 'basic',
        'icon' => 'far fa-star',
        'definition' => 'js/pagebuilder_elementor_v23/widgets/basic/icon/definition.js',
        'canvas' => 'js/pagebuilder_elementor_v23/widgets/basic/icon/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor_v23/widgets/basic/icon/Settings.vue',
        'view' => 'pagebuilder_elementor_v23.widgets.basic.icon',
        'toolbox' => true,
    ],
];
