<?php

return [
    'heading' => [
        'type' => 'heading',
        'label' => 'Heading',
        'category' => 'basic',
        'icon' => 'fas fa-heading',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/heading/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/heading/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/heading/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.heading',
        'toolbox' => true,
    ],
    'text_editor' => [
        'type' => 'text_editor',
        'label' => 'Text Editor',
        'category' => 'basic',
        'icon' => 'fas fa-edit',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/text-editor/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/text-editor/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/text-editor/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.text-editor',
        'toolbox' => true,
    ],
    'image' => [
        'type' => 'image',
        'label' => 'Image',
        'category' => 'basic',
        'icon' => 'far fa-image',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/image/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/image/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/image/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.image',
        'toolbox' => true,
    ],
    'button' => [
        'type' => 'button',
        'label' => 'Button',
        'category' => 'basic',
        'icon' => 'fas fa-link',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/button/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/button/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/button/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.button',
        'toolbox' => true,
    ],
    'divider' => [
        'type' => 'divider',
        'label' => 'Divider',
        'category' => 'basic',
        'icon' => 'fas fa-minus',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/divider/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/divider/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/divider/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.divider',
        'toolbox' => true,
    ],
    'spacer' => [
        'type' => 'spacer',
        'label' => 'Spacer',
        'category' => 'basic',
        'icon' => 'fas fa-arrows-alt-v',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/spacer/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/spacer/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/spacer/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.spacer',
        'toolbox' => true,
    ],
    'icon' => [
        'type' => 'icon',
        'label' => 'Icon',
        'category' => 'basic',
        'icon' => 'far fa-star',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/icon/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/icon/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/icon/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.icon',
        'toolbox' => true,
    ],
];
