<?php

return [
    'container' => [
        'type' => 'container',
        'label' => 'Container',
        'category' => 'layout',
        'icon' => 'fas fa-cube',
        'definition' => 'js/pagebuilder_elementor/widgets/layout/container/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/layout/container/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/layout/container/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.layout.container',
        'toolbox' => true,
    ],
    'container_fluid' => [
        'type' => 'container_fluid',
        'label' => 'Container Fluid',
        'category' => 'layout',
        'icon' => 'fas fa-cube',
        'definition' => 'js/pagebuilder_elementor/widgets/layout/container-fluid/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/layout/container-fluid/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/layout/container-fluid/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.layout.container-fluid',
        'toolbox' => true,
    ],
    'grid' => [
        'type' => 'grid',
        'label' => 'Grid',
        'category' => 'layout',
        'icon' => 'fas fa-th-large',
        'definition' => 'js/pagebuilder_elementor/widgets/layout/grid/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/layout/grid/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/layout/grid/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.layout.grid',
        'toolbox' => true,
    ],
    'row_grid' => [
        'type' => 'row_grid',
        'label' => 'Row Grid',
        'category' => 'layout',
        'icon' => 'fas fa-th-large',
        'definition' => 'js/pagebuilder_elementor/widgets/layout/row-grid/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/layout/row-grid/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/layout/row-grid/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.layout.row-grid',
        'toolbox' => true,
    ],
    'heading' => [
        'type' => 'heading',
        'label' => 'Heading',
        'category' => 'basic',
        'icon' => 'fas fa-heading',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/heading/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/heading/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/heading/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.heading',
        'toolbox' => true,
    ],
    'video' => [
        'type' => 'video',
        'label' => 'Video',
        'category' => 'basic',
        'icon' => 'fas fa-video',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/video/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/video/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/video/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.video',
        'toolbox' => true,
    ],
    'image_box' => [
        'type' => 'image_box',
        'label' => 'Image Box',
        'category' => 'general',
        'icon' => 'far fa-image',
        'definition' => 'js/pagebuilder_elementor/widgets/general/image-box/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/general/image-box/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/general/image-box/Settings.vue',
        'view' => 'pagebuilder_elementor.partials.render_image_box',
        'toolbox' => true,
    ],
    'tabs' => [
        'type' => 'tabs',
        'label' => 'Tabs',
        'category' => 'general',
        'icon' => 'far fa-folder',
        'definition' => 'js/pagebuilder_elementor/widgets/general/tabs/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/general/tabs/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/general/tabs/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.general.tabs',
        'toolbox' => true,
    ],
    'accordion' => [
        'type' => 'accordion',
        'label' => 'Accordion',
        'category' => 'general',
        'icon' => 'fas fa-bars',
        'definition' => 'js/pagebuilder_elementor/widgets/advanced/accordion/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/advanced/accordion/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/advanced/accordion/Settings.vue',
        'view' => 'pagebuilder_elementor.partials.render_accordion',
        'toolbox' => true,
    ],
    'text_editor' => [
        'type' => 'text_editor',
        'label' => 'Text Editor',
        'category' => 'basic',
        'icon' => 'fas fa-edit',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/text-editor/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/text-editor/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/text-editor/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.text-editor',
        'toolbox' => true,
    ],
    'image' => [
        'type' => 'image',
        'label' => 'Image',
        'category' => 'basic',
        'icon' => 'far fa-image',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/image/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/image/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/image/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.image',
        'toolbox' => true,
    ],
    'button' => [
        'type' => 'button',
        'label' => 'Button',
        'category' => 'basic',
        'icon' => 'fas fa-link',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/button/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/button/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/button/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.button',
        'toolbox' => true,
    ],
    'divider' => [
        'type' => 'divider',
        'label' => 'Divider',
        'category' => 'basic',
        'icon' => 'fas fa-minus',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/divider/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/divider/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/divider/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.divider',
        'toolbox' => true,
    ],
    'spacer' => [
        'type' => 'spacer',
        'label' => 'Spacer',
        'category' => 'basic',
        'icon' => 'fas fa-arrows-alt-v',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/spacer/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/spacer/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/spacer/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.spacer',
        'toolbox' => true,
    ],
    'icon' => [
        'type' => 'icon',
        'label' => 'Icon',
        'category' => 'basic',
        'icon' => 'far fa-star',
        'definition' => 'js/pagebuilder_elementor/widgets/basic/icon/definition.js',
        'canvas' => 'js/pagebuilder_elementor/widgets/basic/icon/Canvas.vue',
        'settings' => 'js/pagebuilder_elementor/widgets/basic/icon/Settings.vue',
        'view' => 'pagebuilder_elementor.widgets.basic.icon',
        'toolbox' => true,
    ],
];
