@php
    $settings = is_array($node['settings'] ?? null) ? $node['settings'] : [];
    $nodeId = trim((string) ($node['id'] ?? 'progress-bar')) ?: 'progress-bar';
    $safeLength = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?(?:px|pt|%|em|rem|vw|vh)?$/i', $raw) ? $raw : $fallback; };
    $safeColor = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return $raw !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $raw) ? $raw : $fallback; };
    $enum = fn (mixed $value, array $allowed, string $fallback): string => in_array(strtolower(trim((string) $value)), $allowed, true) ? strtolower(trim((string) $value)) : $fallback;
    $responsive = function (string $base, string $suffix = '', mixed $fallback = '') use ($settings): mixed { $keys = $suffix === 'Mobile' ? [$base.'Mobile', $base.'Tablet', $base] : ($suffix === 'Tablet' ? [$base.'Tablet', $base] : [$base]); foreach ($keys as $key) { if (($settings[$key] ?? '') !== '' && ($settings[$key] ?? null) !== null) return $settings[$key]; } return $fallback; };
    $titleTag = $enum($settings['titleTag'] ?? 'div', ['h1','h2','h3','h4','h5','h6','div','span','p'], 'div');
    $titleTagFontSizes = ['h1' => '40px', 'h2' => '34px', 'h3' => '29px', 'h4' => '24px', 'h5' => '20px', 'h6' => '16px', 'div' => '14px', 'span' => '14px', 'p' => '14px'];
    $titleFontSizeMode = ($settings['titleFontSizeMode'] ?? 'auto') === 'custom' ? 'custom' : 'auto';
    $fontStyle = function (string $prefix, string $suffix = '') use ($settings, $responsive, $safeLength, $safeColor, $titleTag, $titleTagFontSizes, $titleFontSizeMode): string { $size = $prefix === 'title' && $titleFontSizeMode === 'auto' ? ($titleTagFontSizes[$titleTag] ?? '14px') : '14px'; $line = '1.4em'; $weight = preg_match('/^(?:normal|bold|[1-9]00)$/', trim((string) ($settings[$prefix.'FontWeight'] ?? '600'))) ? trim((string) ($settings[$prefix.'FontWeight'] ?? '600')) : '600'; return implode(';', ['font-family:inherit','font-size:'.$safeLength(($prefix === 'title' && $titleFontSizeMode === 'auto') ? $size : $responsive($prefix.'FontSize', $suffix, $size), $size),'font-weight:'.$weight,'line-height:'.$safeLength($responsive($prefix.'LineHeight', $suffix, $line), $line),'letter-spacing:'.$safeLength($responsive($prefix.'LetterSpacing', $suffix, '0px'), '0px'),'word-spacing:'.$safeLength($responsive($prefix.'WordSpacing', $suffix, '0px'), '0px'),'text-transform:'.($settings[$prefix.'TextTransform'] ?? 'none'),'font-style:'.($settings[$prefix.'FontStyle'] ?? 'normal'),'text-decoration:'.($settings[$prefix.'TextDecoration'] ?? 'none'),'color:'.$safeColor($settings[$prefix.'Color'] ?? '#344054', '#344054')]); };
    $percentage = is_numeric($settings['percentage'] ?? null) ? max(0, min(100, (float) $settings['percentage'])) : 75;
    $advanced = app(\App\Support\PageBuilderElementorV24\WidgetAdvancedStyleResolver::class)->resolve($settings, $nodeId, request());
    $rootClasses = array_values(array_unique(array_merge(['el-widget-progress-bar','pb-progress-bar'], $advanced['classes'])));
@endphp
<div id="{{ $advanced['id'] }}" class="{{ implode(' ', $rootClasses) }}" data-entrance-delay="{{ $advanced['entranceDelay'] }}" data-entrance-duration="{{ $advanced['entranceDuration'] }}" @foreach($advanced['attributes'] as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>
    @if(trim((string) ($settings['title'] ?? '')) !== '')<{{ $titleTag }} class="pb-progress-bar__title" style="{{ $fontStyle('title') }}">{{ (string) $settings['title'] }}</{{ $titleTag }}>@endif
    <div class="pb-progress-bar__track" role="progressbar" aria-valuenow="{{ $percentage }}" aria-valuemin="0" aria-valuemax="100" style="background-color:{{ $safeColor($settings['backgroundColor'] ?? '', '#eef1f4') }}"><div class="pb-progress-bar__fill" style="width:{{ $percentage }}%;background-color:{{ $safeColor($settings['progressColor'] ?? '', '#69727d') }};color:{{ $safeColor($settings['innerTextColor'] ?? '', '#fff') }}">@if(!empty($settings['displayPercentage']) || trim((string) ($settings['innerText'] ?? '')) !== '')<span class="pb-progress-bar__inner-text">{{ trim((string) ($settings['innerText'] ?? '')) !== '' ? (string) $settings['innerText'] : $percentage.'%' }}</span>@endif</div></div>
</div>
<style>{!! $advanced['css'] !!}</style>
