<template>
	<div class="pb-widget-settings pb-widget-settings--general-new pb-widget-settings--progress-bar">
		<div class="pb-tab-nav"><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button></div>
		<div v-if="editor.settingsTab==='content'" class="pb-tab-content"><details class="pb-collapsible" open><summary>Progress Bar</summary><div class="pb-collapsible-body">
			<div class="pb-form-group"><label class="pb-form-label">Title</label><input class="pb-input" v-model="node.settings.title" placeholder="Web Design"></div>
			<div class="pb-form-row pb-form-row--two"><div class="pb-form-group"><label class="pb-form-label">Title HTML Tag</label><select class="pb-select" v-model="node.settings.titleTag"><option v-for="tag in titleTags" :key="tag" :value="tag">{{tag.toUpperCase()}}</option></select></div><div class="pb-form-group"><label class="pb-form-label">Percentage</label><input class="pb-input" type="number" min="0" max="100" v-model.number="node.settings.percentage"></div></div>
			<div class="pb-form-group pb-toggle-label-row"><label class="pb-form-label mb-0">Display Percentage</label><div class="pb-toggle-switch-wrap"><div class="pb-toggle-wrap"><input :id="'progress-display-' + node.id" type="checkbox" class="pb-toggle" v-model="node.settings.displayPercentage"><label :for="'progress-display-' + node.id"></label></div><span class="pb-toggle-state">{{node.settings.displayPercentage?'On':'Off'}}</span></div></div>
			<div class="pb-form-group"><label class="pb-form-label">Inner Text</label><input class="pb-input" v-model="node.settings.innerText" placeholder="Optional text"></div>
		</div></details></div>
		<div v-if="editor.settingsTab==='style'" class="pb-tab-content"><details class="pb-collapsible" open><summary>Progress Bar</summary><div class="pb-collapsible-body"><color-control label="Progress Bar Color" setting-key="progressColor" :node="node" /><color-control label="Background" setting-key="backgroundColor" :node="node" /><color-control label="Inner Text Color" setting-key="innerTextColor" :node="node" /></div></details><details class="pb-collapsible"><summary>Title</summary><div class="pb-collapsible-body"><color-control label="Color" setting-key="titleColor" :node="node" /><component :is="editor.typographyControl" prefix="title" :settings="node.settings" :responsive-device="editor.responsiveDevice" :font-families="editor.fontFamilies" :reset-defaults="{FontSize:'14px',FontWeight:'600',LineHeight:'1.4em'}" font-size-mode-key="titleFontSizeMode" @responsive-device="editor.setResponsiveDevice" /></div></details></div>
		<div v-if="editor.settingsTab==='advanced'" class="pb-tab-content"><component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" :show-display-conditions="false" :show-cache-settings="false" :elementor-choices="true" @responsive-device="editor.setResponsiveDevice" @choose-media="editor.chooseMedia(node.settings,$event)" @clear-media="editor.clearMedia(node.settings,$event)" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" /></div>
	</div>
</template>

<script>
const ColorControl={props:['label','settingKey','node'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><input class="pb-input coloris pb-coloris-input" v-model="node.settings[settingKey]"></div>`};
export default {name:'GeneralProgressBarSettings',props:{node:{type:Object,required:true},editor:{type:Object,required:true}},components:{ColorControl},data(){return{titleTags:['h1','h2','h3','h4','h5','h6','div','span','p']}}};
</script>

<style scoped>
.pb-widget-settings--general-new .pb-form-row{display:grid;gap:12px}.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:repeat(2,minmax(0,1fr))}.pb-widget-settings--general-new .pb-form-group{margin-bottom:14px}.pb-widget-settings--general-new .pb-form-row .pb-form-group{margin-bottom:0}.pb-widget-settings--general-new .pb-collapsible-body{padding-top:13px}.pb-widget-settings--general-new .pb-input,.pb-widget-settings--general-new .pb-select{min-height:36px}@media(max-width:420px){.pb-widget-settings--general-new .pb-form-row--two{grid-template-columns:1fr}}
</style>
