<section v-if="optionsModal.section === 'thumbnail' && surface === 'archive'" id="article-template-option-panel-thumbnail" role="tabpanel" aria-labelledby="article-template-option-tab-thumbnail" tabindex="-1" class="article-template-options-section">
    <div class="article-template-options-section__heading"><span>4</span><div><h5>{{ t('Thumbnail') }}</h5><small>{{ t('Choose how every archive thumbnail is rendered and framed.') }}</small></div></div>
    <div class="article-template-options-fields">
        <div class="article-template-option-row article-template-option-row--three">
            <label>{{ t('Display mode') }}<select class="form-select" v-model="optionsModal.value.thumbnail.mode"><option value="background">{{ t('Background image') }}</option><option value="asset">{{ t('Full asset image') }}</option></select></label>
            <label v-if="optionsModal.value.thumbnail.mode === 'background'">{{ t('Height') }}<span class="article-template-unit-control"><input class="form-control" type="number" min="0" :max="dimensionMax('thumbnail.height')" :step="dimensionStep('thumbnail.height')" :value="dimensionValue('thumbnail.height')" @input="setDimensionValue('thumbnail.height', $event.target.value)"><select class="form-select" :value="dimensionUnit('thumbnail.height')" @change="setDimensionUnit('thumbnail.height', $event.target.value)" aria-label="{{ t('Height unit') }}"><option v-for="unit in unitChoices()" :key="'thumbnail-height-'+unit" :value="unit">@{{ unit }}</option></select></span></label>
            <label>{{ t('Image fit') }}<select class="form-select" v-model="optionsModal.value.thumbnail.fit"><option value="cover">Cover</option><option value="contain">Contain</option></select></label>
            <label>{{ t('Background color') }}<input class="form-control article-template-coloris" type="text" v-model="optionsModal.value.thumbnail.background_color"></label>
        </div>
        <div class="article-template-option-row article-template-option-row--frame">
            <label class="form-check form-switch"><input class="form-check-input" type="checkbox" v-model="optionsModal.value.thumbnail.frame.enabled" @change="scheduleColorisInit"><span class="form-check-label">{{ t('Override thumbnail frame') }}</span></label>
            <div v-if="optionsModal.value.thumbnail.frame.enabled" class="article-template-frame-fields">
                <label>{{ t('Border color') }}<input class="form-control article-template-coloris" type="text" v-model="optionsModal.value.thumbnail.frame.border_color"></label>
                <label>{{ t('Border width') }}<span class="article-template-unit-control"><input class="form-control" type="number" min="0" :max="dimensionMax('thumbnail.frame.border_width', 'border')" :step="dimensionStep('thumbnail.frame.border_width', 'border')" :value="dimensionValue('thumbnail.frame.border_width', 'border')" @input="setDimensionValue('thumbnail.frame.border_width', $event.target.value, 'border')"><select class="form-select" :value="dimensionUnit('thumbnail.frame.border_width', 'border')" @change="setDimensionUnit('thumbnail.frame.border_width', $event.target.value, 'border')"><option v-for="unit in unitChoices('border')" :key="unit" :value="unit">@{{ unit }}</option></select></span></label>
                <div class="article-template-radius-control">
                    <div class="article-template-radius-label-row"><label class="article-template-radius-label">{{ t('Border radius') }}</label><select class="form-select article-template-radius-unit" :value="radiusUnit('thumbnail.frame.radius')" @change="setRadiusUnit('thumbnail.frame.radius', $event.target.value)"><option v-for="unit in unitChoices('radius')" :key="'thumbnail-radius-'+unit" :value="unit">@{{ unit }}</option></select></div>
                    <div class="article-template-radius-fields"><label v-for="(corner, index) in radiusCorners" :key="'thumbnail-radius-'+corner.key" class="article-template-radius-side"><input class="form-control" type="number" min="0" :max="radiusMax('thumbnail.frame.radius')" :step="radiusStep('thumbnail.frame.radius')" :value="radiusValue('thumbnail.frame.radius', index)" @input="setRadiusValue('thumbnail.frame.radius', index, $event.target.value)"><span>@{{ corner.label }}</span></label><div class="article-template-radius-link-cell"><button type="button" class="btn article-template-radius-link" :class="{ active: isRadiusLinked('thumbnail.frame.radius') }" :title="isRadiusLinked('thumbnail.frame.radius') ? 'Unlink values' : 'Link values'" :aria-label="isRadiusLinked('thumbnail.frame.radius') ? 'Unlink values' : 'Link values'" @click="toggleRadiusLinked('thumbnail.frame.radius')"><i class="fas" :class="isRadiusLinked('thumbnail.frame.radius') ? 'fa-link' : 'fa-unlink'" aria-hidden="true"></i></button></div></div>
                </div>
            </div>
        </div>
    </div>
</section>

<section v-if="optionsModal.section === 'pagination' && surface === 'archive'" id="article-template-option-panel-pagination" role="tabpanel" aria-labelledby="article-template-option-tab-pagination" tabindex="-1" class="article-template-options-section">
    <div class="article-template-options-section__heading"><span>5</span><div><h5>{{ t('Pagination') }}</h5><small>{{ t('Control total data, alignment, footer frame, and responsive spacing.') }}</small></div></div>
    <div class="article-template-options-fields">
        <div class="article-template-option-row article-template-option-row--pagination-model">
            <label class="article-template-reading-list-control">{{ t('Pagination model') }}<select class="form-select" v-model="optionsModal.value.pagination.type"><option value="underline">{{ t('Minimal Underline') }}</option><option value="boxed">{{ t('Classic Boxed') }}</option><option value="soft">{{ t('Soft Highlight') }}</option></select></label>
        </div>
        <div class="article-template-option-row article-template-pagination-range">
            <div class="article-template-pagination-range__label"><span>{{ t('Page range') }}</span><small>{{ t('Number of page links shown around the active page.') }}</small></div>
            <div class="article-template-pagination-range__fields">
                <label>{{ t('Desktop') }}<input class="form-control" type="number" min="1" max="9" step="1" :value="paginationRangeValue('desktop')" @input="setPaginationRange('desktop', $event.target.value)"></label>
                <label>{{ t('Tablet') }}<input class="form-control" type="number" min="1" max="9" step="1" :value="paginationRangeValue('tablet')" @input="setPaginationRange('tablet', $event.target.value)"></label>
                <label>{{ t('Mobile') }}<input class="form-control" type="number" min="1" max="9" step="1" :value="paginationRangeValue('mobile')" @input="setPaginationRange('mobile', $event.target.value)"></label>
            </div>
        </div>
        <div class="article-template-pagination-style-fields">
            <label>{{ t('Pagination button radius') }}<span class="article-template-unit-control"><input class="form-control" type="number" min="0" :max="dimensionMax('pagination.item_radius', 'radius')" :step="dimensionStep('pagination.item_radius', 'radius')" :value="dimensionValue('pagination.item_radius', 'radius')" @input="setDimensionValue('pagination.item_radius', $event.target.value, 'radius')"><select class="form-select" :value="dimensionUnit('pagination.item_radius', 'radius')" @change="setDimensionUnit('pagination.item_radius', $event.target.value, 'radius')"><option v-for="unit in unitChoices('radius')" :key="'pagination-item-radius-'+unit" :value="unit">@{{ unit }}</option></select></span></label>
            <label>{{ t('Pagination number gap') }}<span class="article-template-unit-control"><input class="form-control" type="number" min="0" :max="dimensionMax('pagination.item_gap')" :step="dimensionStep('pagination.item_gap')" :value="dimensionValue('pagination.item_gap')" @input="setDimensionValue('pagination.item_gap', $event.target.value)"><select class="form-select" :value="dimensionUnit('pagination.item_gap')" @change="setDimensionUnit('pagination.item_gap', $event.target.value)"><option v-for="unit in unitChoices()" :key="'pagination-item-gap-'+unit" :value="unit">@{{ unit }}</option></select></span></label>
            <label>{{ t('Previous icon') }}<select class="form-select" v-model="optionsModal.value.pagination.previous_icon"><option value="fas fa-chevron-left">Chevron left</option><option value="fas fa-angle-left">Angle left</option><option value="fas fa-arrow-left">Arrow left</option></select></label>
            <label>{{ t('Next icon') }}<select class="form-select" v-model="optionsModal.value.pagination.next_icon"><option value="fas fa-chevron-right">Chevron right</option><option value="fas fa-angle-right">Angle right</option><option value="fas fa-arrow-right">Arrow right</option></select></label>
            <label>{{ t('Normal background') }}<input class="form-control article-template-coloris" type="text" placeholder="Model default" v-model="optionsModal.value.pagination.item_background_color"></label>
            <label>{{ t('Normal text') }}<input class="form-control article-template-coloris" type="text" placeholder="Model default" v-model="optionsModal.value.pagination.item_text_color"></label>
            <label>{{ t('Border color') }}<input class="form-control article-template-coloris" type="text" placeholder="Model default" v-model="optionsModal.value.pagination.item_border_color"></label>
            <label>{{ t('Hover background') }}<input class="form-control article-template-coloris" type="text" placeholder="Theme surface" v-model="optionsModal.value.pagination.item_hover_background_color"></label>
            <label>{{ t('Hover text') }}<input class="form-control article-template-coloris" type="text" placeholder="Theme default" v-model="optionsModal.value.pagination.item_hover_text_color"></label>
            <label>{{ t('Active background') }}<input class="form-control article-template-coloris" type="text" placeholder="Theme accent" v-model="optionsModal.value.pagination.item_active_background_color"></label>
            <label>{{ t('Active text') }}<input class="form-control article-template-coloris" type="text" placeholder="Theme default" v-model="optionsModal.value.pagination.item_active_text_color"></label>
        </div>
        <div class="article-template-option-row article-template-option-row--toolbar">
            <label class="form-check form-switch"><input class="form-check-input" type="checkbox" v-model="optionsModal.value.pagination.show_total"><span class="form-check-label">{{ t('Show Total Data') }}</span></label>
            <div class="btn-group article-template-position" role="group" aria-label="{{ t('Pagination position') }}"><button v-for="position in ['left', 'center', 'right']" :key="position" type="button" class="btn" :class="optionsModal.value.pagination.position === position ? 'btn-primary' : 'btn-outline-secondary'" @click="optionsModal.value.pagination.position = position">@{{ position }}</button></div>
        </div>
        <div class="article-template-option-row article-template-option-row--frame">
            <label class="form-check form-switch"><input class="form-check-input" type="checkbox" v-model="optionsModal.value.pagination.frame.enabled" @change="scheduleColorisInit"><span class="form-check-label">{{ t('Show footer frame') }}</span></label>
            <div v-if="optionsModal.value.pagination.frame.enabled" class="article-template-frame-fields">
                <label>{{ t('Border color') }}<input class="form-control article-template-coloris" type="text" v-model="optionsModal.value.pagination.frame.border_color"></label>
                <label>{{ t('Border width') }}<span class="article-template-unit-control"><input class="form-control" type="number" min="0" :max="dimensionMax('pagination.frame.border_width', 'border')" :step="dimensionStep('pagination.frame.border_width', 'border')" :value="dimensionValue('pagination.frame.border_width', 'border')" @input="setDimensionValue('pagination.frame.border_width', $event.target.value, 'border')"><select class="form-select" :value="dimensionUnit('pagination.frame.border_width', 'border')" @change="setDimensionUnit('pagination.frame.border_width', $event.target.value, 'border')"><option v-for="unit in unitChoices('border')" :key="unit" :value="unit">@{{ unit }}</option></select></span></label>
                <div class="article-template-radius-control">
                    <div class="article-template-radius-label-row"><label class="article-template-radius-label">{{ t('Border radius') }}</label><select class="form-select article-template-radius-unit" :value="radiusUnit('pagination.frame.radius')" @change="setRadiusUnit('pagination.frame.radius', $event.target.value)"><option v-for="unit in unitChoices('radius')" :key="'pagination-radius-'+unit" :value="unit">@{{ unit }}</option></select></div>
                    <div class="article-template-radius-fields"><label v-for="(corner, index) in radiusCorners" :key="'pagination-radius-'+corner.key" class="article-template-radius-side"><input class="form-control" type="number" min="0" :max="radiusMax('pagination.frame.radius')" :step="radiusStep('pagination.frame.radius')" :value="radiusValue('pagination.frame.radius', index)" @input="setRadiusValue('pagination.frame.radius', index, $event.target.value)"><span>@{{ corner.label }}</span></label><div class="article-template-radius-link-cell"><button type="button" class="btn article-template-radius-link" :class="{ active: isRadiusLinked('pagination.frame.radius') }" :title="isRadiusLinked('pagination.frame.radius') ? 'Unlink values' : 'Link values'" :aria-label="isRadiusLinked('pagination.frame.radius') ? 'Unlink values' : 'Link values'" @click="toggleRadiusLinked('pagination.frame.radius')"><i class="fas" :class="isRadiusLinked('pagination.frame.radius') ? 'fa-link' : 'fa-unlink'" aria-hidden="true"></i></button></div></div>
                </div>
                <label>{{ t('Background color') }}<input class="form-control article-template-coloris" type="text" v-model="optionsModal.value.pagination.frame.background_color"></label>
            </div>
        </div>
        <template v-for="box in spacingBoxes" :key="'pagination-'+box.key">
            <div class="article-template-box-control">
                <div class="article-template-box-control__header">
                    <label class="form-check form-switch article-template-box-control__toggle"><span class="form-check-label">@{{ box.label }}</span><input class="form-check-input" type="checkbox" v-model="optionsModal.value.pagination[box.key].enabled"></label>
                    <select v-if="optionsModal.value.pagination[box.key].enabled" class="form-select article-template-box-control__unit-select" :value="boxUnit('pagination.'+box.key, optionsDevice)" @change="setBoxUnit('pagination.'+box.key, optionsDevice, $event.target.value)" :aria-label="box.label + ' unit'"><option v-for="unit in unitChoices()" :key="unit" :value="unit">@{{ unit }}</option></select>
                </div>
                <div v-if="optionsModal.value.pagination[box.key].enabled" class="article-template-box-control__body">
                    <div class="article-template-box-control__inputs"><label v-for="side in boxSides" :key="side.key"><input class="form-control" type="number" min="0" :max="boxMax('pagination.'+box.key, optionsDevice)" :step="boxStep('pagination.'+box.key, optionsDevice)" :value="boxValue('pagination.'+box.key, optionsDevice, side.key)" @input="setBoxValue('pagination.'+box.key, optionsDevice, side.key, $event.target.value)"><span>@{{ side.label }}</span></label><button type="button" class="btn article-template-box-control__link" :class="{ active: isBoxLinked('pagination.'+box.key, optionsDevice) }" :title="isBoxLinked('pagination.'+box.key, optionsDevice) ? 'Unlink values' : 'Link values'" :aria-label="isBoxLinked('pagination.'+box.key, optionsDevice) ? 'Unlink values' : 'Link values'" @click="toggleBoxLinked('pagination.'+box.key, optionsDevice)"><i class="fas" :class="isBoxLinked('pagination.'+box.key, optionsDevice) ? 'fa-link' : 'fa-unlink'" aria-hidden="true"></i></button></div>
                </div>
            </div>
        </template>
    </div>
</section>

<section v-if="optionsModal.section === 'article-title' && surface === 'archive'" id="article-template-option-panel-article-title" role="tabpanel" aria-labelledby="article-template-option-tab-article-title" tabindex="-1" class="article-template-options-section">
    <div class="article-template-options-section__heading"><span>6</span><div><h5>{{ t('Article title tag') }}</h5><small>{{ t('Set the semantic heading level for all archive item titles.') }}</small></div></div>
    <label class="article-template-select-label">{{ t('Heading level') }}<select class="form-select" v-model="optionsModal.value.article_title.tag"><option v-for="tag in ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']" :key="tag" :value="tag">@{{ tag.toUpperCase() }}</option></select></label>
</section>

<section v-if="optionsModal.section === 'shell'" id="article-template-option-panel-shell" role="tabpanel" aria-labelledby="article-template-option-tab-shell" tabindex="-1" class="article-template-options-section">
    <div class="article-template-options-section__heading"><span>@{{ surface === 'archive' ? 7 : 2 }}</span><div><h5>@{{ surface === 'archive' ? 'Archive shell' : 'Detail shell' }}</h5><small>{{ t('Apply responsive spacing and a global frame without changing the template layout.') }}</small></div></div>
    <div class="article-template-options-fields">
        <template v-for="box in spacingBoxes" :key="'shell-'+box.key">
            <div class="article-template-box-control">
                <div class="article-template-box-control__header">
                    <label class="form-check form-switch article-template-box-control__toggle"><span class="form-check-label">@{{ box.label }}</span><input class="form-check-input" type="checkbox" v-model="optionsModal.value.shell[box.key].enabled"></label>
                    <select v-if="optionsModal.value.shell[box.key].enabled" class="form-select article-template-box-control__unit-select" :value="boxUnit('shell.'+box.key, optionsDevice)" @change="setBoxUnit('shell.'+box.key, optionsDevice, $event.target.value)" :aria-label="box.label + ' unit'"><option v-for="unit in unitChoices()" :key="unit" :value="unit">@{{ unit }}</option></select>
                </div>
                <div v-if="optionsModal.value.shell[box.key].enabled" class="article-template-box-control__body">
                    <div class="article-template-box-control__inputs"><label v-for="side in boxSides" :key="side.key"><input class="form-control" type="number" min="0" :max="boxMax('shell.'+box.key, optionsDevice)" :step="boxStep('shell.'+box.key, optionsDevice)" :value="boxValue('shell.'+box.key, optionsDevice, side.key)" @input="setBoxValue('shell.'+box.key, optionsDevice, side.key, $event.target.value)"><span>@{{ side.label }}</span></label><button type="button" class="btn article-template-box-control__link" :class="{ active: isBoxLinked('shell.'+box.key, optionsDevice) }" :title="isBoxLinked('shell.'+box.key, optionsDevice) ? 'Unlink values' : 'Link values'" :aria-label="isBoxLinked('shell.'+box.key, optionsDevice) ? 'Unlink values' : 'Link values'" @click="toggleBoxLinked('shell.'+box.key, optionsDevice)"><i class="fas" :class="isBoxLinked('shell.'+box.key, optionsDevice) ? 'fa-link' : 'fa-unlink'" aria-hidden="true"></i></button></div>
                </div>
            </div>
        </template>
        <div class="article-template-option-row article-template-option-row--frame">
            <label class="form-check form-switch"><input class="form-check-input" type="checkbox" v-model="optionsModal.value.shell.frame.enabled" @change="scheduleColorisInit"><span class="form-check-label">{{ t('Override shell frame') }}</span></label>
            <div v-if="optionsModal.value.shell.frame.enabled" class="article-template-frame-fields">
                <label>{{ t('Border color') }}<input class="form-control article-template-coloris" type="text" v-model="optionsModal.value.shell.frame.border_color"></label>
                <label>{{ t('Border width') }}<span class="article-template-unit-control"><input class="form-control" type="number" min="0" :max="dimensionMax('shell.frame.border_width', 'border')" :step="dimensionStep('shell.frame.border_width', 'border')" :value="dimensionValue('shell.frame.border_width', 'border')" @input="setDimensionValue('shell.frame.border_width', $event.target.value, 'border')"><select class="form-select" :value="dimensionUnit('shell.frame.border_width', 'border')" @change="setDimensionUnit('shell.frame.border_width', $event.target.value, 'border')"><option v-for="unit in unitChoices('border')" :key="unit" :value="unit">@{{ unit }}</option></select></span></label>
                <div class="article-template-radius-control">
                    <div class="article-template-radius-label-row"><label class="article-template-radius-label">{{ t('Border radius') }}</label><select class="form-select article-template-radius-unit" :value="radiusUnit('shell.frame.radius')" @change="setRadiusUnit('shell.frame.radius', $event.target.value)"><option v-for="unit in unitChoices('radius')" :key="'shell-radius-'+unit" :value="unit">@{{ unit }}</option></select></div>
                    <div class="article-template-radius-fields"><label v-for="(corner, index) in radiusCorners" :key="'shell-radius-'+corner.key" class="article-template-radius-side"><input class="form-control" type="number" min="0" :max="radiusMax('shell.frame.radius')" :step="radiusStep('shell.frame.radius')" :value="radiusValue('shell.frame.radius', index)" @input="setRadiusValue('shell.frame.radius', index, $event.target.value)"><span>@{{ corner.label }}</span></label><div class="article-template-radius-link-cell"><button type="button" class="btn article-template-radius-link" :class="{ active: isRadiusLinked('shell.frame.radius') }" :title="isRadiusLinked('shell.frame.radius') ? 'Unlink values' : 'Link values'" :aria-label="isRadiusLinked('shell.frame.radius') ? 'Unlink values' : 'Link values'" @click="toggleRadiusLinked('shell.frame.radius')"><i class="fas" :class="isRadiusLinked('shell.frame.radius') ? 'fa-link' : 'fa-unlink'" aria-hidden="true"></i></button></div></div>
                </div>
                <label>{{ t('Background color') }}<input class="form-control article-template-coloris" type="text" v-model="optionsModal.value.shell.frame.background_color"></label>
            </div>
        </div>
    </div>
</section>
