<template>
	<div class="pb-widget-settings pb-widget-settings--general-new pb-widget-settings--text-path">
		<div class="pb-tab-nav"><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button></div>
		<div v-show="editor.settingsTab==='content'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Text Path</summary><div class="pb-collapsible-body">
				<div class="pb-form-group"><label class="pb-form-label">Text</label><textarea class="pb-input" rows="3" v-model="node.settings.text"></textarea></div>
				<div class="pb-form-group"><label class="pb-form-label">Path Type</label><select class="pb-select" v-model="node.settings.pathType"><option v-for="option in pathTypes" :key="option.value" :value="option.value">{{option.label}}</option></select></div>
				<div v-if="node.settings.pathType==='custom'" class="pb-form-group"><label class="pb-form-label">Custom SVG</label><div class="pb-bg-media-field pb-widget-settings__media-field" :class="{'has-image':!!node.settings.customSvgUrl}"><div class="pb-bg-media-preview pb-text-path-svg-preview"><i class="fas fa-bezier-curve"></i><button type="button" class="pb-bg-media-center-btn" :title="node.settings.customSvgUrl?'Change SVG':'Choose SVG'" @click="editor.chooseMedia(node.settings,'customSvgUrl','Paste SVG URL')"><i :class="node.settings.customSvgUrl?'fas fa-pen':'fas fa-plus'"></i></button></div><div class="pb-bg-media-actions"><button type="button" class="pb-bg-media-choose" @click="editor.chooseMedia(node.settings,'customSvgUrl','Paste SVG URL')">Choose SVG</button><button type="button" class="pb-bg-media-remove" :disabled="!node.settings.customSvgUrl" title="Remove SVG" @click="editor.clearMedia(node.settings,'customSvgUrl')"><i class="fas fa-trash-alt"></i></button></div></div><p class="pb-control-help">Choose an SVG containing a path. The first valid path is used for the text.</p></div>
				<div class="pb-form-group"><label class="pb-form-label">Link</label><component :is="editor.linkControl" :url="node.settings.linkUrl" :target="node.settings.linkTarget" :nofollow="node.settings.linkNofollow" :custom-attributes="node.settings.linkCustomAttributes" @update:url="node.settings.linkUrl=$event" @update:target="node.settings.linkTarget=$event" @update:nofollow="node.settings.linkNofollow=$event" @update:customAttributes="node.settings.linkCustomAttributes=$event" /></div>
				<responsive-choice label="Alignment" base="alignment" control-id="text-path-alignment" :node="node" :editor="editor" :options="alignmentOptions" />
				<div class="pb-form-group"><label class="pb-form-label">Text Direction</label><select class="pb-select" v-model="node.settings.textDirection"><option value="default">Default</option><option value="rtl">RTL</option><option value="ltr">LTR</option></select></div>
				<div class="pb-form-group pb-toggle-label-row"><label class="pb-form-label mb-0">Show Path</label><div class="pb-toggle-switch-wrap"><div class="pb-toggle-wrap"><input :id="'text-path-show-'+node.id" type="checkbox" class="pb-toggle" v-model="node.settings.showPath"><label :for="'text-path-show-'+node.id"></label></div><span class="pb-toggle-state">{{node.settings.showPath?'On':'Off'}}</span></div></div>
			</div></details>
		</div>

		<div v-show="editor.settingsTab==='style'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Text Path</summary><div class="pb-collapsible-body">
				<size-control label="Size" base="size" control-id="text-path-size" fallback="500px" :node="node" :editor="editor" :min="50" :max="1200" :allowed-units="['px']" />
				<size-control label="Rotate" base="rotate" control-id="text-path-rotate" fallback="0deg" :node="node" :editor="editor" :min="0" :max="360" :allowed-units="['deg']" />
				<div class="pb-section-subtitle">Text</div>
				<component :is="editor.typographyControl" aria-label="Typography" :settings="node.settings" prefix="text" :responsive-device="editor.responsiveDevice" control-id="text-path-typography" @responsive-device="editor.setResponsiveDevice" />
				<component :is="editor.textStrokeControl" aria-label="Text Stroke" :settings="node.settings" :responsive-device="editor.responsiveDevice" width-key="textStrokeWidth" color-key="textStrokeColor" control-id="text-path-stroke" :open="activeEffect==='text-path-stroke'" @request-open="activeEffect=$event" @responsive-device="editor.setResponsiveDevice" />
				<size-control label="Word Spacing" base="wordSpacing" control-id="text-path-word-spacing" fallback="0px" :node="node" :editor="editor" :min="0" :max="200" :allowed-units="['px']" />
				<scalar-control label="Starting Point (%)" setting-key="startingPoint" :node="node" :min="0" :max="100" :step="1" />
				<div class="pb-state-tabs pb-state-tabs--two"><button type="button" :class="{active:textState==='normal'}" @click="textState='normal'">Normal</button><button type="button" :class="{active:textState==='hover'}" @click="textState='hover'">Hover</button></div>
				<color-control :label="textState==='normal'?'Color':'Hover Color'" :setting-key="textState==='normal'?'textColor':'textColorHover'" :node="node" />
				<template v-if="textState==='hover'"><div class="pb-form-group"><label class="pb-form-label">Hover Animation</label><select class="pb-select" v-model="node.settings.hoverAnimation"><option v-for="option in hoverAnimations" :key="option.value" :value="option.value">{{option.label}}</option></select></div><div class="pb-form-group"><label class="pb-form-label">Transition Duration</label><div class="pb-value-with-unit pb-value-with-unit--full"><input class="pb-input pb-input-compact" type="number" min="0" max="10" step="0.1" v-model.number="node.settings.transitionDuration"><span class="pb-mini-unit pb-mini-unit--static">s</span></div></div></template>
			</div></details>

			<details v-if="node.settings.showPath" class="pb-collapsible" open><summary>Path</summary><div class="pb-collapsible-body">
				<div class="pb-state-tabs pb-state-tabs--two"><button type="button" :class="{active:pathState==='normal'}" @click="pathState='normal'">Normal</button><button type="button" :class="{active:pathState==='hover'}" @click="pathState='hover'">Hover</button></div>
				<color-control label="Color" :setting-key="pathState==='normal'?'pathColor':'pathColorHover'" :node="node" />
				<div class="pb-section-subtitle">Stroke</div>
				<color-control label="Color" :setting-key="pathState==='normal'?'pathStrokeColor':'pathStrokeColorHover'" :node="node" />
				<size-control label="Width" :base="pathState==='normal'?'pathStrokeWidth':'pathStrokeWidthHover'" :control-id="'text-path-path-width-'+pathState" fallback="1px" :node="node" :editor="editor" :min="0" :max="20" :allowed-units="['px']" />
				<div v-if="pathState==='hover'" class="pb-form-group"><label class="pb-form-label">Transition Duration</label><div class="pb-value-with-unit pb-value-with-unit--full"><input class="pb-input pb-input-compact" type="number" min="0" max="10" step="0.1" v-model.number="node.settings.pathTransitionDuration"><span class="pb-mini-unit pb-mini-unit--static">s</span></div></div>
			</div></details>
		</div>

		<div v-show="editor.settingsTab==='advanced'" class="pb-tab-content"><component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" :show-display-conditions="true" :show-cache-settings="true" :elementor-choices="true" @responsive-device="editor.setResponsiveDevice" @choose-media="editor.chooseMedia(node.settings,$event)" @clear-media="editor.clearMedia(node.settings,$event)" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" /></div>
	</div>
</template>

<script>
const ResponsiveMenu={props:['editor','id'],template:`<div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu(id)" :title="'Responsive: '+editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen(id)" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="id+'-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice(id,device.value)"><i :class="device.icon"></i><span>{{editor.deviceOptionLabel(device)}}</span></button></div></div>`};
const ResponsiveChoice={components:{ResponsiveMenu},props:['label','base','controlId','node','editor','options'],template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-btn-group pb-compact-choice"><button v-for="option in options" :key="base+'-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey(base)]===option.value}" :title="option.label" :aria-label="option.label" @click="editor.setResponsiveSetting(node.settings,base,option.value)"><i :class="option.icon"></i></button></div></div>`};
const SizeControl={components:{ResponsiveMenu},props:{label:String,base:String,controlId:String,fallback:String,node:Object,editor:Object,min:{type:Number,default:0},max:{type:Number,default:null},allowedUnits:{type:Array,default:()=>['px']}},computed:{options(){return{fallback:this.fallback,min:this.min,max:this.max,allowedUnits:this.allowedUnits,fallbackUnit:this.allowedUnits[0]||'px'}}},template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback,options):max" :step="editor.sizeControlStep(node,base,fallback,options)" :value="editor.sizeControlDisplayValue(node,base,fallback,options)" @input="editor.onSizeControlInput(node,base,$event,options)"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback,options):max" :value="editor.sizeControlDisplayValue(node,base,fallback,options)" @input="editor.onSizeControlInput(node,base,$event,options)"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node,base,fallback,options)" @change="editor.setSizeControlUnit(node,base,$event.target.value,options)"><option v-for="unit in allowedUnits" :key="unit" :value="unit">{{unit}}</option></select></div></div></div>`};
const ScalarControl={props:{label:String,settingKey:String,node:Object,min:Number,max:Number,step:Number},template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max" :step="step" v-model.number="node.settings[settingKey]"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max" :step="step" v-model.number="node.settings[settingKey]"></div></div>`};
const ColorControl={props:['label','settingKey','node'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><input class="pb-input coloris pb-coloris-input" :value="node.settings[settingKey]" @input="node.settings[settingKey]=$event.target.value"></div>`};
const animationLabels={'none':'None','grow':'Grow','shrink':'Shrink','pulse':'Pulse','pulse-grow':'Pulse Grow','pulse-shrink':'Pulse Shrink','push':'Push','pop':'Pop','bounce-in':'Bounce In','bounce-out':'Bounce Out','rotate':'Rotate','grow-rotate':'Grow Rotate','float':'Float','sink':'Sink','bob':'Bob','hang':'Hang','skew':'Skew','skew-forward':'Skew Forward','skew-backward':'Skew Backward','wobble-vertical':'Wobble Vertical','wobble-horizontal':'Wobble Horizontal','wobble-to-bottom-right':'Wobble To Bottom Right','wobble-to-top-right':'Wobble To Top Right','wobble-top':'Wobble Top','wobble-bottom':'Wobble Bottom','wobble-skew':'Wobble Skew','buzz':'Buzz','buzz-out':'Buzz Out'};
export default{name:'GeneralTextPathSettings',props:{node:{type:Object,required:true},editor:{type:Object,required:true}},components:{ResponsiveChoice,SizeControl,ScalarControl,ColorControl},data(){return{activeEffect:'',textState:'normal',pathState:'normal'}},computed:{pathTypes(){return[{value:'wave',label:'Wave'},{value:'arc',label:'Arc'},{value:'circle',label:'Circle'},{value:'line',label:'Line'},{value:'oval',label:'Oval'},{value:'spiral',label:'Spiral'},{value:'custom',label:'Custom'}]},alignmentOptions(){return[{value:'left',label:'Left',icon:'fas fa-align-left'},{value:'center',label:'Center',icon:'fas fa-align-center'},{value:'right',label:'Right',icon:'fas fa-align-right'}]},hoverAnimations(){return Object.entries(animationLabels).map(([value,label])=>({value,label}))}}};
</script>

<style scoped>
.pb-widget-settings--general-new .pb-form-group{margin-bottom:14px}.pb-widget-settings--general-new .pb-input,.pb-widget-settings--general-new .pb-select{min-height:36px}.pb-widget-settings--general-new textarea.pb-input{padding:9px 10px;resize:vertical}.pb-widget-settings--general-new .pb-compact-choice{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.pb-widget-settings--general-new .pb-compact-choice .pb-seg-btn{min-width:0;height:30px;padding:0 8px}.pb-widget-settings--general-new .pb-collapsible-body{padding-top:13px}.pb-section-subtitle{margin:18px 0 12px;padding-top:14px;border-top:1px solid #e8edf4;color:#344054;font-size:12px;font-weight:700}.pb-control-help{margin:7px 0 0;color:#7a8699;font-size:10px;line-height:1.45}.pb-text-path-svg-preview{display:grid;place-items:center;color:#7c8aa0;font-size:25px}.pb-value-with-unit--full{display:grid;grid-template-columns:minmax(0,1fr) 42px}.pb-mini-unit--static{display:grid;place-items:center;border-left:0;color:#667085;background:#f8fafc}.pb-state-tabs{margin:4px 0 14px}
</style>
