@php
    $settings = is_array($node['settings'] ?? null) ? $node['settings'] : [];
    $nodeId = trim((string) ($node['id'] ?? 'social-icons')) ?: 'social-icons';
    $safeLength = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return preg_match('/^-?\d+(?:\.\d+)?(?:px|pt|%|em|rem|vw|vh)?$/i', $raw) ? $raw : $fallback; };
    $safeColor = function (mixed $value, string $fallback): string { $raw = trim((string) $value); return $raw !== '' && preg_match('/^[#a-z0-9(),.%\s-]+$/i', $raw) ? $raw : $fallback; };
    $safeUrl = function (mixed $value): string { $url = trim((string) $value); return $url !== '' && !str_starts_with($url, '//') && preg_match('/^(?:https?:|mailto:|tel:|\/|#)/i', $url) ? $url : '#'; };
    $enum = fn (mixed $value, array $allowed, string $fallback): string => in_array(strtolower(trim((string) $value)), $allowed, true) ? strtolower(trim((string) $value)) : $fallback;
    $officialColors = ['facebook'=>['#1877f2','#fff'],'facebook-f'=>['#1877f2','#fff'],'twitter'=>['#1da1f2','#fff'],'instagram'=>['#e1306c','#fff'],'linkedin'=>['#0a66c2','#fff'],'youtube'=>['#ff0000','#fff'],'pinterest'=>['#bd081c','#fff'],'github'=>['#181717','#fff'],'whatsapp'=>['#25d366','#fff']];
    $svg = function (mixed $value): string { $raw = trim((string) $value); if ($raw === '' || !str_starts_with(strtolower($raw), '<svg')) return ''; $raw = preg_replace('/<script\b[^>]*>.*?<\/script>/is', '', $raw) ?? ''; $raw = preg_replace('/\s(?:on[a-z]+|style|xlink:href|href)\s*=\s*(?:"[^"]*"|\'[^\']*\'|[^\s>]+)/i', '', $raw) ?? ''; return strip_tags($raw, '<svg><g><path><circle><ellipse><rect><line><polyline><polygon><title><desc>'); };
    $items = array_values(array_filter(is_array($settings['items'] ?? null) ? $settings['items'] : [], 'is_array'));
    $shape = $enum($settings['shape'] ?? 'rounded', ['rounded','square','circle'], 'rounded'); $alignment = $enum($settings['alignment'] ?? 'left', ['left','center','right'], 'left'); $columns = in_array((string) ($settings['columns'] ?? 'auto'), ['auto','1','2','3','4','5','6'], true) ? (string) $settings['columns'] : 'auto'; $borderType = $enum($settings['borderType'] ?? 'none', ['none','solid','double','dotted','dashed'], 'none'); $hoverAnimation = $enum($settings['hoverAnimation'] ?? 'none', ['none','grow','shrink','pulse','pulse-grow','pulse-shrink','rotate'], 'none');
    $advanced = app(\App\Support\PageBuilderElementorV24\WidgetAdvancedStyleResolver::class)->resolve($settings, $nodeId, request());
    $rootClasses = array_values(array_unique(array_merge(['el-widget-social-icons','pb-social-icons','pb-social-icons--shape-'.$shape,'pb-social-icons--align-'.$alignment], $hoverAnimation !== 'none' ? ['pb-social-icons--hover-'.$hoverAnimation] : [], $advanced['classes'])));
    $rootStyle = implode(';', ['--pb-social-size:'.$safeLength($settings['size'] ?? '18px', '18px'),'--pb-social-padding:'.$safeLength($settings['padding'] ?? '10px', '10px'),'--pb-social-spacing:'.$safeLength($settings['spacing'] ?? '8px', '8px'),'--pb-social-row-gap:'.$safeLength($settings['rowsGap'] ?? '8px', '8px'),'--pb-social-border-width:'.$safeLength($settings['borderWidth'] ?? '1px', '1px'),'--pb-social-border-color:'.$safeColor($settings['borderColor'] ?? '', '#d0d7e6'),'--pb-social-border-style:'.$borderType,'--pb-social-border-radius:'.$safeLength($settings['borderRadius'] ?? '4px', '4px'),'--pb-social-duration:'.max(0, min(10, (float) ($settings['transitionDuration'] ?? .3))).'s','grid-template-columns:'.($columns === 'auto' ? 'repeat(auto-fit,minmax(40px,max-content))' : 'repeat('.(int) $columns.',minmax(0,max-content))')]);
@endphp
<div id="{{ $advanced['id'] }}" class="{{ implode(' ', $rootClasses) }}" style="{{ $rootStyle }}" data-entrance-delay="{{ $advanced['entranceDelay'] }}" data-entrance-duration="{{ $advanced['entranceDuration'] }}" @foreach($advanced['attributes'] as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>
    @foreach($items as $entry)
        @php $iconName = strtolower(trim((string) ($entry['iconName'] ?? ''))); $official = $officialColors[$iconName] ?? [$settings['primaryColor'] ?? '#405de6', $settings['secondaryColor'] ?? '#fff']; $primary = ($entry['colorMode'] ?? 'official') === 'custom' ? $safeColor($entry['primaryColor'] ?? '', $official[0]) : $official[0]; $secondary = ($entry['colorMode'] ?? 'official') === 'custom' ? $safeColor($entry['secondaryColor'] ?? '', $official[1]) : $official[1]; $iconClass = preg_match('/^(?:fas|far|fab|fal|fad)\s+fa-[a-z0-9-]+$/i', trim((string) ($entry['iconClass'] ?? ''))) ? trim((string) $entry['iconClass']) : 'fas fa-star'; $itemSvg = ($entry['iconSource'] ?? '') === 'svg' ? $svg($entry['iconSvg'] ?? '') : ''; $href = $safeUrl($entry['linkUrl'] ?? '#'); $itemTarget = ($entry['linkTarget'] ?? '') === '_blank' ? '_blank' : ''; $itemRel = $itemTarget === '_blank' ? 'noopener noreferrer' : ''; $attrs = []; foreach (($entry['linkCustomAttributes'] ?? []) as $attribute) { if (!is_array($attribute)) continue; $name = strtolower(trim((string) ($attribute['key'] ?? $attribute['name'] ?? ''))); if (preg_match('/^(?:aria-[a-z0-9_-]+|data-[a-z0-9_-]+|title|download|hreflang)$/', $name)) $attrs[$name] = (string) ($attribute['value'] ?? ''); } @endphp
        <a class="pb-social-icons__item" href="{{ $href }}" @if($itemTarget !== '') target="{{ $itemTarget }}" @endif @if($itemRel !== '') rel="{{ $itemRel }}" @endif style="--pb-social-primary:{{ $primary }};--pb-social-secondary:{{ $secondary }};--pb-social-hover-primary:{{ $safeColor($settings['primaryColorHover'] ?? '', '#4f46e5') }};--pb-social-hover-secondary:{{ $safeColor($settings['secondaryColorHover'] ?? '', '#fff') }}" aria-label="{{ e((string) ($entry['iconName'] ?? 'Social link')) }}" @foreach($attrs as $attributeName=>$attributeValue) {{ $attributeName }}="{{ e($attributeValue) }}" @endforeach>@if($itemSvg !== ''){!! $itemSvg !!}@else<i class="{{ $iconClass }}" aria-hidden="true"></i>@endif</a>
    @endforeach
</div>
<style>{!! $advanced['css'] !!}</style>
