<template>
	<div class="pb-widget-settings pb-widget-settings--general-new pb-widget-settings--rating">
		<div class="pb-tab-nav"><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='content'}" @click="editor.settingsTab='content'"><i class="fas fa-edit"></i><span>Content</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='style'}" @click="editor.settingsTab='style'"><i class="fas fa-adjust"></i><span>Style</span></button><button type="button" class="pb-tab-btn pb-tab-btn-icon" :class="{active:editor.settingsTab==='advanced'}" @click="editor.settingsTab='advanced'"><i class="fas fa-gear"></i><span>Advanced</span></button></div>
		<div v-show="editor.settingsTab==='content'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Rating</summary><div class="pb-collapsible-body">
				<scalar-control label="Rating Scale" setting-key="ratingScale" :node="node" :min="1" :max="10" :step="1" @change="clampRating" />
				<div class="pb-form-group"><label class="pb-form-label">Rating</label><input class="pb-input" type="number" min="0" :max="node.settings.ratingScale" step="0.5" v-model.number="node.settings.rating" @change="clampRating"></div>
				<div class="pb-form-group"><label class="pb-form-label">Icon</label><div class="pb-general-icon-picker">
					<button type="button" class="pb-icon-picker-field" title="Open Icon Library" @click="editor.openIconLibrary(node)"><div class="pb-icon-picker-preview"><span v-if="node.settings.iconSource==='svg' && node.settings.iconSvg" v-html="node.settings.iconSvg"></span><i v-else :class="node.settings.iconClass || 'fas fa-star'"></i></div><div class="pb-icon-picker-copy"><div class="pb-icon-picker-name">{{ iconLabel }}</div><div class="pb-icon-picker-style">{{ node.settings.iconSource==='svg'?'Custom SVG':editor.fontAwesomeStyleLabel(node.settings.iconStyle||'solid') }}</div></div><i class="fas fa-chevron-right"></i></button>
					<div class="pb-general-icon-picker__actions"><button type="button" title="Upload SVG" aria-label="Upload SVG" @click="editor.chooseRatingSvg(node)"><i class="fas fa-upload"></i></button><button type="button" title="Reset Icon" aria-label="Reset Icon" @click="resetIcon"><i class="fas fa-undo-alt"></i></button></div>
				</div></div>
				<responsive-choice label="Alignment" base="alignment" control-id="rating-alignment" :node="node" :editor="editor" :options="alignmentOptions" />
			</div></details>
		</div>
		<div v-show="editor.settingsTab==='style'" class="pb-tab-content">
			<details class="pb-collapsible" open><summary>Icon</summary><div class="pb-collapsible-body">
				<size-control label="Size" base="iconSize" control-id="rating-size" fallback="18px" :node="node" :editor="editor" :min="0" :max="100" :allowed-units="['px']" />
				<size-control label="Spacing" base="iconSpacing" control-id="rating-spacing" fallback="4px" :node="node" :editor="editor" :min="0" :max="100" :allowed-units="['px']" />
				<color-control label="Color" setting-key="markedColor" :node="node" />
				<color-control label="Unmarked Color" setting-key="unmarkedColor" :node="node" />
			</div></details>
		</div>
		<div v-show="editor.settingsTab==='advanced'" class="pb-tab-content"><component :is="editor.widgetAdvancedControls" :node="node" :responsive-device="editor.responsiveDevice" :show-display-conditions="true" :show-cache-settings="true" :elementor-choices="true" @responsive-device="editor.setResponsiveDevice" @choose-media="editor.chooseMedia(node.settings,$event)" @clear-media="editor.clearMedia(node.settings,$event)" @unavailable-ai="editor.showUnsupportedControlNotice('Animate With AI', 'AI service is not connected to this page builder.')" /></div>
	</div>
</template>

<script>
const ResponsiveMenu={props:['editor','id'],template:`<div class="pb-control-device-wrap"><button type="button" class="pb-control-device-btn" @click.stop="editor.openControlResponsiveMenu(id)" :title="'Responsive: '+editor.responsiveDeviceLabel()"><i :class="editor.responsiveDeviceIcon()"></i></button><div v-if="editor.isControlResponsiveMenuOpen(id)" class="pb-control-device-menu"><button v-for="device in editor.responsiveDevices" :key="id+'-'+device.value" type="button" class="pb-control-device-item" :class="{active:editor.responsiveDevice===device.value}" @click.stop="editor.applyResponsiveDevice(id,device.value)"><i :class="device.icon"></i><span>{{editor.deviceOptionLabel(device)}}</span></button></div></div>`};
const ResponsiveChoice={components:{ResponsiveMenu},props:['label','base','controlId','node','editor','options'],template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-btn-group pb-compact-choice"><button v-for="option in options" :key="base+'-'+option.value" type="button" class="pb-seg-btn" :class="{active:node.settings[editor.activeResponsiveKey(base)]===option.value}" :title="option.label" :aria-label="option.label" @click="editor.setResponsiveSetting(node.settings,base,option.value)"><i :class="option.icon"></i></button></div></div>`};
const SizeControl={components:{ResponsiveMenu},props:{label:String,base:String,controlId:String,fallback:String,node:Object,editor:Object,min:{type:Number,default:0},max:{type:Number,default:null},allowedUnits:{type:Array,default:()=>['px']}},computed:{options(){return{fallback:this.fallback,min:this.min,max:this.max,allowedUnits:this.allowedUnits,fallbackUnit:this.allowedUnits[0]||'px'}}},template:`<div class="pb-form-group"><div class="pb-label-row pb-label-row-device"><label class="pb-form-label mb-0">{{label}}</label><responsive-menu :editor="editor" :id="controlId"/></div><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback,options):max" :step="editor.sizeControlStep(node,base,fallback,options)" :value="editor.sizeControlDisplayValue(node,base,fallback,options)" @input="editor.onSizeControlInput(node,base,$event,options)"><div class="pb-value-with-unit"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max===null?editor.sizeControlMax(node,base,fallback,options):max" :value="editor.sizeControlDisplayValue(node,base,fallback,options)" @input="editor.onSizeControlInput(node,base,$event,options)"><select class="pb-mini-unit" :value="editor.sizeControlUnit(node,base,fallback,options)" @change="editor.setSizeControlUnit(node,base,$event.target.value,options)"><option v-for="unit in allowedUnits" :key="unit" :value="unit">{{unit}}</option></select></div></div></div>`};
const ScalarControl={props:{label:String,settingKey:String,node:Object,min:Number,max:Number,step:Number},emits:['change'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><div class="pb-range-value-row"><input class="pb-range" type="range" :min="min" :max="max" :step="step" v-model.number="node.settings[settingKey]" @input="$emit('change')"><input class="pb-input pb-input-compact" type="number" :min="min" :max="max" :step="step" v-model.number="node.settings[settingKey]" @change="$emit('change')"></div></div>`};
const ColorControl={props:['label','settingKey','node'],template:`<div class="pb-form-group"><label class="pb-form-label">{{label}}</label><input class="pb-input coloris pb-coloris-input" :value="node.settings[settingKey]" @input="node.settings[settingKey]=$event.target.value"></div>`};
export default{name:'GeneralRatingSettings',props:{node:{type:Object,required:true},editor:{type:Object,required:true}},components:{ResponsiveChoice,SizeControl,ScalarControl,ColorControl},computed:{alignmentOptions(){return[{value:'left',label:'Start',icon:'fas fa-align-left'},{value:'center',label:'Center',icon:'fas fa-align-center'},{value:'right',label:'End',icon:'fas fa-align-right'}]},iconLabel(){return this.node.settings.iconSource==='svg'?'Uploaded SVG':String(this.node.settings.iconName||'star').replace(/(^|[-_\s])(\w)/g,(_,space,letter)=>space+letter.toUpperCase())}},methods:{clampRating(){const scale=Math.max(1,Math.min(10,Math.round(Number(this.node.settings.ratingScale)||5)));this.node.settings.ratingScale=scale;this.node.settings.rating=Math.max(0,Math.min(scale,Math.round((Number(this.node.settings.rating)||0)*2)/2))},resetIcon(){Object.assign(this.node.settings,{iconSource:'library',iconStyle:'solid',iconName:'star',iconClass:'fas fa-star',iconSvg:''})}}};
</script>

<style scoped>
.pb-general-icon-picker{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:center}.pb-general-icon-picker__actions{display:grid;gap:5px}.pb-general-icon-picker__actions button{width:28px;height:28px;padding:0;border:1px solid #cdd8ea;border-radius:6px;background:#fff;color:#667085}.pb-general-icon-picker__actions button:hover{border-color:#aebdf7;background:#eef1ff;color:#5367ff}.pb-icon-picker-preview>span :deep(svg){width:20px;height:20px;fill:currentColor}.pb-widget-settings--general-new .pb-form-group{margin-bottom:14px}.pb-widget-settings--general-new .pb-input,.pb-widget-settings--general-new .pb-select{min-height:36px}.pb-widget-settings--general-new .pb-compact-choice{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.pb-widget-settings--general-new .pb-compact-choice .pb-seg-btn{min-width:0;height:30px;padding:0 8px}.pb-widget-settings--general-new .pb-collapsible-body{padding-top:13px}
</style>
